import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "203.0.113.14";

export const easyLevel4: ChainDef = {
  id: "easy-4",
  difficulty: "easy",
  order: 4,
  points: 100,
  title: "Grid Exposure",
  codename: "OPERATION COLD RELAY",
  summary: "One target. Everything you've learned so far, chained together. Find it before someone else does.",
  briefing: [
    "Cinder Hollow, Kansas — population 4,100. One electric co-op keeps the lights, the water pumps,",
    "and the regional hospital's cold-storage fridges running.",
    "",
    "Their customer portal has been sitting on an unpatched Apache box for three years.",
    "Nobody's looked at it since it was built. That's the problem.",
    "",
    "This one doesn't hand you a single vulnerability — it hands you a whole web app and asks you",
    "to work the full loop yourself: recon, enumerate, find the foothold, recover what you can,",
    "get in, and close the door behind you.",
    "",
    "Objective: find the way in. Recover what an attacker would recover. Lock the door behind you.",
  ],
  debrief: [
    "That's the easy tier in miniature: a public web app, a directory an admin forgot was indexable,",
    "and a backup file with plaintext credentials sitting inside it.",
    "",
    "In the real world this is CWE-530 (exposure of backup file) chained into credential reuse —",
    "consistently one of the highest-frequency findings in actual small-org penetration tests.",
    "No zero-days required. Just patience and a checklist.",
    "",
    "Grid secured. Cinder Hollow keeps the lights on.",
  ],
  nodes: [
    {
      id: "meridian",
      org: "Meridian Grid Co-op",
      city: "Cinder Hollow",
      state: "KS",
      coords: { x: 48.3, y: 30.2 },
      ip: IP,
      randomizableSecrets: ["Cinder2019!"],
      tagline: "Rural electric co-op — customer self-service portal",
      briefing: [
        "TARGET: Meridian Grid Co-op customer portal",
        `IP: ${IP}`,
        "KNOWN: public-facing web app, last redesigned 2021, no WAF observed",
        "",
        "Standard external web app assessment. Recon, enumerate, find your foothold, remediate.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Co-op flagged for review after a resident reported the portal 'looks broken'",
        "   in a few spots. Probably nothing. Check it anyway.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "webenum", label: "Discover hidden web content", tactic: "Discovery", requires: ["recon"] },
        {
          id: "creds",
          label: "Recover credentials from an exposed backup file",
          tactic: "Credential Access",
          requires: ["webenum"],
        },
        { id: "access", label: "Authenticate to the admin console", tactic: "Initial Access", requires: ["creds"] },
        { id: "secure", label: "Remediate the exposure and rotate credentials", tactic: "Remediation", requires: ["access"] },
      ],
      hints: [
        "Start with recon: scan the target for open services and versions. `nmap -sV <ip>` is a good start.",
        "The web server's up. Check what's publicly reachable — `curl http://<ip>/robots.txt`, then brute-force hidden directories with `gobuster dir -u http://<ip> -w common.txt`.",
        "robots.txt disallows a couple of paths for a reason — a human wrote that file, and now you know exactly where not to look... which is exactly where to look.",
        "Old backup files (.bak, .old, ~) left inside web-accessible directories are one of the most common real-world ways admin credentials leak. List the backup directory, then read what's inside.",
        "You've got valid admin credentials now. Try `login <username> <password>` against the admin console.",
        "You're in — but the job isn't done. This is a defensive exercise: remediate what you found with `secure system`.",
      ],
      debrief: [
        "root cause: an old config backup (portal_config.php.bak) was left inside a web-accessible,",
        "directory-listable folder, with the admin panel credentials hardcoded in plaintext.",
        "fix applied: backup removed, directory listing disabled, admin + DB credentials rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "Starting Nmap 7.94 ( https://nmap.org )",
              `Nmap scan report for portal.meridiangrid.example (${IP})`,
              "Host is up (0.031s latency).",
              "",
              "PORT    STATE SERVICE VERSION",
              "22/tcp  open  ssh     OpenSSH 8.2p1 Ubuntu",
              "80/tcp  open  http    Apache httpd 2.4.29 ((Ubuntu))",
              "443/tcp open  https   Apache httpd 2.4.29 ((Ubuntu))",
              "",
              "Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel",
              "Nmap done: 1 IP address (1 host up) scanned in 4.81 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["robots.txt", "/backup", "/admin"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          deniedOutput: ["curl: (7) Failed to connect — you haven't confirmed the service is up yet. Try nmap first."],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "Server: Apache/2.4.29 (Ubuntu)",
              "Content-Type: text/html",
              "",
              "<title>Meridian Grid Co-op — Customer Portal</title>",
              "<!-- built by contractor, do not modify without calling ext 214 -->",
              "",
              "tip: check /robots.txt",
            ],
          }),
        }),
        cmd({
          id: "robots",
          tool: "curl",
          requires: ["robots.txt"],
          help: "curl http://<ip>/robots.txt",
          requiresObjectives: ["recon"],
          run: () => ({
            tone: "output",
            output: ["User-agent: *", "Disallow: /admin/", "Disallow: /backup/", "Disallow: /old-site/"],
          }),
        }),
        cmd({
          id: "gobuster",
          tool: "gobuster",
          requires: [IP],
          help: "gobuster dir -u http://<ip> -w common.txt   — brute-force hidden directories",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "webenum",
            tone: "success",
            setsFlags: ["found_backup_dir"],
            output: [
              "===============================================================",
              "Gobuster v3.6",
              "===============================================================",
              `[+] Url: http://${IP}`,
              "[+] Method: GET",
              "[+] Wordlist: common.txt",
              "===============================================================",
              "/login                (Status: 200) [Size: 1821]",
              "/admin                (Status: 301) [Size: 312]",
              "/backup               (Status: 200) [Size: 954]  <- directory listing enabled",
              "/assets               (Status: 301) [Size: 312]",
              "/old-site             (Status: 403) [Size: 278]",
              "===============================================================",
            ],
          }),
        }),
        cmd({
          id: "list-backup",
          tool: "curl",
          requires: ["/backup"],
          forbids: [".bak", ".gz", ".sql"],
          help: "curl http://<ip>/backup/",
          requiresFlags: ["found_backup_dir"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "Index of /backup",
              "  ../",
              "  portal_config.php.bak       12-Mar-2023 02:11   3.2K",
              "  db_dump_2022.sql.gz         09-Sep-2022 22:04   118K",
              "",
              "tip: try fetching portal_config.php.bak directly",
            ],
          }),
        }),
        cmd({
          id: "cat-backup",
          tool: "curl",
          requires: ["portal_config.php.bak"],
          help: "curl http://<ip>/backup/portal_config.php.bak",
          requiresFlags: ["found_backup_dir"],
          run: () => ({
            completesObjective: "creds",
            tone: "success",
            setsFlags: ["have_creds"],
            note: "Meridian Grid Co-op admin console — mgrid_admin : Cinder2019!",
            output: [
              "HTTP/1.1 200 OK",
              "Content-Type: application/octet-stream",
              "",
              "<?php",
              "// portal_config.php — DO NOT COMMIT — dev copy",
              '$db_host = "127.0.0.1";',
              '$db_user = "mgrid_svc";',
              '$db_pass = "Sv1nter#Watts";',
              "",
              '$admin_user = "mgrid_admin";',
              '$admin_pass = "Cinder2019!";',
              "?>",
              "",
              "[+] plaintext admin credentials recovered: mgrid_admin : Cinder2019!",
            ],
          }),
        }),
        {
          id: "login",
          tool: "login",
          match: (input) => /^login\s+\S+\s+\S+$/.test(input.trim().toLowerCase()),
          help: "login <username> <password>   — authenticate to /admin",
          requiresFlags: ["have_creds"],
          deniedOutput: ["/admin redirects to a login form — you don't have credentials to try yet."],
          run: (input) => {
            const parts = input.trim().split(/\s+/);
            const user = parts[1]?.toLowerCase().replace(/^["']|["']$/g, "");
            const pass = parts[2]?.replace(/^["']|["']$/g, "");
            if (user === "mgrid_admin" && pass === "Cinder2019!") {
              return {
                completesObjective: "access",
                tone: "success",
                promptAfter: "mgrid_admin@portal:~$",
                output: [
                  "[+] authenticated as mgrid_admin",
                  "",
                  "=== Meridian Grid Co-op — Admin Console ===",
                  "outage map | billing | meter reads | user accounts | system",
                  "",
                  "ALERT: /backup/ has been crawled by external search bots for 14+ months.",
                  "Exposure window: HIGH. This needs to be remediated now.",
                ],
              };
            }
            return {
              tone: "error",
              output: [`[-] authentication failed for user '${parts[1] ?? ""}'`],
            };
          },
        },
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — remove the exposure and rotate credentials",
          requiresObjectives: ["access"],
          deniedOutput: ["you need admin console access before you can push a remediation."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] deleted /backup/portal_config.php.bak and /backup/db_dump_2022.sql.gz",
              "[+] disabled directory listing on /backup/ (Options -Indexes)",
              "[+] rotated mgrid_admin password",
              "[+] rotated mgrid_svc database password",
              "[+] filed disclosure note for the co-op's IT contractor",
              "",
              "MERIDIAN GRID CO-OP: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
