import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "203.0.113.77";

export const easyLevel2: ChainDef = {
  id: "easy-2",
  difficulty: "easy",
  order: 2,
  points: 50,
  title: "Open Kennel",
  codename: "OPERATION OPEN KENNEL",
  summary: "No password to guess. No backup file to find. Just a door nobody locked.",
  briefing: [
    "Cascade Hollow Animal Rescue runs an adoption-listings site built by a volunteer's nephew as a",
    "favor two summers ago. It works fine. Nobody's touched the backend since.",
    "",
    "This one isn't about breaking a lock. It's about finding out there was never a lock installed on",
    "the back door in the first place — the admin API doesn't check who's asking. It just answers.",
    "",
    "Prove it, then get it fixed before someone less friendly finds it first.",
  ],
  debrief: [
    "root cause: /api/admin had no authentication or authorization check at all — not weak, not",
    "default, just absent. This is CWE-306 (missing authentication for a critical function), part of",
    "OWASP A01:2021 Broken Access Control, and it's alarmingly common on APIs bolted onto small sites",
    "after the fact by whoever was available to build it.",
    "",
    "fix applied: session/API-key enforcement added to every /api/admin/* route, access logging",
    "turned on, the shelter's volunteer webmaster notified.",
  ],
  nodes: [
    {
      id: "cascadehollow",
      org: "Cascade Hollow Animal Rescue",
      city: "Cascade Hollow",
      state: "OR",
      coords: { x: 13.9, y: 13.9 },
      ip: IP,
      tagline: "Regional animal rescue — adoption listings & donor records",
      briefing: [
        "TARGET: Cascade Hollow Animal Rescue adoption site",
        `IP: ${IP}`,
        "KNOWN: volunteer-built site, no formal security review, ever",
        "",
        "Standard external check: see what's reachable, and whether everything that should require a login actually does.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Nothing specific reported — this is just a routine sweep of small local orgs.",
        "   Don't assume 'small' means 'nothing to find.'\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "webenum", label: "Discover the admin API via directory brute-force", tactic: "Discovery", requires: ["recon"] },
        {
          id: "access",
          label: "Access the admin API with no authentication required",
          tactic: "Initial Access",
          requires: ["webenum"],
        },
        { id: "secure", label: "Add authentication and access control to the admin API", tactic: "Remediation", requires: ["access"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "Brute-force the directory structure — `gobuster dir -u http://<ip> -w common.txt`. Pay attention to which paths return 200 versus 401/403.",
        "If /api/admin came back 200 without you sending any credentials at all, that's not a login you need to guess — that's a door that was never locked. Just ask it for what's there: `curl http://<ip>/api/admin`.",
        "You just proved anyone on the internet could pull donor records and delete listings with zero authentication. Lock it down: `secure system`.",
      ],
      debrief: [
        "root cause: the admin API had no auth check on any route — a missing control, not a broken one.",
        "fix applied: session/API-key enforcement added to /api/admin/*, access logging enabled.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    nginx 1.24.0",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.02 seconds",
            ],
          }),
        }),
        cmd({
          id: "gobuster",
          tool: "gobuster",
          requires: [IP],
          help: "gobuster dir -u http://<ip> -w common.txt   — brute-force hidden directories",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "webenum",
            tone: "success",
            setsFlags: ["found_admin_api"],
            output: [
              "===============================================================",
              "Gobuster v3.6",
              "===============================================================",
              `[+] Url: http://${IP}`,
              "[+] Method: GET",
              "===============================================================",
              "/api/adopt            (Status: 200) [Size: 3140]  — public listings, expected",
              "/api/admin            (Status: 200) [Size: 812]   <- no login wall, unexpected",
              "===============================================================",
              "",
              "note: a 200 on /api/admin with zero auth headers sent is not normal — most admin",
              "routes at least bounce you to a 401.",
            ],
          }),
        }),
        cmd({
          id: "curl-admin-api",
          tool: "curl",
          requires: ["/api/admin"],
          help: "curl http://<ip>/api/admin",
          requiresFlags: ["found_admin_api"],
          run: () => ({
            completesObjective: "access",
            tone: "success",
            setsFlags: ["confirmed_no_auth"],
            note: "Cascade Hollow Animal Rescue — /api/admin has zero authentication, exposes donor records",
            output: [
              "HTTP/1.1 200 OK",
              "Content-Type: application/json",
              "",
              '{"donors":[{"name":"redacted","amount":250},{"name":"redacted","amount":75}],',
              ' "listings":[{"id":41,"pet":"Biscuit","status":"pending"}],',
              ' "actions":["export_donors","delete_listing","edit_listing"]}',
              "",
              "[!] no Authorization header sent. no session cookie. no API key. the API just... answered.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — add auth to the admin API",
          requiresObjectives: ["access"],
          deniedOutput: ["confirm what the unauthenticated endpoint actually exposes before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] added session/API-key enforcement to every /api/admin/* route",
              "[+] enabled access logging on the admin API",
              "[+] notified the shelter's volunteer webmaster with a writeup",
              "",
              "CASCADE HOLLOW ANIMAL RESCUE: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
