import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "203.0.113.45";
const DOMAIN = "talusridgeoutfitters.com";

export const easyLevel6: ChainDef = {
  id: "easy-6",
  difficulty: "easy",
  order: 6,
  points: 70,
  title: "Public Record",
  codename: "OPERATION PUBLIC RECORD",
  summary: "No login page. No exploit. Every real engagement starts before you ever touch the target directly — build a profile of Talus Ridge Outfitters using only what's already public.",
  briefing: [
    "Talus Ridge Outfitters — an outdoor gear retailer out of Bozeman, Montana — just signed on for a",
    "penetration test. The engagement hasn't reached the technical phase yet.",
    "",
    "Before anyone runs a single scan against a live system, build a target profile the way a real",
    "assessment starts: domain and hosting details, subdomain footprint, technology stack, key",
    "personnel, and anything public documents leak without meaning to. Everything here is passive —",
    "nothing in this mission touches Talus Ridge's systems directly. That's the point.",
  ],
  debrief: [
    "Everything gathered here came from public sources — domain registration data, DNS records, a job",
    "listing, a conference bio, and a PDF's own metadata. Nothing here scanned a port or logged in",
    "anywhere. This is what real engagements actually start with, and it routinely takes longer than",
    "the technical phase that follows it: understanding the target well enough that the technical work",
    "is aimed at something real, instead of guessing.",
    "",
    "TALUS RIDGE OUTFITTERS: PROFILE COMPLETE.",
  ],
  nodes: [
    {
      id: "talus-ridge",
      org: "Talus Ridge Outfitters",
      city: "Bozeman",
      state: "MT",
      coords: { x: 17.8, y: 13.2 },
      ip: IP,
      tagline: "Outdoor gear retailer — pre-engagement OSINT",
      briefing: [
        `TARGET: ${DOMAIN}`,
        "This is a passive reconnaissance engagement. No scans against live infrastructure, no login",
        "attempts — everything you need is already public.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon-domain", label: "Identify domain registration and hosting details", tactic: "Reconnaissance" },
        {
          id: "recon-subdomains",
          label: "Enumerate the organization's subdomain footprint",
          tactic: "Reconnaissance",
          requires: ["recon-domain"],
        },
        {
          id: "recon-stack",
          label: "Identify the technology stack from a public job listing",
          tactic: "Reconnaissance",
          requires: ["recon-subdomains"],
        },
        {
          id: "recon-people",
          label: "Identify key personnel through public sources",
          tactic: "Reconnaissance",
          requires: ["recon-stack"],
        },
        {
          id: "recon-metadata",
          label: "Extract metadata from a publicly available document",
          tactic: "Reconnaissance",
          requires: ["recon-people"],
        },
        { id: "compile", label: "Compile every finding into a target profile", tactic: "Collection", requires: ["recon-metadata"] },
      ],
      hints: [
        `Start with \`whois ${DOMAIN}\` — registration records often name a hosting provider or registrant org even when privacy protection hides the individual.`,
        `Passive DNS enumeration next: \`dig +short ${DOMAIN}\` gives you the main record, but subdomains need their own lookups — try common ones like \`dig +short dev.${DOMAIN}\` and \`dig +short vpn.${DOMAIN}\`.`,
        `Check the careers page for what they're actually hiring for — \`curl http://${DOMAIN}/careers\` — job listings routinely name the exact stack a company runs, in far more detail than any marketing page would.`,
        "For personnel, public conference talks and company blog posts often name real employees with their actual role — try `search \"talus ridge outfitters\" engineer conference`.",
        `Public-facing PDFs carry metadata most people never think to check — \`exiftool ${DOMAIN}/downloads/catalog.pdf\` reads the file's embedded author and software fields directly.`,
        "Once you have all five, pull it together with `compile profile`.",
      ],
      debrief: [],
      commands: [
        cmd({
          id: "whois",
          tool: "whois",
          requires: [DOMAIN],
          help: `whois ${DOMAIN}`,
          run: () => ({
            completesObjective: "recon-domain",
            tone: "success",
            setsFlags: ["have_whois"],
            note: "Talus Ridge Outfitters — registrant privacy-protected, but hosted at Cascade Peak Hosting (autonomous system AS-CASCADEPEAK), registered 2014",
            output: [
              "Domain Name: TALUSRIDGEOUTFITTERS.COM",
              "Registrant Organization: REDACTED FOR PRIVACY",
              "Registrar: NameShield Registrar Inc.",
              "Creation Date: 2014-03-11",
              "Name Server: NS1.CASCADEPEAKHOSTING.NET",
              "Name Server: NS2.CASCADEPEAKHOSTING.NET",
              "",
              "[!] registrant identity is privacy-protected — a dead end on its own, but the nameservers",
              "    confirm who actually hosts this: Cascade Peak Hosting.",
            ],
          }),
        }),
        cmd({
          id: "dig-root",
          tool: "dig",
          requires: [DOMAIN],
          forbids: ["dev.", "vpn.", "staging.", "mail."],
          help: `dig +short ${DOMAIN}`,
          requiresFlags: ["have_whois"],
          run: () => ({
            tone: "output",
            setsFlags: ["dug_root"],
            output: [IP, "", "note: this is just the main site's A record — worth checking whether other subdomains resolve too."],
          }),
        }),
        cmd({
          id: "dig-dev",
          tool: "dig",
          requires: ["dev."],
          help: `dig +short dev.${DOMAIN}`,
          requiresFlags: ["dug_root"],
          run: () => ({
            tone: "output",
            setsFlags: ["found_dev"],
            output: ["203.0.113.46", "", "[+] dev.talusridgeoutfitters.com resolves — a staging/development environment is exposed."],
          }),
        }),
        cmd({
          id: "dig-vpn",
          tool: "dig",
          requires: ["vpn."],
          help: `dig +short vpn.${DOMAIN}`,
          requiresFlags: ["found_dev"],
          run: () => ({
            completesObjective: "recon-subdomains",
            tone: "success",
            setsFlags: ["found_vpn"],
            note: "Talus Ridge Outfitters — subdomains: dev.talusridgeoutfitters.com (203.0.113.46), vpn.talusridgeoutfitters.com (203.0.113.47, Cisco AnyConnect portal)",
            output: [
              "203.0.113.47",
              "",
              "[+] vpn.talusridgeoutfitters.com resolves too — a remote-access portal, likely their actual",
              "    perimeter for employee access. Two real subdomains found from guessing common names alone.",
            ],
          }),
        }),
        cmd({
          id: "curl-careers",
          tool: "curl",
          requires: ["careers"],
          help: `curl http://${DOMAIN}/careers`,
          requiresFlags: ["found_vpn"],
          run: () => ({
            completesObjective: "recon-stack",
            tone: "success",
            setsFlags: ["have_stack"],
            note: "Talus Ridge Outfitters — job listing reveals stack: Node.js/Express API, PostgreSQL, React frontend, hosted on Cascade Peak's managed Kubernetes",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "Senior Backend Engineer — Talus Ridge Outfitters",
              "You'll work across our Node.js/Express API and PostgreSQL data layer, alongside a React",
              "frontend team. Experience with Kubernetes a plus — we run our whole stack on Cascade Peak's",
              "managed K8s offering.",
              "",
              "[+] a single job posting named the exact backend framework, database, frontend framework,",
              "    and hosting platform — more precise than any port scan banner would give for free.",
            ],
          }),
        }),
        {
          id: "search-people",
          tool: "search",
          match: (input) => {
            const n = input.trim().toLowerCase();
            return n.startsWith("search") && n.includes("talus ridge") && n.includes("engineer") && n.includes("conference");
          },
          help: 'search "talus ridge outfitters" engineer conference',
          requiresFlags: ["have_stack"],
          deniedOutput: ["broaden or narrow the search terms — try the org name plus a role and context."],
          run: () => ({
            completesObjective: "recon-people",
            tone: "success",
            setsFlags: ["have_people"],
            note: "Talus Ridge Outfitters — Dana Ferreira (Lead Backend Engineer) named in a 2024 regional dev conference talk on migrating monoliths to Kubernetes",
            output: [
              'search results for "talus ridge outfitters" engineer conference:',
              "",
              '  "Breaking Up the Monolith" — Rocky Mountain DevOps Summit 2024',
              "  speaker: Dana Ferreira, Lead Backend Engineer, Talus Ridge Outfitters",
              '  abstract: "...our migration off a single Node.js monolith onto Kubernetes, and the Postgres',
              '  sharding work that came with it..."',
              "",
              "[+] a named employee, their actual title, and independent confirmation of the stack the job",
              "    posting described — all from a public conference archive.",
            ],
          }),
        },
        cmd({
          id: "exiftool-catalog",
          tool: "exiftool",
          requires: ["catalog.pdf"],
          help: `exiftool ${DOMAIN}/downloads/catalog.pdf`,
          requiresFlags: ["have_people"],
          run: () => ({
            completesObjective: "recon-metadata",
            tone: "success",
            setsFlags: ["have_metadata"],
            note: "Talus Ridge Outfitters — catalog PDF metadata: Author 'd.ferreira', Producer 'Adobe InDesign 18.2 (Windows)', internal path C:\\Users\\d.ferreira\\Documents\\catalog-2025\\",
            output: [
              "File: catalog.pdf",
              "Author: d.ferreira",
              "Producer: Adobe InDesign 18.2 (Windows)",
              "Creator Tool: Adobe InDesign",
              'Original File Path (embedded): C:\\Users\\d.ferreira\\Documents\\catalog-2025\\final-print.indd',
              "",
              "[+] the author field matches the naming convention (first initial + last name) for the",
              "    employee already identified — and confirms this org runs Windows workstations for at",
              "    least its design/marketing staff.",
            ],
          }),
        }),
        {
          id: "compile",
          tool: "compile",
          match: match.startsWith("compile profile", "compile", "profile"),
          help: "compile profile",
          requiresObjectives: ["recon-metadata"],
          deniedOutput: ["gather all five findings before compiling the profile — domain, subdomains, stack, personnel, and metadata."],
          run: () => ({
            completesObjective: "compile",
            tone: "success",
            output: [
              "=== TARGET PROFILE — Talus Ridge Outfitters ===",
              "Hosting: Cascade Peak Hosting (registrant privacy-protected)",
              "Subdomains: dev.talusridgeoutfitters.com, vpn.talusridgeoutfitters.com",
              "Stack: Node.js/Express, PostgreSQL, React, Kubernetes (Cascade Peak managed)",
              "Personnel: Dana Ferreira — Lead Backend Engineer (d.ferreira naming convention, Windows workstation)",
              "Notable exposure: a staging subdomain and a VPN portal are both internet-facing",
              "",
              "[+] a full profile built without a single packet sent to talusridgeoutfitters.com's live",
              "    infrastructure — everything above came from registries, DNS, a job board, a conference",
              "    archive, and a PDF nobody scrubbed before publishing.",
              "",
              "TALUS RIDGE OUTFITTERS: PROFILE COMPLETE",
            ],
          }),
        },
      ],
    },
  ],
};
