import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "203.0.113.93";

export const easyLevel3: ChainDef = {
  id: "easy-3",
  difficulty: "easy",
  order: 3,
  points: 50,
  title: "Open Book",
  codename: "OPERATION OPEN BOOK",
  summary: "The vulnerability isn't hidden behind a login. It's sitting in a file the browser already downloaded.",
  briefing: [
    "Fernbrook Little League runs schedules, rosters, and parent text alerts through a site a league",
    "parent built one off-season using a page-builder template and a notification-service plugin.",
    "",
    "It works. Parents get their game-time texts. Nobody thought twice about where the plugin's API",
    "key actually lives — which, it turns out, is sitting in plain text in a file the browser",
    "downloads for every single visitor.",
    "",
    "Find it the way anyone with a browser's dev tools could.",
  ],
  debrief: [
    "root cause: a third-party notification service's live API key was hardcoded directly into",
    "client-side JavaScript — CWE-798 (use of hard-coded credentials). Anything shipped to a browser",
    "should be treated as public, permanently, the moment it ships — there's no such thing as a",
    "'hidden' file in a client-side bundle.",
    "",
    "fix applied: the key was pulled out of the bundle, notification calls moved behind a small",
    "server-side proxy, and the key rotated with the vendor.",
  ],
  nodes: [
    {
      id: "fernbrook",
      org: "Fernbrook Little League",
      city: "Fernbrook",
      state: "IN",
      coords: { x: 58, y: 33 },
      ip: IP,
      tagline: "Youth sports league — schedules, rosters, parent notifications",
      briefing: [
        "TARGET: Fernbrook Little League site",
        `IP: ${IP}`,
        "KNOWN: static-ish site, page-builder template, third-party SMS notification plugin",
        "",
        "Check what the site actually ships to a browser — not just what's on the page.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"League treasurer asked a favor after reading about a phishing text scam hitting",
        "   another league's parents. Long shot, but check their notification setup.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "webenum", label: "Locate the site's JavaScript bundle", tactic: "Discovery", requires: ["recon"] },
        {
          id: "secrets",
          label: "Recover the hardcoded notification-service API key from the bundle",
          tactic: "Credential Access",
          requires: ["webenum"],
        },
        { id: "secure", label: "Remove the key from client code and rotate it", tactic: "Remediation", requires: ["secrets"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "Fetch the homepage — `curl http://<ip>`. See what script files it actually loads into the browser.",
        "Anything shipped to a browser is public, full stop, even if nobody who wrote it thought of it that way. Fetch the JS bundle directly: `curl http://<ip>/assets/app.js`.",
        "That's a live API key sitting in code anyone can view. Get it out of there and rotate it: `secure system`.",
      ],
      debrief: [
        "root cause: a live SMS-provider API key was hardcoded in a public JS file, not an env var or",
        "server-side secret.",
        "fix applied: key removed from the client bundle, calls proxied server-side, key rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "80/tcp  open  http    nginx 1.24.0 (redirects to 443)",
              "443/tcp open  https   nginx 1.24.0",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.71 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["app.js"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "webenum",
            tone: "success",
            setsFlags: ["found_bundle"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Fernbrook Little League</title>",
              "<body>",
              "  <div id=\"app\"></div>",
              '  <script src="/assets/app.js"></script>',
              "</body>",
              "",
              "tip: check what's actually shipped to the browser — anything in a JS file is public,",
              "whether anyone meant it to be or not.",
            ],
          }),
        }),
        cmd({
          id: "curl-bundle",
          tool: "curl",
          requires: ["app.js"],
          help: "curl http://<ip>/assets/app.js",
          requiresFlags: ["found_bundle"],
          run: () => ({
            completesObjective: "secrets",
            tone: "success",
            setsFlags: ["have_notify_key"],
            note: "Fernbrook Little League notification key — tr_live_9c2f2b1a (text-relay), hardcoded in public JS",
            output: [
              "HTTP/1.1 200 OK",
              "Content-Type: application/javascript",
              "",
              'const NOTIFY_CONFIG = { provider: "text-relay", apiKey: "tr_live_9c2f2b1a", from: "+1-555-0134" };',
              "function sendGameAlert(msg){ return fetch(`https://api.text-relay.example/send?key=${NOTIFY_CONFIG.apiKey}`,",
              "  { method: \"POST\", body: msg }); }",
              "",
              "[+] live text-relay API key recovered from client-side code: tr_live_9c2f2b1a",
              "[!] anyone with this key can send SMS as Fernbrook Little League, or read message logs.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — remove the key from client code and rotate it",
          requiresObjectives: ["secrets"],
          deniedOutput: ["you need to actually pull the key out of the bundle before you can file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] removed the hardcoded key from app.js",
              "[+] moved notification sends behind a small server-side proxy endpoint",
              "[+] rotated the key with text-relay",
              "",
              "FERNBROOK LITTLE LEAGUE: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
