import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "198.51.100.20";

export const mediumLevel3: ChainDef = {
  id: "medium-3",
  difficulty: "medium",
  order: 3,
  points: 80,
  title: "Not Equal",
  codename: "OPERATION NOT EQUAL",
  summary: "A login check that compares against a query operator instead of a password isn't really checking a password at all.",
  briefing: [
    "Comstock Veterinary Group runs a client portal across its six clinics — appointment history,",
    "vaccine records, billing. It's backed by a document database instead of a traditional SQL one,",
    "and the login form was built by someone who'd only ever tested it with normal input.",
    "",
    "No leaked credentials here. No default password. Just a query that was never taught to expect",
    "anything but a plain string.",
  ],
  debrief: [
    "root cause: the login handler passed the client-supplied password field directly into a MongoDB",
    "query without type-checking it first. Sending an object instead of a string let an attacker replace",
    "the password check with a query operator that's always true — NoSQL injection (CWE-943).",
    "",
    "COMSTOCK VETERINARY GROUP: SECURED.",
  ],
  nodes: [
    {
      id: "comstockvet",
      org: "Comstock Veterinary Group",
      city: "Comstock",
      state: "MI",
      coords: { x: 58, y: 22 },
      ip: IP,
      tagline: "Regional veterinary clinic chain — client portal",
      briefing: [
        "TARGET: Comstock Veterinary Group client portal",
        `IP: ${IP}`,
        "KNOWN: document-database-backed login form, no known credentials.",
        "",
        "Find out whether the login handler actually validates the shape of what it's given.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Devs mentioned it's 'a Mongo thing' when asked about the backend. Worth remembering that",
        "   query operators are still just JSON if nothing strips them out.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Identify the client portal's document-database-backed login", tactic: "Discovery", requires: ["recon"] },
        { id: "bypass", label: "Bypass authentication with a NoSQL operator injection", tactic: "Initial Access", requires: ["identify"] },
        { id: "loot", label: "Read another client's records through the bypassed session", tactic: "Collection", requires: ["bypass"] },
        { id: "secure", label: "Enforce strict type-checking on login input", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then check the web root; the response headers or page footer usually name the stack.",
        "The login form posts a JSON body with 'user' and 'pass' fields. Try `login {\"user\":\"admin\",\"pass\":{\"$ne\":null}}` — a database that never validates the shape of 'pass' will happily compare it against a query operator instead of a string.",
        "You're in as admin without ever knowing a real password. Look for a client-record export or listing endpoint.",
        "You've proven a type-confusion bug bypasses auth entirely. Push the fix.",
      ],
      debrief: [
        "root cause: the login handler passed req.body.pass directly into the MongoDB query filter with no",
        "type check, so an object like {\"$ne\": null} was interpreted as a query operator instead of a value —",
        "matching any document regardless of the real password.",
        "fix applied: login input strictly type-checked to reject non-string password fields, all sessions revoked.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    Node.js Express (Comstock Veterinary client portal)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.65 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["login", "client-records"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_login"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Comstock Veterinary Group — Client Portal</title>",
              "<!-- backend: mongoose 7.x -->",
              '<form action="/api/login" method="POST">',
              "",
              "tip: a document-database backend that never validates input shape is worth testing with",
              "something that isn't a string.",
            ],
          }),
        }),
        {
          id: "login",
          tool: "login",
          match: (input) => /^login\s+\{.*\$ne.*\}\s*$/i.test(input.trim()) && /admin/i.test(input),
          help: 'login {"user":"admin","pass":{"$ne":null}}   — NoSQL operator injection',
          requiresFlags: ["found_login"],
          deniedOutput: ["authentication failed — that's a real string comparison. try feeding it something that isn't a string."],
          run: () => ({
            completesObjective: "bypass",
            tone: "success",
            promptAfter: "admin@comstock-portal:~$",
            note: "Comstock Veterinary Group — auth bypassed via {\"pass\":{\"$ne\":null}} NoSQL operator injection",
            output: [
              "[+] authenticated as admin — no real password ever checked",
              "",
              "=== Client Portal — Admin View ===",
              "clinics | client-records | billing | settings",
              "",
              "ALERT: password field was never type-checked before hitting the query.",
            ],
          }),
        },
        cmd({
          id: "loot-records",
          tool: "curl",
          requires: ["client-records"],
          help: "curl http://<ip>/api/client-records/export      — export all client records",
          requiresObjectives: ["bypass"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Comstock Veterinary Group — full client-records export accessible with no further authorization check",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"client":"[redacted]","pet":"[redacted]","balance_due":"$142.00"}, ...]',
              "",
              "[!] the bypassed admin session has unrestricted read access to every clinic's client data.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — enforce strict type-checking on login input",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the actual data exposure before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] login handler now rejects any non-string password field before it reaches the query",
              "[+] revoked all active sessions",
              "[+] documented as NoSQL injection / improper input validation (CWE-943)",
              "",
              "COMSTOCK VETERINARY GROUP: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
