import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP1 = "198.51.100.90";
const IP2 = "198.51.100.95";

export const mediumLevel10: ChainDef = {
  id: "medium-10",
  difficulty: "medium",
  order: 10,
  points: 270,
  title: "Cross-Tenant",
  codename: "OPERATION CROSS-TENANT",
  summary: "A build pipeline's secrets, a cloud role trusted too broadly, and a partner's tenant on the other end of it. Everything you've learned this tier, chained once more.",
  briefing: [
    "Meridian Cloud Exchange runs a vendor marketplace platform that a number of smaller companies",
    "build integrations on top of — including Cobalt Harbor Port Authority, whose container-tracking",
    "system lives in a partner cloud tenant reachable through Meridian's shared infrastructure.",
    "",
    "You start with nothing but a public-facing CI status page. Everything else — the shell, the",
    "stolen cloud role, the cross-tenant reach into a second organization — has to be built one step",
    "at a time, the same way every chain this tier has been.",
  ],
  debrief: [
    "This is the medium tier in miniature, stacked twice: an exposed CI debug endpoint became command",
    "execution (CWE-94), which reached an instance role with a dangerously broad trust policy allowing",
    "cross-account assumption (excessive IAM trust, CWE-284), which handed over live credentials for a",
    "second organization's cloud tenant entirely. Nobody attacked Cobalt Harbor directly — their exposure",
    "came entirely from a partner they'd never audited.",
    "",
    "Two organizations, one cloud marketplace, one chain. That's the shape almost every real",
    "supply-chain compromise takes.",
  ],
  nodes: [
    {
      id: "meridian",
      org: "Meridian Cloud Exchange",
      city: "Meridian",
      state: "TX",
      coords: { x: 44.6, y: 44.4 },
      ip: IP1,
      tagline: "Cloud vendor marketplace platform",
      briefing: [
        "TARGET: Meridian Cloud Exchange CI/build platform",
        `IP: ${IP1}`,
        "KNOWN: public marketplace site with an undocumented CI status dashboard.",
        "",
        "Find out what that dashboard exposes, and what it's connected to.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"CI dashboard was stood up for internal debugging and never fully locked down before it",
        "   went public with the rest of the marketplace site.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Discover the exposed CI status dashboard and its webhook debug endpoint", tactic: "Discovery", requires: ["recon"] },
        { id: "foothold", label: "Abuse the webhook debug endpoint for command execution in the build container", tactic: "Execution", requires: ["identify"] },
        {
          id: "privesc",
          label: "Discover and assume an overly broad cross-account IAM role from the build container",
          tactic: "Privilege Escalation",
          requires: ["foothold"],
        },
        { id: "secure", label: "Lock down the webhook endpoint and tighten the IAM trust policy", tactic: "Remediation", requires: ["privesc"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. An extra port beyond the usual web ports is worth a look.",
        "The CI dashboard on the undocumented port mentions a webhook 'replay' debug feature — worth finding out exactly what it lets you replay, and with what input.",
        "The replay endpoint takes a `cmd=` parameter and runs it inside the build container — try something simple like `id` first.",
        "From inside the build container, check what cloud role it's running as, and what that role is allowed to assume — an `aws sts assume-role` into a partner account is worth trying if the trust policy looks broad.",
      ],
      debrief: [
        "root cause: an internal CI debug dashboard was exposed publicly, and its webhook 'replay' feature",
        "executed a client-supplied command inside the build container with no validation — from there, the",
        "build container's instance role had a trust policy broad enough to assume a role in a partner",
        "organization's cloud account.",
        "fix applied: CI dashboard removed from public routing, webhook replay endpoint requires signed,",
        "pre-registered payloads only, cross-account trust policy scoped down to specific approved roles.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP1],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "80/tcp   open  http    nginx 1.24.0 (marketplace site)",
              "8000/tcp open  http    Node.js Express (undocumented — CI status?)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.30 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-ci",
          tool: "curl",
          requires: ["8000"],
          forbids: ["webhook", "replay"],
          help: "curl http://<ip>:8000/      — probe the undocumented CI dashboard",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_ci"],
            output: [
              '{"service":"meridian-ci-status","builds":"12 today","debug":"/webhook/replay?cmd="}',
              "",
              "note: a 'replay' debug endpoint that takes a cmd= parameter has no business being reachable",
              "from outside the build network.",
            ],
          }),
        }),
        cmd({
          id: "webhook-replay",
          tool: "curl",
          requires: ["webhook/replay", "cmd="],
          forbids: ["sts", "assume-role"],
          help: 'curl "http://<ip>:8000/webhook/replay?cmd=id"',
          requiresFlags: ["found_ci"],
          run: () => ({
            completesObjective: "foothold",
            tone: "success",
            setsFlags: ["have_shell"],
            output: [
              "200 OK",
              '{"cmd":"id","result":"uid=1000(svc_ci) gid=1000(svc_ci) groups=1000(svc_ci)"}',
              "",
              "[+] the replay endpoint runs arbitrary commands inside the build container with zero validation.",
            ],
          }),
        }),
        cmd({
          id: "sts-assume",
          tool: "curl",
          requires: ["sts", "assume-role", "cobaltharbor"],
          help: 'curl "http://<ip>:8000/webhook/replay?cmd=aws sts assume-role --role-arn arn:aws:iam::cobaltharbor:role/partner-integration --role-session-name pivot"',
          requiresFlags: ["have_shell"],
          run: () => ({
            completesObjective: "privesc",
            tone: "success",
            setsFlags: ["have_temp_creds"],
            note: "Meridian Cloud Exchange build role assumed cross-account into Cobalt Harbor's partner-integration role — overly broad trust policy",
            output: [
              "{",
              '  "AccessKeyId": "ASIA_COBALT_DEMO",',
              '  "SecretAccessKey": "d3mo/secretvalue/notreal",',
              '  "SessionToken": "IQoJb3JpZ2luX2VjEP...",',
              '  "AssumedRoleArn": "arn:aws:iam::cobaltharbor:role/partner-integration"',
              "}",
              "",
              "[!] the build container's role was trusted, unscoped, to assume a role in Cobalt Harbor's",
              "    own cloud account. this box just handed you a second organization's credentials.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — lock down the webhook and the trust policy",
          requiresObjectives: ["privesc"],
          deniedOutput: ["confirm how far the stolen role actually reaches before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] removed the CI debug dashboard from public routing",
              "[+] webhook replay now requires signed, pre-registered payloads only",
              "[+] scoped the cross-account trust policy down to specific approved roles",
              "",
              "MERIDIAN CLOUD EXCHANGE: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "cobaltharbor",
      org: "Cobalt Harbor Port Authority",
      city: "Cobalt Harbor",
      state: "LA",
      coords: { x: 59.6, y: 45.8 },
      ip: IP2,
      tagline: "Regional port authority — container-tracking platform",
      briefing: [
        "TARGET: Cobalt Harbor Port Authority container-tracking API",
        `IP: ${IP2}`,
        "YOU HAVE: cross-account temporary credentials, assumed via Meridian's build role.",
        "",
        "Find out exactly what those credentials reach inside Cobalt Harbor's own tenant.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Cobalt Harbor never audited what Meridian's marketplace integration was actually trusted",
        "   to do inside their own account.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "access", label: "Authenticate to the container-tracking API using the assumed-role credentials", tactic: "Initial Access", requires: ["recon"] },
        { id: "loot", label: "Recover cargo manifest data proving full tenant compromise", tactic: "Collection", requires: ["access"] },
        { id: "secure", label: "Revoke the cross-account role and audit all partner integrations", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "The assumed-role credentials from Meridian are valid here — authenticate to the container-tracking API with them, using the session token as well as the access key.",
        "Once authenticated, look for a manifests or cargo-data endpoint — that's the real proof of impact.",
      ],
      debrief: [
        "root cause: Cobalt Harbor granted Meridian's marketplace integration role broad read access across",
        "the container-tracking tenant, and never revisited what that trust actually allowed once the",
        "integration was live.",
        "fix applied: cross-account role access revoked and re-scoped to the minimum required, full audit",
        "of every partner integration's granted permissions.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP2],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (container-tracking API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.95 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-access",
          tool: "curl",
          requires: ["x-amz-security-token", "containers"],
          help: 'curl -H "Authorization: AWS4-HMAC-SHA256 ..." -H "X-Amz-Security-Token: <session-token>" https://<ip>/api/containers',
          requiresObjectives: ["recon"],
          requiresFlags: ["have_temp_creds"],
          deniedOutput: ["401 Unauthorized — you need valid cross-account credentials for this tenant."],
          run: () => ({
            completesObjective: "access",
            tone: "success",
            setsFlags: ["api_access"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"tenant":"cobaltharbor","access":"authenticated","containers_tracked":4821}',
              "",
              "[+] the stolen cross-account role authenticated cleanly against Cobalt Harbor's own API.",
            ],
          }),
        }),
        cmd({
          id: "loot-manifests",
          tool: "curl",
          requires: ["manifests"],
          help: "curl -H \"X-Amz-Security-Token: <session-token>\" https://<ip>/api/manifests",
          requiresFlags: ["api_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Cobalt Harbor Port Authority — full cargo manifest data recovered via cross-tenant IAM trust abuse",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"manifest_id":"CH-88213","vessel":"[redacted]","cargo":"[redacted]"}, ...]',
              "",
              "[!] full read access to Cobalt Harbor's cargo manifests, from credentials that were never",
              "    meant to leave Meridian's own build pipeline.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — revoke the cross-account role and audit partner access",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the full extent of the cross-tenant exposure before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] revoked Meridian's cross-account role access into Cobalt Harbor's tenant",
              "[+] re-scoped the integration to the minimum required permissions",
              "[+] launched a full audit of every partner integration's granted access",
              "",
              "COBALT HARBOR PORT AUTHORITY: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
