import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "198.51.100.25";
const SESSION_COOKIE = "fw_session=b7e2a9c14f";

export const mediumLevel4: ChainDef = {
  id: "medium-4",
  difficulty: "medium",
  order: 4,
  points: 90,
  title: "Reflected Trust",
  codename: "OPERATION REFLECTED TRUST",
  summary: "An API that reflects whatever Origin header you send, credentials included, trusts nothing — it just answers.",
  briefing: [
    "Fernbrook Wealth Advisors is a small independent investment advisory in eastern Pennsylvania.",
    "Their client portal API was built to support a couple of internal tools on different subdomains,",
    "so someone configured cross-origin access to 'just work' rather than be listed explicitly.",
    "",
    "A member of the assessment team already has a live client session cookie, provided for this test.",
    "Find out exactly how far a stolen cookie reaches when the API trusts any origin that asks.",
  ],
  debrief: [
    "root cause: the client-account API reflected the request's Origin header back as",
    "Access-Control-Allow-Origin while also setting Access-Control-Allow-Credentials: true — meaning any",
    "website, from any origin, could read a logged-in client's authenticated data in their own browser",
    "(CWE-942, overly permissive CORS policy).",
    "",
    "FERNBROOK WEALTH ADVISORS: SECURED.",
  ],
  nodes: [
    {
      id: "fernbrook",
      org: "Fernbrook Wealth Advisors",
      city: "Millrose",
      state: "PA",
      coords: { x: 76, y: 25 },
      ip: IP,
      tagline: "Independent investment advisory — client portal API",
      briefing: [
        "TARGET: Fernbrook Wealth Advisors client portal API",
        `IP: ${IP}`,
        `YOU HAVE: a live client session cookie for this test — ${SESSION_COOKIE}`,
        "",
        "Confirm whether the API's cross-origin policy actually restricts who can read that session's data.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Portal API needs to talk to a couple of internal dashboards on other subdomains. Someone",
        "   made CORS 'just work' rather than list them out.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Discover the client-account API and its CORS headers", tactic: "Discovery", requires: ["recon"] },
        { id: "exploit", label: "Confirm the API trusts an arbitrary Origin with credentials included", tactic: "Initial Access", requires: ["identify"] },
        { id: "loot", label: "Read the client's full portfolio data via the misconfigured origin", tactic: "Collection", requires: ["exploit"] },
        { id: "secure", label: "Restrict Access-Control-Allow-Origin to a fixed allowlist", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then hit the API root and look closely at the response headers, not just the body.",
        "Send a request with an Origin header that has nothing to do with Fernbrook — something like https://evil.example — and see whether Access-Control-Allow-Origin echoes it back.",
        `Add the provided session cookie to that same request — ${SESSION_COOKIE} — and check whether Allow-Credentials is set alongside the reflected origin.`,
        "If both are true, an arbitrary origin can read authenticated responses. Confirm it by pulling the client's actual account data with that combination.",
      ],
      debrief: [
        "root cause: /api/account reflected any Origin header back as Access-Control-Allow-Origin and set",
        "Access-Control-Allow-Credentials: true, so a malicious page on any domain could make a credentialed",
        "request in a logged-in client's browser and read the response.",
        "fix applied: CORS policy pinned to a fixed allowlist of known internal subdomains, wildcard-style",
        "origin reflection removed.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (client portal API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.80 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["origin"],
          help: "curl -i https://<ip>/api/account      — check the response headers",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_api"],
            output: [
              "HTTP/1.1 401 Unauthorized",
              "Access-Control-Allow-Origin: null",
              "",
              "no session cookie yet — but note the CORS header is present at all. worth testing what it",
              "does when you actually send an Origin.",
            ],
          }),
        }),
        cmd({
          id: "cors-poc",
          tool: "curl",
          requires: ["origin:", "evil", "cookie:", "fw_session"],
          forbids: ["portfolio"],
          help: `curl -i -H "Origin: https://evil.example" -H "Cookie: ${SESSION_COOKIE}" https://<ip>/api/account`,
          requiresFlags: ["found_api"],
          run: () => ({
            completesObjective: "exploit",
            tone: "success",
            setsFlags: ["cors_confirmed"],
            output: [
              "HTTP/1.1 200 OK",
              "Access-Control-Allow-Origin: https://evil.example",
              "Access-Control-Allow-Credentials: true",
              "",
              '{"client":"authenticated","portfolio_summary":"available"}',
              "",
              "[!] an origin with nothing to do with Fernbrook was reflected back and trusted with credentials.",
            ],
          }),
        }),
        cmd({
          id: "loot-portfolio",
          tool: "curl",
          requires: ["origin:", "evil", "portfolio"],
          help: `curl -H "Origin: https://evil.example" -H "Cookie: ${SESSION_COOKIE}" https://<ip>/api/portfolio`,
          requiresFlags: ["cors_confirmed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Fernbrook Wealth Advisors — full client portfolio data readable cross-origin due to reflected CORS + Allow-Credentials: true",
            output: [
              "HTTP/1.1 200 OK",
              "Access-Control-Allow-Origin: https://evil.example",
              "Access-Control-Allow-Credentials: true",
              "",
              '{"holdings":[{"symbol":"[redacted]","value":"[redacted]"}],"account_balance":"[redacted]"}',
              "",
              "[!] a page hosted on any domain could have read this in the client's own browser.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — restrict CORS to a fixed allowlist",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the full data exposure before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] pinned Access-Control-Allow-Origin to a fixed list of known internal subdomains",
              "[+] removed origin-reflection logic from the CORS middleware",
              "[+] documented as overly permissive CORS policy (CWE-942)",
              "",
              "FERNBROOK WEALTH ADVISORS: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
