import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP1 = "198.51.100.22";
const IP2 = "198.51.100.87";

export const mediumLevel9: ChainDef = {
  id: "medium-9",
  difficulty: "medium",
  order: 9,
  points: 200,
  title: "Shared Infrastructure",
  codename: "OPERATION LOOSE MANIFEST",
  summary: "Two companies. One cloud provider between them. Trust doesn't stop at the tenant boundary.",
  briefing: [
    "NorthPeak Cloud Hosting rents VPS and object storage to a couple hundred small and mid-size",
    "businesses across the Midwest. One of them is Swift Transit Logistics — regional freight",
    "dispatch, the kind of company that quietly keeps trucks full of everyone else's inventory moving.",
    "",
    "You've got a free-tier NorthPeak account. That's the entire foothold you start with.",
    "",
    "Multi-tenant platforms are only as secure as their weakest authorization check. Find where",
    "NorthPeak trusts a client-supplied ID instead of verifying who's asking, ride that into Swift",
    "Transit's systems, and find out how far a single leaked API key actually reaches.",
  ],
  debrief: [
    "This is the shape of almost every real supply-chain compromise: nobody attacked Swift Transit",
    "directly. Their hosting provider had a broken object-level authorization check (IDOR, OWASP API1),",
    "and that was enough to walk straight into a downstream customer's infrastructure — then a debug",
    "endpoint that trusted a client-supplied header handed over command execution.",
    "",
    "Two organizations, two unrelated-looking bugs, one chain. That's the job.",
  ],
  nodes: [
    {
      id: "northpeak",
      org: "NorthPeak Cloud Hosting",
      city: "Rapid Falls",
      state: "SD",
      coords: { x: 43.1, y: 16.1 },
      ip: IP1,
      tagline: "Regional VPS + object storage provider",
      briefing: [
        "TARGET: NorthPeak Cloud Hosting customer API",
        `IP: ${IP1}`,
        "YOU HAVE: a free-trial tenant account (tenant id 1044) — legitimate, low-privilege access.",
        "",
        "Find out whether tenant isolation on their storage API actually holds.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Free trial account is real, not staged. Use it like a normal low-priv customer would.",
        "   Internal ticket NP-482 mentioned an auth gap on the bucket API — never confirmed closed.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "api-enum", label: "Discover the tenant storage API", tactic: "Discovery", requires: ["recon"] },
        { id: "idor", label: "Access another tenant's bucket via broken object-level auth", tactic: "Initial Access", requires: ["api-enum"] },
        { id: "leak", label: "Recover Swift Transit's leaked dispatch API key", tactic: "Credential Access", requires: ["idor"] },
        { id: "secure", label: "Report and patch the authorization gap", tactic: "Remediation", requires: ["leak"] },
      ],
      hints: [
        "Start with recon on the target IP — `nmap -sV <ip>`. Note anything past the usual 80/443.",
        "Port 8080 is an undocumented API. Hit the root of it with curl and see what it tells you about itself.",
        "You have a real tenant id (1044) from your trial account. Try pulling your own bucket listing at /api/v1/buckets/1044 to learn the URL pattern.",
        "If the API trusts whatever tenant id you send instead of checking who's authenticated, it doesn't matter whose id it is. Try searching the tenant directory for 'swift' to get another tenant's real id, then request that id's bucket.",
        "Once you're looking at Swift Transit's bucket, read what's actually in it — one of those files is a config file, and config files leak credentials constantly.",
        "You've proven the impact. Now fix it: `secure system`.",
      ],
      debrief: [
        "root cause: /api/v1/buckets/<tenant_id> checked that a request was authenticated, but never checked",
        "that the authenticated tenant matched the requested tenant_id — a textbook IDOR / broken object-level",
        "authorization bug (OWASP API1:2023).",
        "fix applied: bucket API now validates tenant_id against the session, ticket NP-482 closed.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP1],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "22/tcp   open  ssh     OpenSSH 8.9p1",
              "80/tcp   open  http    nginx 1.24.0 (redirects to 443)",
              "443/tcp  open  https   nginx 1.24.0",
              "8080/tcp open  http    Node.js Express (undocumented — customer-api?)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 5.62 seconds",
            ],
          }),
        }),
        cmd({
          id: "api-root",
          tool: "curl",
          requires: ["8080"],
          forbids: ["buckets", "tenants"],
          help: "curl http://<ip>:8080/     — probe the undocumented API",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "api-enum",
            tone: "success",
            setsFlags: ["api_known"],
            output: [
              '{"service":"northpeak-customer-api","version":"2.3.0","status":"ok"}',
              "",
              "X-Powered-By: Express",
              "note: no OpenAPI spec published, but /api/v1/buckets/<tenant_id> responds to GET",
            ],
          }),
        }),
        cmd({
          id: "own-bucket",
          tool: "curl",
          requires: ["buckets/1044"],
          help: "curl http://<ip>:8080/api/v1/buckets/1044    — list your own tenant bucket",
          requiresFlags: ["api_known"],
          run: () => ({
            tone: "output",
            output: [
              '{"tenant_id":1044,"files":["welcome.txt","getting-started.pdf"]}',
              "",
              "your own bucket, as expected. notice the endpoint took the tenant id straight",
              "from the URL — worth checking whether it actually verifies you own that id.",
            ],
          }),
        }),
        cmd({
          id: "tenant-search",
          tool: "curl",
          requires: ["tenants", "swift"],
          help: "curl http://<ip>:8080/api/v1/tenants?q=swift   — search the tenant directory",
          requiresFlags: ["api_known"],
          run: () => ({
            tone: "success",
            setsFlags: ["tenant_id_known"],
            note: "NorthPeak tenant_id for Swift Transit Logistics: 1091",
            output: [
              '[{"tenant_id":1091,"name":"Swift Transit Logistics","plan":"business"}]',
              "",
              "[+] tenant id for Swift Transit Logistics: 1091",
            ],
          }),
        }),
        cmd({
          id: "idor-pull",
          tool: "curl",
          requires: ["buckets/1091"],
          forbids: ["dispatch-config"],
          help: "curl http://<ip>:8080/api/v1/buckets/1091    — request another tenant's bucket",
          requiresFlags: ["tenant_id_known"],
          deniedOutput: ["you don't have a tenant id to try yet — search the tenant directory first."],
          run: () => ({
            completesObjective: "idor",
            tone: "success",
            setsFlags: ["found_swift_bucket"],
            output: [
              '{"tenant_id":1091,"files":["swift-transit-dispatch-config.json","shipping_manifest_template.csv"]}',
              "",
              "[!] no ownership check performed — the API returned another customer's private bucket.",
            ],
          }),
        }),
        cmd({
          id: "cat-config",
          tool: "curl",
          requires: ["dispatch-config"],
          help: "curl http://<ip>:8080/api/v1/buckets/1091/swift-transit-dispatch-config.json",
          requiresFlags: ["found_swift_bucket"],
          run: () => ({
            completesObjective: "leak",
            tone: "success",
            setsFlags: ["have_swift_api_key"],
            note: `Swift Transit dispatch API key — st_live_8f2b9c1e4a77d0 (https://${IP2}/api/dispatch)`,
            output: [
              "{",
              `  "dispatch_base_url": "https://${IP2}/api/dispatch",`,
              '  "api_key": "st_live_8f2b9c1e4a77d0",',
              '  "environment": "production"',
              "}",
              "",
              "[+] production API key for Swift Transit Logistics recovered.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — patch the authorization gap",
          requiresObjectives: ["leak"],
          deniedOutput: ["you should understand the full impact before filing the fix — keep digging."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] added tenant_id ownership check to /api/v1/buckets/<tenant_id>",
              "[+] filed incident report referencing ticket NP-482",
              "[+] notified Swift Transit Logistics that their API key was exposed",
              "",
              "NORTHPEAK CLOUD HOSTING: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "swifttransit",
      org: "Swift Transit Logistics",
      city: "Danville Junction",
      state: "IL",
      coords: { x: 61.5, y: 25.7 },
      ip: IP2,
      tagline: "Regional freight dispatch & last-mile routing",
      briefing: [
        "TARGET: Swift Transit Logistics dispatch platform",
        `IP: ${IP2}`,
        "YOU HAVE: a production API key, leaked from NorthPeak's storage bucket.",
        "",
        "Find out what that key actually reaches, and how far.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Key came out of a supposedly-internal config file. See if it's scoped down,",
        "   or if whoever wrote DispatchTrack Pro trusted it with more than they should have.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate to the dispatch API with the leaked key", tactic: "Initial Access", requires: ["recon"] },
        { id: "foothold", label: "Abuse the debug endpoint for command execution", tactic: "Execution", requires: ["auth"] },
        { id: "loot", label: "Enumerate downstream integrations reachable from this host", tactic: "Collection", requires: ["foothold"] },
        { id: "secure", label: "Disable the debug endpoint and rotate the key", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first, as always — `nmap -sV <ip>`.",
        "Authenticate with the leaked key as a Bearer token against the dispatch API's status endpoint.",
        "Try hitting the debug endpoint plainly first — read the error carefully, it tells you exactly what header it wants.",
        "DispatchTrack Pro's debug endpoint trusts a client-supplied 'X-Internal-Debug: true' header instead of actually checking the network origin. Set it, and pass a `cmd=` parameter.",
        "You've got command execution. Look at what this host is configured to talk to — `cat /etc/dispatch/integrations.yaml` is a good next move.",
        "You've proven a leaked key plus a trust-the-header bug equals command execution. Remediate it.",
      ],
      debrief: [
        "root cause: /api/dispatch/debug/exec trusted a client-supplied 'X-Internal-Debug' header as proof of",
        "internal network origin instead of checking the actual source, effectively giving any authenticated",
        "API caller command execution.",
        "fix applied: debug endpoint removed from production build, API key rotated, integration credentials rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP2],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "22/tcp  open  ssh     OpenSSH 8.9p1",
              "443/tcp open  https   nginx 1.24.0 (reverse proxy -> dispatch API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.10 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth-status",
          tool: "curl",
          requires: ["authorization", "dispatch/status"],
          forbids: ["debug"],
          help: 'curl -H "Authorization: Bearer <key>" https://<ip>/api/dispatch/status',
          requiresObjectives: ["recon"],
          requiresFlags: ["have_swift_api_key"],
          deniedOutput: ["401 Unauthorized — you don't have a valid API key for this service."],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed"],
            output: [
              '{"status":"ok","service":"DispatchTrack Pro","version":"4.1.2"}',
              "",
              "response header: X-Debug-Available: true",
              "note: 'debug available' isn't something a production API should ever advertise.",
            ],
          }),
        }),
        cmd({
          id: "loot-integrations",
          tool: "curl",
          requires: ["integrations.yaml"],
          help: 'curl ... "https://<ip>/api/dispatch/debug/exec?cmd=cat /etc/dispatch/integrations.yaml"',
          requiresFlags: ["shell_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["saw_integrations"],
            note: "Swift Transit dispatch host also integrates with: metrolink-transit-authority, continental-grid-interconnect",
            output: [
              "integrations:",
              "  - name: metrolink-transit-authority",
              "    role: signal-priority-feed",
              "    endpoint: internal-only",
              "  - name: continental-grid-interconnect",
              "    role: fleet-charging-load-report",
              "    endpoint: internal-only",
              "",
              "[!] this dispatch host has standing integrations into transit signaling and grid load",
              "    reporting systems. a compromise here doesn't stay contained to shipping.",
            ],
          }),
        }),
        cmd({
          id: "debug-probe",
          tool: "curl",
          requires: ["debug/exec"],
          forbids: ["integrations.yaml"],
          help: 'curl -H "Authorization: Bearer <key>" https://<ip>/api/dispatch/debug/exec?cmd=whoami',
          requiresObjectives: ["auth"],
          requiresFlags: ["authed"],
          run: (input) => {
            const hasHeader = /x-internal-debug/i.test(input) && /true/i.test(input);
            if (!hasHeader) {
              return {
                tone: "error",
                output: [
                  "403 Forbidden",
                  '{"error":"internal role required","detail":"set X-Internal-Debug: true"}',
                ],
              };
            }
            return {
              completesObjective: "foothold",
              tone: "success",
              setsFlags: ["shell_access"],
              output: [
                "200 OK",
                '{"cmd":"whoami","result":"svc_dispatch"}',
                "",
                "[+] command execution confirmed as svc_dispatch via debug/exec.",
              ],
            };
          },
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — remove the debug endpoint and rotate keys",
          requiresObjectives: ["loot"],
          deniedOutput: ["understand the blast radius before you file the fix — check what this host integrates with."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] removed /api/dispatch/debug/exec from the production build",
              "[+] rotated the leaked Swift Transit API key",
              "[+] rotated downstream integration credentials",
              "[+] escalated the integrations.yaml finding for follow-up review",
              "",
              "SWIFT TRANSIT LOGISTICS: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
