import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.250";
const OUT_OF_SCOPE_IP = "192.0.2.251";

export const ghostLevel5: ChainDef = {
  id: "ghost-5",
  difficulty: "ghost",
  order: 5,
  points: 320,
  title: "Verify Everything",
  codename: "GHOST ASSESSMENT — VERIFY EVERYTHING",
  summary: "A scanner already ran against this target. Five findings. Only one of them is real. And there's a second host on this segment that isn't yours to touch.",
  briefing: [
    `TARGET: Harrowgate Data Systems — ${IP}`,
    "RULES OF ENGAGEMENT: this engagement covers Harrowgate Data Systems only. A second host on the",
    `same network segment, ${OUT_OF_SCOPE_IP} (Bellcross County EMS Dispatch), belongs to a different`,
    "client entirely and is explicitly NOT in scope. Do not scan it, query it, or interact with it in",
    "any way.",
    "",
    "An automated scanner already ran against the in-scope target. Its report is below. Your job is",
    "not to trust it — it's to verify every line of it yourself before you act on any of it.",
    "",
    "SCANNER REPORT (unverified):",
    "  1. CRITICAL — OpenSSH 7.2 (port 22) — CVE-2016-6210, user enumeration via timing",
    "  2. HIGH     — Redis exposed without authentication (port 6379)",
    "  3. MEDIUM   — Reflected XSS on /search?q=",
    "  4. LOW      — Directory listing enabled on /assets/",
    "  5. MEDIUM   — Verbose error output on /api/internal/debug",
  ],
  debrief: [
    "Four of the five scanner findings were false positives: SSH had already been patched to 9.2p1",
    "since the scan ran, Redis correctly requires authentication, the XSS payload came back",
    "HTML-encoded, and /assets/ returns a clean 403. A scanner report is a list of leads, not a list",
    "of vulnerabilities — reproducing every claim yourself, and documenting the ones that don't hold",
    "up, is as much the job as finding the one that does.",
    "",
    "The fifth finding was real: a debug endpoint leaked a fallback admin token and the path to an",
    "internal admin panel with no further authorization check (CWE-209 / CWE-538).",
    "",
    "HARROWGATE DATA SYSTEMS: SECURED.",
  ],
  nodes: [
    {
      id: "harrowgate",
      org: "Harrowgate Data Systems",
      city: "Harrowgate",
      state: "PA",
      coords: { x: 74, y: 20 },
      ip: IP,
      tagline: "Data processing vendor",
      briefing: [`IP: ${IP}`, "Scanner report provided in the engagement briefing. Verify every line of it yourself."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        {
          id: "triage",
          label: "Independently verify the scanner report and identify the one real finding",
          tactic: "Discovery",
          requires: ["recon"],
        },
        { id: "exploit", label: "Exploit the real finding to reach the internal admin panel", tactic: "Initial Access", requires: ["triage"] },
        { id: "loot", label: "Recover the internal data export", tactic: "Collection", requires: ["exploit"] },
        {
          id: "secure",
          label: "Document every finding — confirmed and debunked — and remediate the real one",
          tactic: "Remediation",
          requires: ["loot"],
        },
      ],
      hints: [
        "a scanner report is a lead, not a finding — verify every claim yourself before you act on any of it.",
        "one of these five is real. reproduce it, don't assume it. the other four deserve exactly as much verification before you rule them out.",
        "you'll notice a second host during recon. it belongs to a different client and isn't part of this engagement — leave it alone, including scanning it.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          forbids: ["-p22"],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "22/tcp   open  ssh     OpenSSH 9.2p1",
              "80/tcp   open  http    nginx 1.24.0",
              "6379/tcp open  redis   Redis 7.0.11",
              "",
              "note: another host is visible on this segment but was not included in this scan's target",
              "list — it is not part of this engagement.",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.60 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "verify-ssh",
          tool: "nmap",
          requires: [IP, "-p22"],
          help: "nmap -sV -p22 <ip>",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            setsFlags: ["check1"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "22/tcp open  ssh     OpenSSH 9.2p1",
              "",
              "[finding 1: FALSE POSITIVE] the scanner's banner-version check is stale — this host has",
              "already been patched well past CVE-2016-6210.",
            ],
          }),
        }),
        strictCmd({
          id: "verify-redis",
          tool: "redis-cli",
          requires: ["6379", "ping"],
          help: "redis-cli -h <ip> -p 6379 ping",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            setsFlags: ["check2"],
            output: [
              "(error) NOAUTH Authentication required.",
              "",
              "[finding 2: FALSE POSITIVE] Redis correctly requires authentication.",
            ],
          }),
        }),
        strictCmd({
          id: "verify-xss",
          tool: "curl",
          requires: ["search?q=", "<script"],
          help: 'curl "http://<ip>/search?q=<script>alert(1)</script>"',
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            setsFlags: ["check3"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "&lt;script&gt;alert(1)&lt;/script&gt; found 0 results",
              "",
              "[finding 3: FALSE POSITIVE] the payload came back HTML-encoded — this endpoint is not",
              "vulnerable to reflected XSS.",
            ],
          }),
        }),
        strictCmd({
          id: "verify-listing",
          tool: "curl",
          requires: ["assets"],
          forbids: ["debug", "search", "internal"],
          help: "curl http://<ip>/assets/",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            setsFlags: ["check4"],
            output: [
              "HTTP/1.1 403 Forbidden",
              "",
              "[finding 4: FALSE POSITIVE] directory listing is disabled — this path returns a clean 403.",
            ],
          }),
        }),
        strictCmd({
          id: "verify-debug",
          tool: "curl",
          requires: ["api/internal/debug"],
          help: "curl http://<ip>/api/internal/debug",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "triage",
            tone: "success",
            setsFlags: ["check5", "have_token"],
            note: "Harrowgate Data Systems — fallback admin token leaked via verbose debug output: HG_FALLBACK_9f2c1a, path /internal-admin",
            output: [
              "HTTP/1.1 500 Internal Server Error",
              "",
              "Traceback (most recent call last):",
              '  File "app.py", line 214, in debug_handler',
              "    raise DebugException(fallback_token=ADMIN_TOKEN, admin_path='/internal-admin')",
              "app.errors.DebugException: fallback_token=HG_FALLBACK_9f2c1a, admin_path=/internal-admin",
              "",
              "[finding 5: CONFIRMED] verbose error output leaked a live fallback admin token and the",
              "internal admin panel's path (CWE-209 / CWE-538).",
            ],
          }),
        }),
        strictCmd({
          id: "exploit",
          tool: "curl",
          requires: ["internal-admin", "HG_FALLBACK_9f2c1a"],
          forbids: ["/export"],
          help: 'curl -H "Authorization: Bearer HG_FALLBACK_9f2c1a" http://<ip>/internal-admin',
          requiresFlags: ["have_token"],
          run: () => ({
            completesObjective: "exploit",
            tone: "success",
            setsFlags: ["admin_access"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "=== Harrowgate Data Systems — Internal Admin ===",
              "client records | processing jobs | export",
              "",
              "[+] the fallback token was never meant to leave a crash log, but nothing checked that it did.",
            ],
          }),
        }),
        strictCmd({
          id: "loot",
          tool: "curl",
          requires: ["internal-admin/export"],
          help: 'curl -H "Authorization: Bearer HG_FALLBACK_9f2c1a" http://<ip>/internal-admin/export',
          requiresFlags: ["admin_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Harrowgate Data Systems — full client data export recovered via leaked fallback admin token",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"client":"[redacted]","records":18420,"last_export":"2025-11-02"}]',
              "",
              "[!] full export access, from a token that only ever should have existed in a crash log.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          requiresFlags: ["check1", "check2", "check3", "check4"],
          deniedOutput: [
            "you haven't independently verified every finding in the scanner report yet — confirm or",
            "debunk all five before you file this.",
          ],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] filed the fallback debug token exposure as the confirmed finding — removed the",
              "    fallback token from error output, disabled verbose tracebacks in production",
              "[+] documented all four other scanner findings as verified false positives, with",
              "    reproduction notes, so nobody re-flags them next quarter",
              "[+] rotated the leaked token and added an authorization check to /internal-admin/*",
              "",
              "HARROWGATE DATA SYSTEMS: SECURED",
            ],
          }),
        },
      ],
      outOfScope: {
        match: (input) => input.includes(OUT_OF_SCOPE_IP),
        response: [
          "[!] SCOPE VIOLATION",
          `${OUT_OF_SCOPE_IP} (Bellcross County EMS Dispatch) is not part of this engagement — it`,
          "belongs to a different client, reachable on this segment purely by coincidence.",
          "",
          "Touching it at all — scanning it, querying it, anything — is outside the rules of",
          "engagement you agreed to. In a real assessment this is the kind of action that ends",
          "contracts and licenses, not a game rule.",
        ],
      },
    },
  ],
};
