import type { ChainDef } from "../../types";
import { match, strictCmd } from "../../engine";

const IP = "192.0.2.210";

export const ghostLevel1: ChainDef = {
  id: "ghost-1",
  difficulty: "ghost",
  order: 1,
  points: 150,
  title: "Signal and Noise",
  codename: "GHOST ASSESSMENT — SIGNAL AND NOISE",
  summary: "Six open services. One of them is the way in. No note is going to tell you which.",
  briefing: [
    `TARGET: Fenwick Analytics Group — ${IP}`,
    "OBJECTIVE: find the actual way in, and prove it with a real credential exposure.",
    "",
    "This box has more open services than most. Some are exactly what they claim to be.",
    "Some aren't worth your time. Figuring out which is which is the whole job — nobody is going",
    "to flag the interesting one for you.",
  ],
  debrief: [
    "root cause: an internal tooling service was deployed without any authorization check on its",
    "user-management endpoint, exposed on the same segment as several unrelated, correctly-secured",
    "services — broken access control (OWASP A01:2021).",
    "",
    "The rest of what was open — Redis, Grafana, SonarQube — was fine. That's real recon: most of",
    "what you find isn't the way in, and nothing marks the one thing that is.",
  ],
  nodes: [
    {
      id: "fenwick",
      org: "Fenwick Analytics Group",
      city: "Fenwick",
      state: "CT",
      coords: { x: 88.4, y: 20 },
      ip: IP,
      randomizableSecrets: ["Fw!analytics-int9"],
      tagline: "Marketing analytics platform",
      briefing: [`IP: ${IP}`, "No further information provided."],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate every open service on the target", tactic: "Reconnaissance" },
        {
          id: "identify",
          label: "Identify the one service missing an authorization check",
          tactic: "Discovery",
          requires: ["recon"],
        },
        { id: "creds", label: "Recover an exposed credential through it", tactic: "Credential Access", requires: ["identify"] },
        { id: "secure", label: "Lock down the endpoint and rotate the credential", tactic: "Remediation", requires: ["creds"] },
      ],
      hints: [
        "not every open port is interesting, and not every interesting-looking service is actually open to you. read what nmap told you about each one — don't just check them in order.",
        "services that label themselves clearly are usually exactly what they claim to be. the one worth a second look is often the one nobody bothered to name.",
      ],
      debrief: [],
      commands: [
        strictCmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "22/tcp   open  ssh     OpenSSH 8.9p1",
              "80/tcp   open  http    nginx 1.24.0",
              "3000/tcp open  http    Node.js Express",
              "6379/tcp open  redis   Redis 7.0.11",
              "8081/tcp open  http    Grafana 10.1.2",
              "9000/tcp open  http    SonarQube 9.9 LTS",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 5.14 seconds",
            ],
          }),
        }),
        strictCmd({
          id: "curl-80",
          tool: "curl",
          requires: ["http://" + IP],
          forbids: ["3000", "6379", "8081", "9000"],
          help: "curl http://<ip>",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Fenwick Analytics — Reach Further</title>",
              "<p>Marketing attribution dashboards for regional retailers.</p>",
            ],
          }),
        }),
        strictCmd({
          id: "redis-ping",
          tool: "redis-cli",
          requires: ["6379", "ping"],
          help: "redis-cli -h <ip> -p 6379 ping",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "error",
            output: ["(error) NOAUTH Authentication required."],
          }),
        }),
        strictCmd({
          id: "curl-8081",
          tool: "curl",
          requires: ["8081"],
          help: "curl http://<ip>:8081",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"service":"grafana","version":"10.1.2","auth":"required","anonymous_access":false}',
            ],
          }),
        }),
        strictCmd({
          id: "curl-9000",
          tool: "curl",
          requires: ["9000"],
          help: "curl http://<ip>:9000",
          requiresFlags: ["scanned"],
          run: () => ({
            tone: "output",
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>SonarQube</title>",
              '<form action="/sessions/new"><input name="login"><input name="password" type="password"></form>',
            ],
          }),
        }),
        strictCmd({
          id: "curl-3000-root",
          tool: "curl",
          requires: ["3000"],
          forbids: ["/api/internal/users"],
          help: "curl http://<ip>:3000",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_internal"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>internal-tools</title>",
              '<nav><a href="/api/internal/users">users</a> <a href="/api/internal/status">status</a></nav>',
            ],
          }),
        }),
        strictCmd({
          id: "curl-3000-users",
          tool: "curl",
          requires: ["3000", "/api/internal/users"],
          help: "curl http://<ip>:3000/<path>",
          requiresFlags: ["found_internal"],
          deniedOutput: ["you haven't found a reason to look here yet."],
          run: () => ({
            completesObjective: "creds",
            tone: "success",
            note: "Fenwick Analytics — internal-tools admin account: admin : Fw!analytics-int9 (reused from the SonarQube deploy config)",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"user":"admin","role":"internal-admin","note":"reused password, see deploy config: Fw!analytics-int9"}]',
              "",
              "[!] no session, no auth header, no cookie — this endpoint never checked who was asking.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["creds"],
          deniedOutput: ["confirm the actual exposure before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] added an authorization check to every /api/internal/* route",
              "[+] rotated the reused admin credential",
              "[+] documented as broken access control (OWASP A01:2021)",
              "",
              "FENWICK ANALYTICS GROUP: SECURED",
            ],
          }),
        },
      ],
    },
  ],
};
