import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";
import { jitteredCoords } from "../../../state-coords";

const IP_BELLWETHER = "203.0.113.150";
const IP_RECEIVABLES = "203.0.113.151";
const LEAKED_PASS = "Autumn2019!";

export const campaignLevel1: ChainDef = {
  id: "campaign-1",
  difficulty: "campaign",
  order: 1,
  points: 220,
  title: "First Contact",
  codename: "CAMPAIGN — EPISODE 1: FIRST CONTACT",
  summary: "One reused password, handed to you by someone you'll never meet. Everything after that is your own footwork.",
  briefing: [
    "unbank's tip: a Bellwether Outreach Solutions employee account, password reused from an old breach —",
    `agent14 : ${LEAKED_PASS}`,
    "",
    "Bellwether is a contracted collections call center. Nobody outside unbank has confirmed who they",
    "actually work for. Get in, and find out.",
  ],
  debrief: [
    "One reused employee password got you a low-privilege call-center account. A directory endpoint",
    "that trusted any valid session with any employee id — no ownership check at all — turned that",
    "account into every other employee's record, including the one that named who actually owns",
    "Bellwether: a shell called Concord Receivables Partners, filed at the exact same tax address.",
    "",
    "That address is the whole finding. Two companies pretending to be strangers, sharing one office.",
  ],
  nodes: [
    {
      id: "bellwether",
      org: "Bellwether Outreach Solutions",
      city: "Danforth",
      state: "IL",
      coords: jitteredCoords("IL", "campaign-1:bellwether"),
      ip: IP_BELLWETHER,
      tagline: "Contracted collections call center",
      briefing: [
        `TARGET: Bellwether Outreach Solutions employee portal — ${IP_BELLWETHER}`,
        `YOU HAVE: agent14 : ${LEAKED_PASS} (leaked, reused — courtesy of an unbank sympathizer inside)`,
        "",
        "Find out who this account can actually see, not just what it was issued for.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate the employee portal login", tactic: "Discovery", requires: ["recon"] },
        { id: "access", label: "Authenticate with the leaked, reused credential", tactic: "Initial Access", requires: ["identify"] },
        {
          id: "idor",
          label: "Enumerate other employee records by incrementing the id parameter",
          tactic: "Discovery",
          requires: ["access"],
        },
        { id: "loot", label: "Recover the directory export naming Bellwether's actual owner", tactic: "Collection", requires: ["idor"] },
        { id: "secure", label: "Rotate the credential and add an ownership check to the record endpoint", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. Then find the employee portal login itself.",
        `Log in with what unbank gave you: \`login agent14 ${LEAKED_PASS}\`.`,
        "Your own record loads from /api/employees/<id>. Nothing says that id has to be yours — try a neighboring number.",
        "Once you can read arbitrary employee records, look for one that isn't a call-center agent — an office manager or admin record tends to say more about who actually signs the lease.",
      ],
      debrief: [
        "root cause: /api/employees/<id> checked that a session was valid, never that the id belonged to",
        "that session — broken object-level authorization (OWASP A01:2021), same shape as the reused-",
        "password problem one layer up.",
        "fix applied: the leaked credential was rotated, an ownership check was added to the endpoint.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_BELLWETHER],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "80/tcp open  http    nginx 1.24.0 (Bellwether employee portal)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.80 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP_BELLWETHER],
          forbids: ["login", "employees"],
          help: "curl http://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_login"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Bellwether Outreach Solutions — Agent Portal</title>",
              '<form action="/login" method="POST"><input name="user"><input name="pass"></form>',
            ],
          }),
        }),
        {
          id: "login",
          tool: "login",
          match: (input) => /^login\s+\S+\s+\S+$/.test(input.trim().toLowerCase()),
          help: `login agent14 ${LEAKED_PASS}`,
          requiresFlags: ["found_login"],
          deniedOutput: ["/login is up but you haven't got anything to try against it yet."],
          run: (input) => {
            const parts = input.trim().split(/\s+/);
            const user = parts[1]?.toLowerCase().replace(/^["']|["']$/g, "");
            const pass = parts[2]?.replace(/^["']|["']$/g, "");
            if (user === "agent14" && pass === LEAKED_PASS) {
              return {
                completesObjective: "access",
                tone: "success",
                promptAfter: "agent14@bellwether-portal:~$",
                setsFlags: ["have_session"],
                note: `Bellwether Outreach Solutions — agent14 : ${LEAKED_PASS} (reused password, leaked)`,
                output: [
                  "[+] authenticated as agent14",
                  "",
                  "=== Bellwether Agent Portal ===",
                  "my-cases | scripts | employees/142",
                  "",
                  "note: your own record loads at /api/employees/142.",
                ],
              };
            }
            return { tone: "error", output: [`[-] authentication failed for user '${parts[1] ?? ""}'`] };
          },
        },
        cmd({
          id: "own-record",
          tool: "curl",
          requires: ["employees/142"],
          help: "curl http://<ip>/api/employees/142",
          requiresFlags: ["have_session"],
          run: () => ({
            tone: "output",
            output: [
              '{"id":142,"name":"agent14","role":"collections agent"}',
              "",
              "that's your own record — nothing stops you from asking for a different id.",
            ],
          }),
        }),
        cmd({
          id: "idor",
          tool: "curl",
          requires: ["employees/1"],
          forbids: ["employees/142", "export"],
          help: "curl http://<ip>/api/employees/1",
          requiresFlags: ["have_session"],
          run: () => ({
            completesObjective: "idor",
            tone: "success",
            setsFlags: ["idor_confirmed"],
            output: [
              '{"id":1,"name":"r.oyelaran","role":"office manager"}',
              "",
              "[!] no ownership check at all — agent14's session just read employee id 1's record.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "curl",
          requires: ["employees/1/export"],
          help: "curl http://<ip>/api/employees/1/export",
          requiresFlags: ["idor_confirmed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["have_directory"],
            note: `Bellwether Outreach Solutions — directory export names owning entity: Concord Receivables Partners, shared tax address, reachable at ${IP_RECEIVABLES}`,
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"filing_entity":"Concord Receivables Partners","tax_address":"1140 Delmore Plaza Ste 4",',
              ` "shared_sso_domain":"${IP_RECEIVABLES}"}`,
              "",
              "[+] Bellwether isn't its own company. it's a call center wearing Concord Receivables",
              "    Partners' name for the day.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what the directory export actually names before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] rotated agent14's credential",
              "[+] added an ownership check to /api/employees/<id>",
              "[+] documented as broken object-level authorization (OWASP A01:2021)",
              "",
              "BELLWETHER OUTREACH SOLUTIONS: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "receivables",
      org: "Concord Receivables Partners",
      city: "Danforth",
      state: "MO",
      coords: jitteredCoords("MO", "campaign-1:receivables"),
      ip: IP_RECEIVABLES,
      tagline: "Debt-purchasing shell — shared SSO domain with its own contracted call centers",
      briefing: [
        `TARGET: Concord Receivables Partners — shared SSO domain — ${IP_RECEIVABLES}`,
        "YOU HAVE: the shared SSO domain named in Bellwether's directory export.",
        "",
        "Find out how many other 'independent' companies actually federate through this same login.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate the tenant/companies directory behind the shared SSO", tactic: "Discovery", requires: ["recon"] },
        {
          id: "enum",
          label: "Enumerate every tenant federated through this SSO domain",
          tactic: "Discovery",
          requires: ["identify"],
        },
        { id: "loot", label: "Recover the ownership document naming Concord Financial Group", tactic: "Collection", requires: ["enum"] },
        { id: "secure", label: "Restrict the tenant directory to authenticated staff only", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. This one doesn't need a login at all; look for what's public before you assume you need credentials.",
        "A shared SSO domain usually has a tenant-discovery endpoint so a login page knows which company logo to show. Try `/api/tenants`.",
        "Once you have the tenant list, one of those tenant records tends to carry more than a name — look for one with a document or filing attached.",
      ],
      debrief: [
        "root cause: the SSO domain's tenant-discovery endpoint listed every federated company, unauthenticated,",
        "including one internal tenant record that linked directly to Concord Financial Group's own",
        "shell-ownership filing — information exposure (CWE-200) that was never meant to be public, on an",
        "endpoint nobody thought to lock because 'it's just for showing the right logo.'",
        "",
        "CONCORD RECEIVABLES PARTNERS: SECURED.",
        "",
        "unbank now has a name: Concord Financial Group. Confirmed, at least 40 shells deep.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_RECEIVABLES],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT   STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (shared SSO / identity domain)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.90 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP_RECEIVABLES],
          forbids: ["tenants"],
          help: "curl https://<ip>      — fetch the web root",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_sso"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              "<title>Sign in</title>",
              "<script src=\"/assets/tenant-picker.js\"></script>",
              "",
              "note: tenant-picker.js calls /api/tenants to decide which company logo to show before login.",
            ],
          }),
        }),
        cmd({
          id: "enum-tenants",
          tool: "curl",
          requires: ["api/tenants"],
          forbids: ["tenants/4"],
          help: "curl https://<ip>/api/tenants",
          requiresFlags: ["found_sso"],
          run: () => ({
            completesObjective: "enum",
            tone: "success",
            setsFlags: ["have_tenants"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"id":1,"name":"Bellwether Outreach Solutions"},{"id":2,"name":"Concord Receivables Partners"},',
              ' {"id":3,"name":"Ashcroft Managed IT"},{"id":4,"name":"internal-holding"},',
              ' ...(37 more)]',
              "",
              "[!] this endpoint requires no authentication at all, and it lists every company federated",
              "    through this login — 41 of them, including one that isn't a debt shop at all.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "curl",
          requires: ["tenants/4"],
          help: "curl https://<ip>/api/tenants/4",
          requiresFlags: ["have_tenants"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Concord Receivables Partners SSO domain — tenant 'internal-holding' filing: parent entity is Concord Financial Group, 41 subsidiaries on record",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"id":4,"name":"internal-holding","filing":{"parent":"Concord Financial Group",',
              ' "subsidiary_count":41,"doc":"cfg-ownership-2024.pdf"}}',
              "",
              "[+] the parent's real name, on the record, behind an endpoint that was only ever meant to",
              "    pick a logo.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what the tenant directory actually exposes before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            setsFlags: ["ep1_complete"],
            output: [
              "[+] restricted /api/tenants to authenticated staff sessions only",
              "[+] removed the internal-holding tenant record from any client-reachable path",
              "[+] documented as unauthenticated information exposure (CWE-200)",
              "",
              "CONCORD RECEIVABLES PARTNERS: SECURED",
              "",
              "=== EPISODE 1 COMPLETE ===",
            ],
          }),
        },
      ],
    },
  ],
};
