import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";
import { jitteredCoords } from "../../../state-coords";

const IP_PALERMO = "203.0.113.154";
const IP_DRIFTWOOD = "203.0.113.155";
const IP_CLOUDSVC = "203.0.113.156";
const IP_LEDGER = "203.0.113.157";

export const campaignLevel3: ChainDef = {
  id: "campaign-3",
  difficulty: "campaign",
  order: 3,
  points: 480,
  title: "Shadow Estate",
  codename: "CAMPAIGN — EPISODE 3: SHADOW ESTATE",
  summary: "Four organizations, one trust graph. Follow every seam, not just the tidy one.",
  briefing: [
    "The correll-data-svc role from Correll Data Systems is trusted well past its own subsidiary — a",
    "cross-account assumption reaches straight into a SaaS analytics vendor, which reaches into",
    "another, which reaches into the cloud account holding company underneath a chunk of Concord's",
    "subsidiary stack.",
    "",
    "This one is deliberately messy. Four organizations, chained entirely through IAM trust policies",
    "nobody scoped down after the integration that needed them was long over. Follow every trust",
    "relationship you find, not just the first one.",
  ],
  debrief: [
    "Four organizations, one shared trust graph, zero of it audited end to end by anyone at Concord.",
    "Each hop was individually reasonable — a vendor integration here, a shared analytics pipeline",
    "there — and each one was scoped broader than the specific thing it was built for, because nobody",
    "ever had to prove it needed to be narrower.",
    "",
    "By the end of this chain you had read access to more of Concord's cloud estate than their own",
    "security team could likely enumerate from the inside. And a name: the nightly reconciliation job",
    "every subsidiary in the network settles against.",
  ],
  nodes: [
    {
      id: "palermo",
      org: "Palermo Analytics Cloud",
      city: "Wardell",
      state: "CO",
      coords: jitteredCoords("CO", "campaign-3:palermo"),
      ip: IP_PALERMO,
      tagline: "Marketing/collections analytics SaaS vendor",
      briefing: [
        `TARGET: Palermo Analytics Cloud — ${IP_PALERMO}`,
        "YOU HAVE: the correll-data-svc IAM role name, recovered from Correll Data Systems' own",
        "instance metadata.",
        "",
        "Find out whether that role's trust actually stops at Correll's own account.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate Palermo's cloud API gateway", tactic: "Discovery", requires: ["recon"] },
        {
          id: "assume",
          label: "Assume a Palermo role using correll-data-svc's broad cross-account trust",
          tactic: "Privilege Escalation",
          requires: ["identify"],
        },
        { id: "loot", label: "Enumerate what the assumed role can itself assume", tactic: "Discovery", requires: ["assume"] },
        { id: "secure", label: "Scope the cross-account trust policy down to the one integration that needs it", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "correll-data-svc's trust policy is broad. Try `aws sts assume-role --role-arn arn:aws:iam::palermo:role/vendor-integration --role-session-name pivot`.",
        "Once you're the assumed role, list what it's itself allowed to assume — `aws iam list-role-policies` or similar reveals the next hop.",
      ],
      debrief: [
        "root cause: Palermo's vendor-integration role trusted correll-data-svc broadly instead of scoping",
        "the trust to the exact actions a data pipeline integration needs — excessive IAM trust (CWE-284).",
        "fix applied: trust policy scoped to the specific actions the integration actually performs.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_PALERMO],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (cloud API gateway)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.90 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP_PALERMO],
          forbids: ["sts"],
          help: "curl https://<ip>      — probe the API gateway",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_api"],
            output: [
              '{"service":"palermo-analytics-gateway","sts_endpoint":"/sts/assume-role"}',
              "",
              "note: this gateway fronts real cloud role assumption, not just a demo API.",
            ],
          }),
        }),
        cmd({
          id: "assume-role",
          tool: "aws",
          requires: ["sts assume-role", "vendor-integration"],
          help: "aws sts assume-role --role-arn arn:aws:iam::palermo:role/vendor-integration --role-session-name pivot",
          requiresFlags: ["found_api"],
          run: () => ({
            completesObjective: "assume",
            tone: "success",
            setsFlags: ["assumed_palermo"],
            note: "Palermo Analytics Cloud — correll-data-svc assumed vendor-integration role, overly broad cross-account trust",
            output: [
              "{",
              '  "AccessKeyId": "ASIA_PALERMO_DEMO",',
              '  "SecretAccessKey": "d3mo/secretvalue/notreal",',
              '  "AssumedRoleArn": "arn:aws:iam::palermo:role/vendor-integration"',
              "}",
              "",
              "[!] correll-data-svc's trust wasn't scoped to the one data pipeline it was built for.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "aws",
          requires: ["iam list-role-policies", "vendor-integration"],
          help: "aws iam list-role-policies --role-name vendor-integration",
          requiresFlags: ["assumed_palermo"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["know_driftwood_role"],
            note: `Palermo — vendor-integration role can itself assume arn:aws:iam::driftwood:role/shared-secrets-reader (Driftwood SaaS Ops, ${IP_DRIFTWOOD})`,
            output: [
              "vendor-integration is permitted to assume:",
              "  arn:aws:iam::driftwood:role/shared-secrets-reader",
              "",
              "[+] the chain keeps going — this role trusts a role in a completely different vendor's account.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm how far this role's trust actually reaches before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] scoped vendor-integration's trust policy to the specific data-pipeline actions it needs",
              "[+] removed its ability to assume roles outside Palermo's own account",
              "[+] documented as excessive IAM trust (CWE-284)",
              "",
              "PALERMO ANALYTICS CLOUD: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "driftwood",
      org: "Driftwood SaaS Ops",
      city: "Cordell",
      state: "WY",
      coords: jitteredCoords("WY", "campaign-3:driftwood"),
      ip: IP_DRIFTWOOD,
      tagline: "Shared secrets/config-management SaaS vendor",
      briefing: [
        `TARGET: Driftwood SaaS Ops — ${IP_DRIFTWOOD}`,
        "YOU HAVE: Palermo's vendor-integration role, trusted to assume Driftwood's shared-secrets-reader role.",
        "",
        "Find out what a 'shared secrets reader' actually reads.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "assume", label: "Assume Driftwood's shared-secrets-reader role", tactic: "Privilege Escalation", requires: ["recon"] },
        { id: "loot", label: "Read the shared secrets store the role has access to", tactic: "Credential Access", requires: ["assume"] },
        { id: "secure", label: "Scope the shared-secrets-reader role down to a single named consumer", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "Assume the role Palermo's chain trusted you into — `aws sts assume-role --role-arn arn:aws:iam::driftwood:role/shared-secrets-reader --role-session-name pivot`.",
        "Once assumed, list what's in the secrets store this role can read — `aws secretsmanager list-secrets` or similar.",
      ],
      debrief: [
        "root cause: Driftwood's shared-secrets-reader role, meant for one specific downstream vendor",
        "integration, was trusted broadly enough that a role assumed three hops upstream could still",
        "reach it — the same excessive-trust pattern as Palermo, one layer deeper.",
        "fix applied: role scoped to a single named consuming role; secrets rotated.",
        "",
        "DRIFTWOOD SAAS OPS: SECURED.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_DRIFTWOOD],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (secrets/config API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.75 seconds",
            ],
          }),
        }),
        cmd({
          id: "assume-role",
          tool: "aws",
          requires: ["sts assume-role", "shared-secrets-reader"],
          help: "aws sts assume-role --role-arn arn:aws:iam::driftwood:role/shared-secrets-reader --role-session-name pivot",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "assume",
            tone: "success",
            setsFlags: ["assumed_driftwood"],
            output: [
              '{"AssumedRoleArn":"arn:aws:iam::driftwood:role/shared-secrets-reader"}',
              "",
              "[+] the trust chain held — Palermo's role assumed Driftwood's without a fresh authentication",
              "    step of any kind.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "aws",
          requires: ["secretsmanager", "list-secrets"],
          help: "aws secretsmanager list-secrets",
          requiresFlags: ["assumed_driftwood"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["have_driftwood_secrets"],
            note: `Driftwood shared secrets store — root credential for Concord Cloud Services master account (${IP_CLOUDSVC}) recovered`,
            output: [
              "SecretList:",
              '  - Name: "concord-cloud-services/master-account-key"',
              '  - Name: "palermo-analytics/pipeline-key"',
              '  - Name: "bellwether-portal/db-key"',
              "",
              "[!] one secrets store, shared across every SaaS vendor in this part of the estate — including",
              "    the credential for the cloud account holding company underneath all of them.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what the shared secrets store actually contains before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] scoped shared-secrets-reader to a single named consuming role",
              "[+] rotated every secret in the shared store",
              "[+] documented as excessive IAM trust compounding a shared-secrets anti-pattern",
              "",
              "DRIFTWOOD SAAS OPS: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "cloudservices",
      org: "Concord Cloud Services",
      city: "Wardell",
      state: "MT",
      coords: jitteredCoords("MT", "campaign-3:cloudservices"),
      ip: IP_CLOUDSVC,
      tagline: "Cloud account holding company underneath the subsidiary stack",
      briefing: [
        `TARGET: Concord Cloud Services — master cloud account — ${IP_CLOUDSVC}`,
        "YOU HAVE: the master account key, recovered from Driftwood's shared secrets store.",
        "",
        "This is the account underneath the accounts. Find out exactly how much of the estate trusts it.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate with the recovered master account key", tactic: "Initial Access", requires: ["recon"] },
        { id: "enum", label: "Enumerate every cross-account trust relationship this account holds", tactic: "Discovery", requires: ["auth"] },
        { id: "loot", label: "Recover the reference to the master nightly reconciliation job", tactic: "Collection", requires: ["enum"] },
        { id: "secure", label: "Begin a full audit of every cross-account trust relationship found", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "Authenticate with the master account key from Driftwood's store, then list every role this account trusts inbound — `aws iam list-account-trust-relationships` (or the equivalent enumeration for this platform).",
        "Somewhere in that list is a reference to a scheduled job, not another vendor — that's worth reading closely.",
      ],
      debrief: [
        "root cause: the master cloud account's own credential lived in a shared secrets store four hops",
        "away with no additional authentication barrier, and the account itself held dozens of inbound",
        "cross-account trust relationships that had never been reviewed as a set — only ever added one",
        "integration at a time, never audited as a whole.",
        "fix applied: master key rotated and moved out of any shared store; full cross-account trust audit opened.",
        "",
        "CONCORD CLOUD SERVICES: SECURED.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_CLOUDSVC],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (cloud account console)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.95 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth",
          tool: "curl",
          requires: ["authorization", "master-account-key"],
          forbids: ["trust-relationships", "scheduled-jobs"],
          help: 'curl -H "Authorization: Bearer <master-account-key>" https://<ip>/api/console',
          requiresFlags: ["scanned"],
          deniedOutput: ["401 Unauthorized — you don't have a credential for this account yet."],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed"],
            output: [
              '{"account":"concord-cloud-services","role":"master","access":"full"}',
              "",
              "[+] the recovered key authenticates cleanly. this is the account everything else answers to.",
            ],
          }),
        }),
        cmd({
          id: "enum-trust",
          tool: "curl",
          requires: ["trust-relationships"],
          help: "curl -H \"Authorization: Bearer <master-account-key>\" https://<ip>/api/trust-relationships",
          requiresFlags: ["authed"],
          run: () => ({
            completesObjective: "enum",
            tone: "success",
            setsFlags: ["sprawl_confirmed"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"trusts":"palermo-analytics"},{"trusts":"driftwood-saas-ops"},{"trusts":"correll-data-systems"},',
              ' {"trusts":"bellwether-outreach"},{"trusts":"ashcroft-managed-it"},{"trusts":"ledger-systems-group"},',
              ' ...(31 more)]',
              "",
              "[!] 37 inbound trust relationships, never reviewed as a set. this is the sprawl — every one of",
              "    those was reasonable in isolation.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "curl",
          requires: ["scheduled-jobs"],
          help: "curl -H \"Authorization: Bearer <master-account-key>\" https://<ip>/api/scheduled-jobs",
          requiresFlags: ["sprawl_confirmed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["know_reconciliation_job"],
            note: `Concord Cloud Services — nightly job "reconciliation-master" runs unattended, settles all 41 subsidiary ledgers, hosted at Ledger Systems Group (${IP_LEDGER})`,
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"job":"reconciliation-master","schedule":"nightly 02:00","scope":"all-subsidiaries",',
              `  "host":"${IP_LEDGER}"}]`,
              "",
              "[+] this is the job fee1000d's been talking about since the first transmission. it's real,",
              "    it's unattended, and it runs against every subsidiary ledger in the network.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm exactly how far this account's trust reaches before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] rotated the master account key and removed it from every shared store",
              "[+] opened a full audit ticket covering all 37 cross-account trust relationships",
              "[+] flagged the reconciliation-master job for a dedicated access review",
              "",
              "CONCORD CLOUD SERVICES: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "ledger",
      org: "Ledger Systems Group",
      city: "Renshaw",
      state: "ID",
      coords: jitteredCoords("ID", "campaign-3:ledger"),
      ip: IP_LEDGER,
      tagline: "Hosts the master nightly reconciliation job",
      briefing: [
        `TARGET: Ledger Systems Group — ${IP_LEDGER}`,
        "YOU HAVE: confirmation from Concord Cloud Services that this host runs the reconciliation-master job.",
        "",
        "Don't touch the job itself yet — that's not this episode's objective, and it isn't safe to",
        "attempt without the access you'll build across the episodes still ahead. Just confirm what's here.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate using Concord Cloud Services' trusted access", tactic: "Initial Access", requires: ["recon"] },
        { id: "loot", label: "Recover the staging credential for Concord's loan-servicing platform", tactic: "Collection", requires: ["auth"] },
        { id: "secure", label: "Restrict which accounts can reach this host at all", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "The master account's trust reaches this host too — authenticate the same way you did at Concord Cloud Services.",
        "Look for a staging or lower environment credential — production loan-servicing systems almost always have one lying around for testing.",
      ],
      debrief: [
        "root cause: Ledger Systems Group trusted any request bearing Concord Cloud Services' master",
        "credential with no additional scoping — the same over-broad trust pattern as every other node",
        "in this episode, one hop from the actual reconciliation job.",
        "fix applied: access restricted to a small, explicitly named set of accounts; staging credential rotated.",
        "",
        "LEDGER SYSTEMS GROUP: SECURED.",
        "",
        "unbank now knows exactly where the reconciliation job lives, and has a way into Concord's",
        "loan-servicing platform itself. Neither one gets touched until the access is earned properly.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_LEDGER],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (reconciliation host)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.05 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth",
          tool: "curl",
          requires: ["authorization", "master-account-key", "api/status"],
          forbids: ["reconciliation-master"],
          help: 'curl -H "Authorization: Bearer <master-account-key>" https://<ip>/api/status',
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed"],
            output: [
              '{"host":"ledger-systems-group","trusts":"concord-cloud-services master","jobs":1}',
              "",
              "[+] the master credential works here too. same trust, same lack of scoping.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "curl",
          requires: ["staging-credentials"],
          help: 'curl -H "Authorization: Bearer <master-account-key>" https://<ip>/api/staging-credentials',
          requiresFlags: ["authed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["have_loanservicing_cred"],
            note: "Ledger Systems Group — staging credential for Concord's loan-servicing platform (Fenmore Loan Servicing) recovered",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"platform":"fenmore-loan-servicing","env":"staging","credential":"fen_stg_7c31be0a94"}',
              "",
              "[+] a staging credential for the actual loan-servicing platform — the system that decides",
              "    what every one of those 41 subsidiaries' debtors actually owes.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what's actually reachable from here before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            setsFlags: ["ep3_complete"],
            output: [
              "[+] restricted this host to a small, explicitly named set of trusted accounts",
              "[+] rotated the exposed loan-servicing staging credential",
              "[+] flagged reconciliation-master for a dedicated access review, separate from the general audit",
              "",
              "LEDGER SYSTEMS GROUP: SECURED",
              "",
              "=== EPISODE 3 COMPLETE ===",
            ],
          }),
        },
      ],
    },
  ],
};
