import type { ChainDef, CommandDef } from "../../types";
import { match, cmd, normalize } from "../../engine";
import { jitteredCoords } from "../../../state-coords";

const IP_BROKER = "203.0.113.163";
const IP_STAGING = "203.0.113.164";
const IP_WATCHDOG = "203.0.113.165";
const IP_PROD = "203.0.113.166";
const PROD_SESSION = "recon_master_sess_e91fa2";

const wipeLedger: CommandDef = {
  id: "wipe-ledger",
  tool: "curl",
  help: "wipe ledger",
  requiresFlags: ["prod_write_ready"],
  deniedOutput: ["you don't have a live, unwatched write window against reconciliation-master yet."],
  match: (input) => /\bwipe\b/.test(normalize(input)) && /\bledger\b/.test(normalize(input)),
  run: () => ({
    completesObjective: "resolve",
    tone: "warn",
    setsFlags: ["ending_wipe"],
    note: "reconciliation-master — every subsidiary balance zeroed across all 41 shells in one unattended run",
    output: [
      `[+] POST https://${IP_PROD}/api/reconciliation-master/run — session ${PROD_SESSION}`,
      "[+] override payload accepted — every subsidiary's nightly reconciliation input replaced with zero",
      "[+] job ran to completion, 02:14, unwatched",
      "",
      "every balance in the network is zero. the predatory ones and the ordinary ones. all of it, at once,",
      "with no way to tell them apart after the fact.",
    ],
  }),
};

const leakEvidence: CommandDef = {
  id: "leak-evidence",
  tool: "curl",
  help: "leak evidence",
  requiresFlags: ["prod_write_ready"],
  deniedOutput: ["you don't have a live, unwatched access window into reconciliation-master's audit trail yet."],
  match: (input) => /\bleak\b/.test(normalize(input)) && /\bevidence\b/.test(normalize(input)),
  run: () => ({
    completesObjective: "resolve",
    tone: "success",
    setsFlags: ["ending_leak"],
    note: "reconciliation-master audit trail extracted intact — no balance touched, full proof of the debt-and-data loop recovered",
    output: [
      `[+] GET https://${IP_PROD}/api/reconciliation-master/audit-trail — session ${PROD_SESSION}`,
      "[+] full audit trail extracted — every subsidiary's nightly submission, cross-referenced against",
      "    the actual source ledgers, for the last 6 years",
      "[+] no write performed. no balance changed. the job runs tonight exactly as it would have anyway",
      "",
      "the math is out. every account is exactly where it was this morning — but the proof of how the",
      "whole loop actually works no longer belongs only to Concord.",
    ],
  }),
};

export const campaignLevel6: ChainDef = {
  id: "campaign-6",
  difficulty: "campaign",
  order: 6,
  points: 560,
  title: "Zero Hour",
  codename: "CAMPAIGN — EPISODE 6: ZERO HOUR",
  summary: "Everything from every prior episode, spent all at once, on one unattended job.",
  briefing: [
    "Five episodes. A reused password, a careless vendor, a trust graph nobody audited as a whole, a",
    "door someone left open on purpose, and a platform's own logic finally read too closely.",
    "",
    "Tonight all of it points at one target: reconciliation-master, the nightly job every subsidiary in",
    "Concord Financial Group's network settles against, unattended, at 02:00. Whatever access this",
    "episode earns, it only has to hold for one run.",
    "",
    "What happens with that access is not a scripted outcome. It's a real decision, and it's yours.",
  ],
  debrief: [
    "Every prior episode fed this one directly: the reconciliation-access broker only issues a session",
    "to an identity with a real, earned footprint across the subsidiary network — which is exactly what",
    "five episodes of individually-unremarkable findings add up to. A staging mirror confirmed the exact",
    "write mechanism without ever touching production. An anomaly watchdog, blinded for one maintenance",
    "window, was the last thing standing between access and consequence.",
    "",
    "Then the job ran, once, exactly the way it was pointed.",
  ],
  nodes: [
    {
      id: "broker",
      org: "Reconciliation Access Broker",
      city: "Fort Renner",
      state: "NE",
      coords: jitteredCoords("NE", "campaign-6:broker"),
      ip: IP_BROKER,
      tagline: "Internal identity broker that mints sessions for the reconciliation pipeline",
      briefing: [
        `TARGET: Reconciliation Access Broker — ${IP_BROKER}`,
        "YOU HAVE: everything recovered across the last five episodes.",
        "",
        "This broker doesn't take a password. It checks whether the identity requesting a session has a",
        "real, earned footprint across the subsidiary network — an accumulated trail, not a single stolen key.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate the broker's session-issuance endpoint", tactic: "Discovery", requires: ["recon"] },
        {
          id: "footprint",
          label: "Present the accumulated footprint from every prior episode",
          tactic: "Initial Access",
          requires: ["identify"],
        },
        { id: "loot", label: "Recover the issued reconciliation-master session token", tactic: "Credential Access", requires: ["footprint"] },
        { id: "secure", label: "Require independent re-verification instead of trusting an accumulated footprint alone", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "The session endpoint doesn't want a single credential — it wants proof you've legitimately touched the network across every prior engagement. Just request it: `curl https://<ip>/api/broker/request-session`.",
        "If it comes back denied, it'll tell you exactly which prior engagement it couldn't confirm — that's not a hint you get to skip.",
      ],
      debrief: [
        "root cause: the broker's 'footprint' check aggregated signals from every subsidiary an identity",
        "had touched, but never independently re-verified any of them at request time — trusting its own",
        "prior logs was equivalent to trusting whoever generated them (CWE-290, authentication bypass by",
        "spoofed trust signal).",
        "fix applied: session issuance now requires a fresh, independently-verified credential in addition",
        "to the historical footprint, not the footprint alone.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_BROKER],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (reconciliation access broker)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.90 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-root",
          tool: "curl",
          requires: [IP_BROKER],
          forbids: ["request-session", "session-token"],
          help: "curl https://<ip>",
          requiresObjectives: ["recon"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_broker"],
            output: [
              '{"service":"reconciliation-access-broker","policy":"footprint-based, no static credential"}',
              "",
              "note: try requesting a session directly — /api/broker/request-session.",
            ],
          }),
        }),
        cmd({
          id: "request-session",
          tool: "curl",
          requires: ["broker/request-session"],
          help: "curl https://<ip>/api/broker/request-session",
          requiresFlags: ["found_broker", "ep1_complete", "ep2_complete", "ep3_complete", "ep4_complete", "ep5_complete"],
          deniedOutput: [
            "HTTP/1.1 403 Forbidden",
            '{"error":"insufficient footprint","detail":"no confirmed engagement history across the subsidiary network"}',
            "",
            "the broker isn't rejecting a bad password — it doesn't see a real trail behind this request yet.",
          ],
          run: () => ({
            completesObjective: "footprint",
            tone: "success",
            setsFlags: ["footprint_accepted"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"footprint":"confirmed","subsidiaries_touched":["bellwether","correll-data","palermo",',
              ' "driftwood","concord-cloud-services","ledger-systems","wellstone","concord-internal-ops",',
              ' "fenmore-loan-servicing","meridian-payment-rails","fenmore-batch-ops"],"decision":"issue"}',
              "",
              "[!] the broker trusted its own accumulated logs completely — it never asked you to re-prove",
              "    any single one of them right now.",
            ],
          }),
        }),
        cmd({
          id: "loot-token",
          tool: "curl",
          requires: ["broker/session-token"],
          help: "curl https://<ip>/api/broker/session-token",
          requiresFlags: ["footprint_accepted"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["have_prod_session"],
            note: `Reconciliation Access Broker — issued session token for reconciliation-master: ${PROD_SESSION}`,
            output: ["HTTP/1.1 200 OK", "", `{"session":"${PROD_SESSION}","scope":"reconciliation-master","ttl_minutes":90}`],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the broker actually issued a live session before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] session issuance now requires a fresh, independently-verified credential",
              "[+] historical footprint alone is no longer sufficient to mint a session",
              "[+] documented as authentication bypass via spoofed trust signal (CWE-290)",
              "",
              "RECONCILIATION ACCESS BROKER: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "staging",
      org: "Reconciliation Master — Staging Mirror",
      city: "Fenwick Crossing",
      state: "IN",
      coords: jitteredCoords("IN", "campaign-6:staging"),
      ip: IP_STAGING,
      tagline: "Full staging mirror of the production reconciliation job",
      briefing: [
        `TARGET: Reconciliation Master — Staging Mirror — ${IP_STAGING}`,
        `YOU HAVE: a session token from the access broker — ${PROD_SESSION}`,
        "",
        "Do not go near production with an unproven mechanism. This mirror exists to test the exact",
        "write path first, harmlessly.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate to the staging mirror with the broker-issued session", tactic: "Initial Access", requires: ["recon"] },
        { id: "test", label: "Execute a harmless test write against the staging job to confirm the mechanism", tactic: "Discovery", requires: ["auth"] },
        { id: "loot", label: "Recover the exact production write endpoint and required parameters", tactic: "Collection", requires: ["test"] },
        { id: "secure", label: "Require a change-ticket reference on every reconciliation write, staging included", tactic: "Remediation", requires: ["loot"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        `Authenticate with the broker session — \`curl -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/status\`.`,
        "Run a test write against the staging copy first, with dry_run set — confirm the mechanism works before you ever consider the real thing.",
        "The staging response mirrors production's exact parameter shape — read it closely, it's telling you precisely what production expects.",
      ],
      debrief: [
        "root cause: the staging mirror ran with identical code and near-identical trust boundaries to",
        "production, with no compensating control (like a mandatory change-ticket reference) distinguishing",
        "'harmless test' from 'live rehearsal for a production write' — a testing environment that taught",
        "an attacker exactly how to attack production, free of consequence.",
        "fix applied: staging now requires a change-ticket reference on every write, matching a control",
        "production already had, closing the asymmetry between the two.",
        "",
        "RECONCILIATION MASTER — STAGING MIRROR: SECURED.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_STAGING],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (reconciliation-master staging mirror)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.85 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth",
          tool: "curl",
          requires: ["authorization", PROD_SESSION, "api/status"],
          forbids: ["run"],
          help: `curl -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/status`,
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed"],
            output: [
              '{"env":"staging","service":"reconciliation-master-mirror","scope":"reconciliation-master"}',
              "",
              "[+] the broker's session token is honored here too — same trust, mirrored environment.",
            ],
          }),
        }),
        cmd({
          id: "test-write",
          tool: "curl",
          requires: ["reconciliation-master/run", "dry_run=true"],
          help: `curl -X POST -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/reconciliation-master/run -d "dry_run=true"`,
          requiresFlags: ["authed"],
          run: () => ({
            completesObjective: "test",
            tone: "success",
            setsFlags: ["mechanism_confirmed"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"dry_run":true,"would_affect":"all-subsidiaries","mechanism":"override-nightly-input"}',
              "",
              "[+] confirmed: a write here doesn't adjust individual balances, it replaces the entire",
              "    night's reconciliation input for every subsidiary at once.",
            ],
          }),
        }),
        cmd({
          id: "loot",
          tool: "curl",
          requires: ["production-endpoint"],
          help: "curl https://<ip>/api/production-endpoint",
          requiresFlags: ["mechanism_confirmed"],
          run: () => ({
            completesObjective: "loot",
            tone: "success",
            setsFlags: ["know_prod_endpoint"],
            note: `Reconciliation Master production write endpoint confirmed: https://${IP_PROD}/api/reconciliation-master/run — same session token, same parameters, no dry_run available`,
            output: [
              "HTTP/1.1 200 OK",
              "",
              `{"production_host":"${IP_PROD}","endpoint":"/api/reconciliation-master/run",`,
              ' "params":"identical to staging, minus dry_run","monitoring":"active — see anomaly watchdog"}',
              "",
              "[!] production has no dry-run mode, and something called an 'anomaly watchdog' is watching it.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["loot"],
          deniedOutput: ["confirm the exact production write mechanism before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] required a change-ticket reference on every reconciliation write, staging included",
              "[+] closed the asymmetry between staging and production trust boundaries",
              "",
              "RECONCILIATION MASTER — STAGING MIRROR: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "watchdog",
      org: "Reconciliation Master — Anomaly Watchdog",
      city: "Comstock",
      state: "MI",
      coords: jitteredCoords("MI", "campaign-6:watchdog"),
      ip: IP_WATCHDOG,
      tagline: "Monitoring service guarding the reconciliation job against unexpected writes",
      briefing: [
        `TARGET: Reconciliation Master — Anomaly Watchdog — ${IP_WATCHDOG}`,
        "KNOWN: this service pages an on-call engineer the moment reconciliation-master's write pattern",
        "deviates from its nightly norm.",
        "",
        "A write against production with this watching is a write that gets noticed, and stopped,",
        "before it finishes.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "identify", label: "Locate the watchdog's alerting configuration", tactic: "Discovery", requires: ["recon"] },
        { id: "analyze", label: "Determine how a maintenance window suppresses alerting", tactic: "Discovery", requires: ["identify"] },
        {
          id: "window",
          label: "Schedule a maintenance window covering the production write",
          tactic: "Defense Evasion",
          requires: ["analyze"],
        },
        { id: "secure", label: "Require a second approver on any maintenance window covering this job", tactic: "Remediation", requires: ["window"] },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        "Check the watchdog's own configuration API — `curl https://<ip>/api/config`. Alerting systems usually document their own suppression rules somewhere reachable.",
        "A single maintenance-window flag, set by anyone with write access to the config, appears to suppress every alert type for its duration — worth reading exactly how it's scoped.",
        `Schedule one covering the production write — \`curl -X POST -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/maintenance-window -d "start=now&duration_minutes=5&scope=reconciliation-master"\`.`,
      ],
      debrief: [
        "root cause: any session with write access to reconciliation-master could unilaterally schedule a",
        "maintenance window suppressing all watchdog alerting for that job — a single-approver control",
        "guarding the one system built specifically to catch unauthorized writes to reconciliation-master",
        "(CWE-284, improper access control on a compensating control).",
        "fix applied: maintenance windows covering this job now require a second, independent approver.",
        "",
        "RECONCILIATION MASTER — ANOMALY WATCHDOG: SECURED.",
      ],
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_WATCHDOG],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (anomaly watchdog)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.80 seconds",
            ],
          }),
        }),
        cmd({
          id: "curl-config",
          tool: "curl",
          requires: ["api/config"],
          forbids: ["maintenance-window"],
          help: "curl https://<ip>/api/config",
          requiresFlags: ["scanned"],
          run: () => ({
            completesObjective: "identify",
            tone: "success",
            setsFlags: ["found_config"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"alert_types":["balance-deviation","write-volume","off-hours-write"],',
              ' "suppression":"maintenance-window flag, any authenticated write-scope session may set it"}',
              "",
              "note: any session with write access to the job it's watching can also silence the thing",
              "watching it.",
            ],
          }),
        }),
        cmd({
          id: "analyze",
          tool: "curl",
          requires: ["maintenance-window/schema"],
          help: "curl https://<ip>/api/maintenance-window/schema",
          requiresFlags: ["found_config"],
          run: () => ({
            completesObjective: "analyze",
            tone: "success",
            setsFlags: ["know_window_schema"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"fields":["start","duration_minutes","scope"],"approval_required":false}',
              "",
              "[!] no second approval, no notification to anyone else. one session, one request, every",
              "    alert type for that job goes quiet for the window's duration.",
            ],
          }),
        }),
        cmd({
          id: "schedule-window",
          tool: "curl",
          requires: ["maintenance-window", "start=now", "reconciliation-master"],
          help: `curl -X POST -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/maintenance-window -d "start=now&duration_minutes=5&scope=reconciliation-master"`,
          requiresFlags: ["know_window_schema"],
          run: () => ({
            completesObjective: "window",
            tone: "success",
            setsFlags: ["maintenance_window"],
            output: [
              "HTTP/1.1 201 Created",
              "",
              '{"window":"scheduled","scope":"reconciliation-master","suppresses":"all alert types","duration_minutes":5}',
              "",
              "[+] the watchdog is blind to reconciliation-master for the next five minutes. that's the",
              "    entire window this operation gets.",
            ],
          }),
        }),
        {
          id: "secure",
          tool: "secure",
          match: match.startsWith("secure system", "secure", "remediate"),
          help: "secure system",
          requiresObjectives: ["window"],
          deniedOutput: ["confirm the maintenance window actually suppresses alerting before you file the fix."],
          run: () => ({
            completesObjective: "secure",
            tone: "success",
            output: [
              "[+] required a second, independent approver on any maintenance window covering this job",
              "[+] documented as improper access control on a compensating monitoring control (CWE-284)",
              "",
              "RECONCILIATION MASTER — ANOMALY WATCHDOG: SECURED",
            ],
          }),
        },
      ],
    },
    {
      id: "production",
      org: "Reconciliation Master — Production",
      city: "Millbrook",
      state: "VT",
      coords: jitteredCoords("VT", "campaign-6:production"),
      ip: IP_PROD,
      tagline: "The job every one of Concord's 41 subsidiaries settles against, nightly, unattended",
      briefing: [
        `TARGET: Reconciliation Master — Production — ${IP_PROD}`,
        `YOU HAVE: a live session (${PROD_SESSION}), a confirmed write mechanism, and a five-minute`,
        "maintenance window with the watchdog blind.",
        "",
        "This is the only node in the whole campaign where the last command isn't a fix. It's a choice,",
        "and it's the one nobody in the channel gets to make for you.",
      ],
      initialPrompt: "op@breachline:~$",
      motd: [],
      objectives: [
        { id: "recon", label: "Enumerate open services on the target", tactic: "Reconnaissance" },
        { id: "auth", label: "Authenticate with the broker-issued session inside the maintenance window", tactic: "Initial Access", requires: ["recon"] },
        {
          id: "prep",
          label: "Confirm live write access to reconciliation-master, unwatched, is actually open",
          tactic: "Discovery",
          requires: ["auth"],
        },
        {
          id: "resolve",
          label: "Decide: wipe the ledger, or leak the evidence. There is no third option tonight.",
          tactic: "Impact",
          requires: ["prep"],
        },
      ],
      hints: [
        "Recon first — `nmap -sV <ip>`.",
        `Authenticate inside the window — \`curl -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/status\`.`,
        "Confirm the write path is actually live and unwatched before you commit to anything — `curl https://<ip>/api/reconciliation-master/status`.",
        "Two commands are open to you now, and only one of them will run: `wipe ledger`, or `leak evidence`. Neither is a trick question. Choose.",
      ],
      debrief: [],
      debriefVariants: {
        ending_wipe: [
          "Every subsidiary balance in the network, zeroed in one unattended run — a full 41-shell write",
          "against reconciliation-master, unwatched for the five minutes it took.",
          "",
          "This is the show-accurate ending: total, unilateral, anonymous. It's also real vigilante",
          "justice with real collateral — the write doesn't know which accounts were predatory and which",
          "weren't. It zeroed all of them the same way.",
          "",
          "RECONCILIATION MASTER: WIPED.",
        ],
        ending_leak: [
          "No balance moved. What left the building instead was the reconciliation-master audit trail",
          "itself — six years of every subsidiary's submitted numbers, cross-referenced against the real",
          "source ledgers, extracted intact and handed to a regulator and a journalist who'd been asking",
          "the right questions with nothing to point at.",
          "",
          "This is the slower ending: due process instead of total erasure, a choice returned to",
          "institutions built to make it instead of taken by whoever was at the keyboard.",
          "",
          "RECONCILIATION MASTER: EVIDENCE EXTRACTED.",
        ],
      },
      commands: [
        cmd({
          id: "nmap",
          tool: "nmap",
          requires: [IP_PROD],
          help: "nmap -sV <ip>",
          run: () => ({
            completesObjective: "recon",
            tone: "success",
            setsFlags: ["scanned"],
            output: [
              "PORT    STATE SERVICE VERSION",
              "443/tcp open  https   nginx 1.24.0 (reconciliation-master, production)",
              "",
              "Nmap done: 1 IP address (1 host up) scanned in 3.95 seconds",
            ],
          }),
        }),
        cmd({
          id: "auth",
          tool: "curl",
          requires: ["authorization", PROD_SESSION, "api/status"],
          forbids: ["reconciliation-master/status"],
          help: `curl -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/status`,
          requiresFlags: ["scanned", "maintenance_window"],
          deniedOutput: ["401 Unauthorized — either the session or the maintenance window isn't in place yet."],
          run: () => ({
            completesObjective: "auth",
            tone: "success",
            setsFlags: ["authed_prod"],
            output: [
              '{"env":"production","service":"reconciliation-master","monitoring":"suppressed (maintenance window active)"}',
              "",
              "[+] production, live, and the watchdog can't see it right now.",
            ],
          }),
        }),
        cmd({
          id: "confirm-live",
          tool: "curl",
          requires: ["reconciliation-master/status"],
          help: `curl -H "Authorization: Bearer ${PROD_SESSION}" https://<ip>/api/reconciliation-master/status`,
          requiresFlags: ["authed_prod"],
          run: () => ({
            completesObjective: "prep",
            tone: "warn",
            setsFlags: ["prod_write_ready"],
            output: [
              "HTTP/1.1 200 OK",
              "",
              '{"job":"reconciliation-master","status":"armed, awaiting nightly run","subsidiaries":41,',
              ' "window_remaining_seconds":214}',
              "",
              "[!] the write path is live, unwatched, and closing in a little over three minutes.",
              "",
              "two commands are open now: `wipe ledger`, or `leak evidence`. only one of them runs.",
            ],
          }),
        }),
        wipeLedger,
        leakEvidence,
      ],
    },
  ],
};
